// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	question "tjxt/apps/exam/api/internal/handler/question"
	questionbiz "tjxt/apps/exam/api/internal/handler/questionbiz"
	"tjxt/apps/exam/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/questions",
				Handler: question.SaveQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/questions",
				Handler: question.ListQuestionsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/questions/:id",
				Handler: question.DeleteQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/questions/:id",
				Handler: question.GetQuestionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/questions/biz",
				Handler: questionbiz.AddQuestionBizHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/questions/biz",
				Handler: questionbiz.RemoveQuestionBizHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/questions/biz/:bizId",
				Handler: questionbiz.GetQuestionsByBizHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
