// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	admin "tjxt/apps/user/api/internal/handler/admin"
	student "tjxt/apps/user/api/internal/handler/student"
	user "tjxt/apps/user/api/internal/handler/user"
	"tjxt/apps/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/staffs/page",
				Handler: admin.PageQueryStaffsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/students/page",
				Handler: admin.PageQueryStudentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/teachers/page",
				Handler: admin.PageQueryTeachersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: admin.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:id",
				Handler: admin.UpdateUserByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:id/password/default",
				Handler: admin.ResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:id/status/:status",
				Handler: admin.UpdateUserStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/students/password",
				Handler: student.UpdateStudentPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/students/register",
				Handler: student.RegisterStudentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/checkCellphone",
				Handler: student.CheckCellPhoneHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/users",
				Handler: user.UpdateCurrentUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: user.GetUserByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/me",
				Handler: user.GetCurrentUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
