// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: exam.proto

package exam

import (
	"context"

	"tjxt/apps/exam/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty              = pb.Empty
	IdReply            = pb.IdReply
	IdReq              = pb.IdReq
	PageReq            = pb.PageReq
	QuestionBizListReq = pb.QuestionBizListReq
	QuestionBizReq     = pb.QuestionBizReq
	QuestionListReply  = pb.QuestionListReply
	QuestionListReq    = pb.QuestionListReq
	QuestionSaveReq    = pb.QuestionSaveReq
	QuestionVO         = pb.QuestionVO

	Exam interface {
		// 题目管理
		SaveQuestion(ctx context.Context, in *QuestionSaveReq, opts ...grpc.CallOption) (*IdReply, error)
		DeleteQuestion(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
		GetQuestion(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*QuestionVO, error)
		ListQuestions(ctx context.Context, in *QuestionListReq, opts ...grpc.CallOption) (*QuestionListReply, error)
		// 题目业务关联
		AddQuestionBiz(ctx context.Context, in *QuestionBizReq, opts ...grpc.CallOption) (*IdReply, error)
		RemoveQuestionBiz(ctx context.Context, in *QuestionBizReq, opts ...grpc.CallOption) (*Empty, error)
		GetQuestionsByBiz(ctx context.Context, in *QuestionBizListReq, opts ...grpc.CallOption) (*QuestionListReply, error)
	}

	defaultExam struct {
		cli zrpc.Client
	}
)

func NewExam(cli zrpc.Client) Exam {
	return &defaultExam{
		cli: cli,
	}
}

// 题目管理
func (m *defaultExam) SaveQuestion(ctx context.Context, in *QuestionSaveReq, opts ...grpc.CallOption) (*IdReply, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.SaveQuestion(ctx, in, opts...)
}

func (m *defaultExam) DeleteQuestion(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.DeleteQuestion(ctx, in, opts...)
}

func (m *defaultExam) GetQuestion(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*QuestionVO, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.GetQuestion(ctx, in, opts...)
}

func (m *defaultExam) ListQuestions(ctx context.Context, in *QuestionListReq, opts ...grpc.CallOption) (*QuestionListReply, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.ListQuestions(ctx, in, opts...)
}

// 题目业务关联
func (m *defaultExam) AddQuestionBiz(ctx context.Context, in *QuestionBizReq, opts ...grpc.CallOption) (*IdReply, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.AddQuestionBiz(ctx, in, opts...)
}

func (m *defaultExam) RemoveQuestionBiz(ctx context.Context, in *QuestionBizReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.RemoveQuestionBiz(ctx, in, opts...)
}

func (m *defaultExam) GetQuestionsByBiz(ctx context.Context, in *QuestionBizListReq, opts ...grpc.CallOption) (*QuestionListReply, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.GetQuestionsByBiz(ctx, in, opts...)
}
