// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: media.proto

package server

import (
	"context"

	"tjxt/apps/media/rpc/internal/logic"
	"tjxt/apps/media/rpc/internal/svc"
	"tjxt/apps/media/rpc/pb"
)

type MediaServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMediaServer
}

func NewMediaServer(svcCtx *svc.ServiceContext) *MediaServer {
	return &MediaServer{
		svcCtx: svcCtx,
	}
}

// 媒资管理
func (s *MediaServer) MediaGet(ctx context.Context, in *pb.MediaIdRequest) (*pb.MediaVO, error) {
	l := logic.NewMediaGetLogic(ctx, s.svcCtx)
	return l.MediaGet(in)
}

func (s *MediaServer) MediaList(ctx context.Context, in *pb.MediaListRequest) (*pb.MediaListReply, error) {
	l := logic.NewMediaListLogic(ctx, s.svcCtx)
	return l.MediaList(in)
}

func (s *MediaServer) MediaSave(ctx context.Context, in *pb.MediaSaveRequest) (*pb.MediaIdReply, error) {
	l := logic.NewMediaSaveLogic(ctx, s.svcCtx)
	return l.MediaSave(in)
}

func (s *MediaServer) MediaDelete(ctx context.Context, in *pb.MediaIdRequest) (*pb.Empty, error) {
	l := logic.NewMediaDeleteLogic(ctx, s.svcCtx)
	return l.MediaDelete(in)
}

// 签名相关
func (s *MediaServer) SignatureUpload(ctx context.Context, in *pb.SignatureRequest) (*pb.SignatureVO, error) {
	l := logic.NewSignatureUploadLogic(ctx, s.svcCtx)
	return l.SignatureUpload(in)
}

func (s *MediaServer) SignaturePreview(ctx context.Context, in *pb.SignatureRequest) (*pb.SignatureVO, error) {
	l := logic.NewSignaturePreviewLogic(ctx, s.svcCtx)
	return l.SignaturePreview(in)
}

func (s *MediaServer) SignaturePlay(ctx context.Context, in *pb.SignatureRequest) (*pb.SignatureVO, error) {
	l := logic.NewSignaturePlayLogic(ctx, s.svcCtx)
	return l.SignaturePlay(in)
}

// 文件管理
func (s *MediaServer) FileGet(ctx context.Context, in *pb.FileIdRequest) (*pb.FileVO, error) {
	l := logic.NewFileGetLogic(ctx, s.svcCtx)
	return l.FileGet(in)
}

func (s *MediaServer) FileSave(ctx context.Context, in *pb.FileSaveRequest) (*pb.FileIdReply, error) {
	l := logic.NewFileSaveLogic(ctx, s.svcCtx)
	return l.FileSave(in)
}

func (s *MediaServer) FileDelete(ctx context.Context, in *pb.FileIdRequest) (*pb.Empty, error) {
	l := logic.NewFileDeleteLogic(ctx, s.svcCtx)
	return l.FileDelete(in)
}
