// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: remark.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Remark_Like_FullMethodName             = "/remark.Remark/Like"
	Remark_QueryLikedBizIds_FullMethodName = "/remark.Remark/QueryLikedBizIds"
)

// RemarkClient is the client API for Remark service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemarkClient interface {
	Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*Empty, error)
	QueryLikedBizIds(ctx context.Context, in *LikedReq, opts ...grpc.CallOption) (*LikedResp, error)
}

type remarkClient struct {
	cc grpc.ClientConnInterface
}

func NewRemarkClient(cc grpc.ClientConnInterface) RemarkClient {
	return &remarkClient{cc}
}

func (c *remarkClient) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Remark_Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remarkClient) QueryLikedBizIds(ctx context.Context, in *LikedReq, opts ...grpc.CallOption) (*LikedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikedResp)
	err := c.cc.Invoke(ctx, Remark_QueryLikedBizIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemarkServer is the server API for Remark service.
// All implementations must embed UnimplementedRemarkServer
// for forward compatibility.
type RemarkServer interface {
	Like(context.Context, *LikeReq) (*Empty, error)
	QueryLikedBizIds(context.Context, *LikedReq) (*LikedResp, error)
	mustEmbedUnimplementedRemarkServer()
}

// UnimplementedRemarkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemarkServer struct{}

func (UnimplementedRemarkServer) Like(context.Context, *LikeReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedRemarkServer) QueryLikedBizIds(context.Context, *LikedReq) (*LikedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryLikedBizIds not implemented")
}
func (UnimplementedRemarkServer) mustEmbedUnimplementedRemarkServer() {}
func (UnimplementedRemarkServer) testEmbeddedByValue()                {}

// UnsafeRemarkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemarkServer will
// result in compilation errors.
type UnsafeRemarkServer interface {
	mustEmbedUnimplementedRemarkServer()
}

func RegisterRemarkServer(s grpc.ServiceRegistrar, srv RemarkServer) {
	// If the following call panics, it indicates UnimplementedRemarkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Remark_ServiceDesc, srv)
}

func _Remark_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemarkServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Remark_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemarkServer).Like(ctx, req.(*LikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remark_QueryLikedBizIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemarkServer).QueryLikedBizIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Remark_QueryLikedBizIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemarkServer).QueryLikedBizIds(ctx, req.(*LikedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Remark_ServiceDesc is the grpc.ServiceDesc for Remark service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Remark_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remark.Remark",
	HandlerType: (*RemarkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Like",
			Handler:    _Remark_Like_Handler,
		},
		{
			MethodName: "QueryLikedBizIds",
			Handler:    _Remark_QueryLikedBizIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remark.proto",
}
