// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"tjxt/apps/learning/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/learning-records",
				Handler: LearningRecordCommitHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/learning-records/course/:courseId",
				Handler: LearningRecordsByCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/lessons/:courseId",
				Handler: LessonGetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/lessons/:courseId/count",
				Handler: LessonCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/lessons/:courseId/valid",
				Handler: LessonValidHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/lessons/now",
				Handler: LearningNowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/lessons/page",
				Handler: LessonPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/lessons/plans",
				Handler: PlanPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/lessons/plans",
				Handler: PlanSaveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
