// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空消息
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

// 通用ID请求/回复
type IdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdReq) Reset() {
	*x = IdReq{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReq) ProtoMessage() {}

func (x *IdReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReq.ProtoReflect.Descriptor instead.
func (*IdReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *IdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdReply) Reset() {
	*x = IdReply{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReply) ProtoMessage() {}

func (x *IdReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReply.ProtoReflect.Descriptor instead.
func (*IdReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *IdReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int32                  `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *PageReq) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *PageReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ==================== 通知模板 ====================
type NoticeTemplateVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	IsSmsTemplate bool                   `protobuf:"varint,8,opt,name=isSmsTemplate,proto3" json:"isSmsTemplate,omitempty"`
	CreateTime    string                 `protobuf:"bytes,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeTemplateVO) Reset() {
	*x = NoticeTemplateVO{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeTemplateVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeTemplateVO) ProtoMessage() {}

func (x *NoticeTemplateVO) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeTemplateVO.ProtoReflect.Descriptor instead.
func (*NoticeTemplateVO) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *NoticeTemplateVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoticeTemplateVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NoticeTemplateVO) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NoticeTemplateVO) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *NoticeTemplateVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *NoticeTemplateVO) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoticeTemplateVO) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoticeTemplateVO) GetIsSmsTemplate() bool {
	if x != nil {
		return x.IsSmsTemplate
	}
	return false
}

func (x *NoticeTemplateVO) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type NoticeTemplateSaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	IsSmsTemplate bool                   `protobuf:"varint,7,opt,name=isSmsTemplate,proto3" json:"isSmsTemplate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeTemplateSaveReq) Reset() {
	*x = NoticeTemplateSaveReq{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeTemplateSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeTemplateSaveReq) ProtoMessage() {}

func (x *NoticeTemplateSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeTemplateSaveReq.ProtoReflect.Descriptor instead.
func (*NoticeTemplateSaveReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *NoticeTemplateSaveReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoticeTemplateSaveReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NoticeTemplateSaveReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NoticeTemplateSaveReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *NoticeTemplateSaveReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoticeTemplateSaveReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoticeTemplateSaveReq) GetIsSmsTemplate() bool {
	if x != nil {
		return x.IsSmsTemplate
	}
	return false
}

type NoticeTemplateListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*NoticeTemplateVO    `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeTemplateListReply) Reset() {
	*x = NoticeTemplateListReply{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeTemplateListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeTemplateListReply) ProtoMessage() {}

func (x *NoticeTemplateListReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeTemplateListReply.ProtoReflect.Descriptor instead.
func (*NoticeTemplateListReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *NoticeTemplateListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NoticeTemplateListReply) GetList() []*NoticeTemplateVO {
	if x != nil {
		return x.List
	}
	return nil
}

// ==================== 通知任务 ====================
type NoticeTaskVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId    int64                  `protobuf:"varint,2,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Partial       bool                   `protobuf:"varint,4,opt,name=partial,proto3" json:"partial,omitempty"`
	PushTime      string                 `protobuf:"bytes,5,opt,name=pushTime,proto3" json:"pushTime,omitempty"`
	Interval      int32                  `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,7,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	MaxTimes      int32                  `protobuf:"varint,8,opt,name=maxTimes,proto3" json:"maxTimes,omitempty"`
	Finished      bool                   `protobuf:"varint,9,opt,name=finished,proto3" json:"finished,omitempty"`
	CreateTime    string                 `protobuf:"bytes,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeTaskVO) Reset() {
	*x = NoticeTaskVO{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeTaskVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeTaskVO) ProtoMessage() {}

func (x *NoticeTaskVO) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeTaskVO.ProtoReflect.Descriptor instead.
func (*NoticeTaskVO) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *NoticeTaskVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoticeTaskVO) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *NoticeTaskVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NoticeTaskVO) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *NoticeTaskVO) GetPushTime() string {
	if x != nil {
		return x.PushTime
	}
	return ""
}

func (x *NoticeTaskVO) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *NoticeTaskVO) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *NoticeTaskVO) GetMaxTimes() int32 {
	if x != nil {
		return x.MaxTimes
	}
	return 0
}

func (x *NoticeTaskVO) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *NoticeTaskVO) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type NoticeTaskSaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId    int64                  `protobuf:"varint,2,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Partial       bool                   `protobuf:"varint,4,opt,name=partial,proto3" json:"partial,omitempty"`
	PushTime      string                 `protobuf:"bytes,5,opt,name=pushTime,proto3" json:"pushTime,omitempty"`
	Interval      int32                  `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,7,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	MaxTimes      int32                  `protobuf:"varint,8,opt,name=maxTimes,proto3" json:"maxTimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeTaskSaveReq) Reset() {
	*x = NoticeTaskSaveReq{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeTaskSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeTaskSaveReq) ProtoMessage() {}

func (x *NoticeTaskSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeTaskSaveReq.ProtoReflect.Descriptor instead.
func (*NoticeTaskSaveReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *NoticeTaskSaveReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoticeTaskSaveReq) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *NoticeTaskSaveReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NoticeTaskSaveReq) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *NoticeTaskSaveReq) GetPushTime() string {
	if x != nil {
		return x.PushTime
	}
	return ""
}

func (x *NoticeTaskSaveReq) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *NoticeTaskSaveReq) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *NoticeTaskSaveReq) GetMaxTimes() int32 {
	if x != nil {
		return x.MaxTimes
	}
	return 0
}

type NoticeTaskListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*NoticeTaskVO        `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeTaskListReply) Reset() {
	*x = NoticeTaskListReply{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeTaskListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeTaskListReply) ProtoMessage() {}

func (x *NoticeTaskListReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeTaskListReply.ProtoReflect.Descriptor instead.
func (*NoticeTaskListReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *NoticeTaskListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NoticeTaskListReply) GetList() []*NoticeTaskVO {
	if x != nil {
		return x.List
	}
	return nil
}

// ==================== 短信模板 ====================
type MessageTemplateVO struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PlatformCode      string                 `protobuf:"bytes,3,opt,name=platformCode,proto3" json:"platformCode,omitempty"`
	SignName          string                 `protobuf:"bytes,4,opt,name=signName,proto3" json:"signName,omitempty"`
	ThirdTemplateCode string                 `protobuf:"bytes,5,opt,name=thirdTemplateCode,proto3" json:"thirdTemplateCode,omitempty"`
	Content           string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	TemplateId        int64                  `protobuf:"varint,7,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Status            int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime        string                 `protobuf:"bytes,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessageTemplateVO) Reset() {
	*x = MessageTemplateVO{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTemplateVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTemplateVO) ProtoMessage() {}

func (x *MessageTemplateVO) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTemplateVO.ProtoReflect.Descriptor instead.
func (*MessageTemplateVO) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *MessageTemplateVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageTemplateVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageTemplateVO) GetPlatformCode() string {
	if x != nil {
		return x.PlatformCode
	}
	return ""
}

func (x *MessageTemplateVO) GetSignName() string {
	if x != nil {
		return x.SignName
	}
	return ""
}

func (x *MessageTemplateVO) GetThirdTemplateCode() string {
	if x != nil {
		return x.ThirdTemplateCode
	}
	return ""
}

func (x *MessageTemplateVO) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageTemplateVO) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *MessageTemplateVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MessageTemplateVO) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type MessageTemplateSaveReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PlatformCode      string                 `protobuf:"bytes,3,opt,name=platformCode,proto3" json:"platformCode,omitempty"`
	SignName          string                 `protobuf:"bytes,4,opt,name=signName,proto3" json:"signName,omitempty"`
	ThirdTemplateCode string                 `protobuf:"bytes,5,opt,name=thirdTemplateCode,proto3" json:"thirdTemplateCode,omitempty"`
	Content           string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	TemplateId        int64                  `protobuf:"varint,7,opt,name=templateId,proto3" json:"templateId,omitempty"`
	Status            int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessageTemplateSaveReq) Reset() {
	*x = MessageTemplateSaveReq{}
	mi := &file_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTemplateSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTemplateSaveReq) ProtoMessage() {}

func (x *MessageTemplateSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTemplateSaveReq.ProtoReflect.Descriptor instead.
func (*MessageTemplateSaveReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *MessageTemplateSaveReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageTemplateSaveReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageTemplateSaveReq) GetPlatformCode() string {
	if x != nil {
		return x.PlatformCode
	}
	return ""
}

func (x *MessageTemplateSaveReq) GetSignName() string {
	if x != nil {
		return x.SignName
	}
	return ""
}

func (x *MessageTemplateSaveReq) GetThirdTemplateCode() string {
	if x != nil {
		return x.ThirdTemplateCode
	}
	return ""
}

func (x *MessageTemplateSaveReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageTemplateSaveReq) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *MessageTemplateSaveReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MessageTemplateListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*MessageTemplateVO   `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageTemplateListReply) Reset() {
	*x = MessageTemplateListReply{}
	mi := &file_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTemplateListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTemplateListReply) ProtoMessage() {}

func (x *MessageTemplateListReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTemplateListReply.ProtoReflect.Descriptor instead.
func (*MessageTemplateListReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{12}
}

func (x *MessageTemplateListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MessageTemplateListReply) GetList() []*MessageTemplateVO {
	if x != nil {
		return x.List
	}
	return nil
}

// ==================== 短信平台 ====================
type SmsPlatformVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsPlatformVO) Reset() {
	*x = SmsPlatformVO{}
	mi := &file_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsPlatformVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsPlatformVO) ProtoMessage() {}

func (x *SmsPlatformVO) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsPlatformVO.ProtoReflect.Descriptor instead.
func (*SmsPlatformVO) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{13}
}

func (x *SmsPlatformVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SmsPlatformVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SmsPlatformVO) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SmsPlatformVO) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SmsPlatformVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SmsPlatformListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*SmsPlatformVO       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsPlatformListReply) Reset() {
	*x = SmsPlatformListReply{}
	mi := &file_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsPlatformListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsPlatformListReply) ProtoMessage() {}

func (x *SmsPlatformListReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsPlatformListReply.ProtoReflect.Descriptor instead.
func (*SmsPlatformListReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{14}
}

func (x *SmsPlatformListReply) GetList() []*SmsPlatformVO {
	if x != nil {
		return x.List
	}
	return nil
}

// ==================== 用户收件箱 ====================
type UserInboxVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	IsRead        bool                   `protobuf:"varint,6,opt,name=isRead,proto3" json:"isRead,omitempty"`
	Publisher     int64                  `protobuf:"varint,7,opt,name=publisher,proto3" json:"publisher,omitempty"`
	PushTime      string                 `protobuf:"bytes,8,opt,name=pushTime,proto3" json:"pushTime,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,9,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInboxVO) Reset() {
	*x = UserInboxVO{}
	mi := &file_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInboxVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInboxVO) ProtoMessage() {}

func (x *UserInboxVO) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInboxVO.ProtoReflect.Descriptor instead.
func (*UserInboxVO) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{15}
}

func (x *UserInboxVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInboxVO) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInboxVO) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UserInboxVO) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserInboxVO) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UserInboxVO) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *UserInboxVO) GetPublisher() int64 {
	if x != nil {
		return x.Publisher
	}
	return 0
}

func (x *UserInboxVO) GetPushTime() string {
	if x != nil {
		return x.PushTime
	}
	return ""
}

func (x *UserInboxVO) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

type SendNoticeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Publisher     int64                  `protobuf:"varint,5,opt,name=publisher,proto3" json:"publisher,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,6,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNoticeReq) Reset() {
	*x = SendNoticeReq{}
	mi := &file_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNoticeReq) ProtoMessage() {}

func (x *SendNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNoticeReq.ProtoReflect.Descriptor instead.
func (*SendNoticeReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{16}
}

func (x *SendNoticeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendNoticeReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SendNoticeReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendNoticeReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendNoticeReq) GetPublisher() int64 {
	if x != nil {
		return x.Publisher
	}
	return 0
}

func (x *SendNoticeReq) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

type InboxPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int32                  `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxPageReq) Reset() {
	*x = InboxPageReq{}
	mi := &file_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxPageReq) ProtoMessage() {}

func (x *InboxPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxPageReq.ProtoReflect.Descriptor instead.
func (*InboxPageReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{17}
}

func (x *InboxPageReq) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *InboxPageReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *InboxPageReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InboxPageReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type InboxListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*UserInboxVO         `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxListReply) Reset() {
	*x = InboxListReply{}
	mi := &file_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxListReply) ProtoMessage() {}

func (x *InboxListReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxListReply.ProtoReflect.Descriptor instead.
func (*InboxListReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{18}
}

func (x *InboxListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *InboxListReply) GetList() []*UserInboxVO {
	if x != nil {
		return x.List
	}
	return nil
}

// ==================== 公告 ====================
type PublicNoticeVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	PushTime      string                 `protobuf:"bytes,5,opt,name=pushTime,proto3" json:"pushTime,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,6,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicNoticeVO) Reset() {
	*x = PublicNoticeVO{}
	mi := &file_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicNoticeVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicNoticeVO) ProtoMessage() {}

func (x *PublicNoticeVO) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicNoticeVO.ProtoReflect.Descriptor instead.
func (*PublicNoticeVO) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{19}
}

func (x *PublicNoticeVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicNoticeVO) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublicNoticeVO) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PublicNoticeVO) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PublicNoticeVO) GetPushTime() string {
	if x != nil {
		return x.PushTime
	}
	return ""
}

func (x *PublicNoticeVO) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

type PublicNoticeSaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	PushTime      string                 `protobuf:"bytes,5,opt,name=pushTime,proto3" json:"pushTime,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,6,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicNoticeSaveReq) Reset() {
	*x = PublicNoticeSaveReq{}
	mi := &file_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicNoticeSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicNoticeSaveReq) ProtoMessage() {}

func (x *PublicNoticeSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicNoticeSaveReq.ProtoReflect.Descriptor instead.
func (*PublicNoticeSaveReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{20}
}

func (x *PublicNoticeSaveReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublicNoticeSaveReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublicNoticeSaveReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PublicNoticeSaveReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PublicNoticeSaveReq) GetPushTime() string {
	if x != nil {
		return x.PushTime
	}
	return ""
}

func (x *PublicNoticeSaveReq) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

type PublicNoticeListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*PublicNoticeVO      `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicNoticeListReply) Reset() {
	*x = PublicNoticeListReply{}
	mi := &file_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicNoticeListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicNoticeListReply) ProtoMessage() {}

func (x *PublicNoticeListReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicNoticeListReply.ProtoReflect.Descriptor instead.
func (*PublicNoticeListReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{21}
}

func (x *PublicNoticeListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PublicNoticeListReply) GetList() []*PublicNoticeVO {
	if x != nil {
		return x.List
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"\a\n" +
	"\x05Empty\"\x17\n" +
	"\x05IdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x19\n" +
	"\aIdReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\aPageReq\x12\x16\n" +
	"\x06pageNo\x18\x01 \x01(\x05R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"\xec\x01\n" +
	"\x10NoticeTemplateVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12$\n" +
	"\risSmsTemplate\x18\b \x01(\bR\risSmsTemplate\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\tR\n" +
	"createTime\"\xb9\x01\n" +
	"\x15NoticeTemplateSaveReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12$\n" +
	"\risSmsTemplate\x18\a \x01(\bR\risSmsTemplate\"^\n" +
	"\x17NoticeTemplateListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12-\n" +
	"\x04list\x18\x02 \x03(\v2\x19.message.NoticeTemplateVOR\x04list\"\x9c\x02\n" +
	"\fNoticeTaskVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"templateId\x18\x02 \x01(\x03R\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\apartial\x18\x04 \x01(\bR\apartial\x12\x1a\n" +
	"\bpushTime\x18\x05 \x01(\tR\bpushTime\x12\x1a\n" +
	"\binterval\x18\x06 \x01(\x05R\binterval\x12\x1e\n" +
	"\n" +
	"expireTime\x18\a \x01(\tR\n" +
	"expireTime\x12\x1a\n" +
	"\bmaxTimes\x18\b \x01(\x05R\bmaxTimes\x12\x1a\n" +
	"\bfinished\x18\t \x01(\bR\bfinished\x12\x1e\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\tR\n" +
	"createTime\"\xe5\x01\n" +
	"\x11NoticeTaskSaveReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"templateId\x18\x02 \x01(\x03R\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\apartial\x18\x04 \x01(\bR\apartial\x12\x1a\n" +
	"\bpushTime\x18\x05 \x01(\tR\bpushTime\x12\x1a\n" +
	"\binterval\x18\x06 \x01(\x05R\binterval\x12\x1e\n" +
	"\n" +
	"expireTime\x18\a \x01(\tR\n" +
	"expireTime\x12\x1a\n" +
	"\bmaxTimes\x18\b \x01(\x05R\bmaxTimes\"V\n" +
	"\x13NoticeTaskListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12)\n" +
	"\x04list\x18\x02 \x03(\v2\x15.message.NoticeTaskVOR\x04list\"\x97\x02\n" +
	"\x11MessageTemplateVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fplatformCode\x18\x03 \x01(\tR\fplatformCode\x12\x1a\n" +
	"\bsignName\x18\x04 \x01(\tR\bsignName\x12,\n" +
	"\x11thirdTemplateCode\x18\x05 \x01(\tR\x11thirdTemplateCode\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"templateId\x18\a \x01(\x03R\n" +
	"templateId\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\tR\n" +
	"createTime\"\xfc\x01\n" +
	"\x16MessageTemplateSaveReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fplatformCode\x18\x03 \x01(\tR\fplatformCode\x12\x1a\n" +
	"\bsignName\x18\x04 \x01(\tR\bsignName\x12,\n" +
	"\x11thirdTemplateCode\x18\x05 \x01(\tR\x11thirdTemplateCode\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"templateId\x18\a \x01(\x03R\n" +
	"templateId\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\"`\n" +
	"\x18MessageTemplateListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12.\n" +
	"\x04list\x18\x02 \x03(\v2\x1a.message.MessageTemplateVOR\x04list\"{\n" +
	"\rSmsPlatformVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"B\n" +
	"\x14SmsPlatformListReply\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.message.SmsPlatformVOR\x04list\"\xeb\x01\n" +
	"\vUserInboxVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06isRead\x18\x06 \x01(\bR\x06isRead\x12\x1c\n" +
	"\tpublisher\x18\a \x01(\x03R\tpublisher\x12\x1a\n" +
	"\bpushTime\x18\b \x01(\tR\bpushTime\x12\x1e\n" +
	"\n" +
	"expireTime\x18\t \x01(\tR\n" +
	"expireTime\"\xa9\x01\n" +
	"\rSendNoticeReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\tpublisher\x18\x05 \x01(\x03R\tpublisher\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x06 \x01(\tR\n" +
	"expireTime\"n\n" +
	"\fInboxPageReq\x12\x16\n" +
	"\x06pageNo\x18\x01 \x01(\x05R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\"P\n" +
	"\x0eInboxListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12(\n" +
	"\x04list\x18\x02 \x03(\v2\x14.message.UserInboxVOR\x04list\"\xa0\x01\n" +
	"\x0ePublicNoticeVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x1a\n" +
	"\bpushTime\x18\x05 \x01(\tR\bpushTime\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x06 \x01(\tR\n" +
	"expireTime\"\xa5\x01\n" +
	"\x13PublicNoticeSaveReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x1a\n" +
	"\bpushTime\x18\x05 \x01(\tR\bpushTime\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x06 \x01(\tR\n" +
	"expireTime\"Z\n" +
	"\x15PublicNoticeListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12+\n" +
	"\x04list\x18\x02 \x03(\v2\x17.message.PublicNoticeVOR\x04list2\xac\t\n" +
	"\aMessage\x12F\n" +
	"\x12SaveNoticeTemplate\x12\x1e.message.NoticeTemplateSaveReq\x1a\x10.message.IdReply\x126\n" +
	"\x14DeleteNoticeTemplate\x12\x0e.message.IdReq\x1a\x0e.message.Empty\x12>\n" +
	"\x11GetNoticeTemplate\x12\x0e.message.IdReq\x1a\x19.message.NoticeTemplateVO\x12I\n" +
	"\x13ListNoticeTemplates\x12\x10.message.PageReq\x1a .message.NoticeTemplateListReply\x12>\n" +
	"\x0eSaveNoticeTask\x12\x1a.message.NoticeTaskSaveReq\x1a\x10.message.IdReply\x122\n" +
	"\x10DeleteNoticeTask\x12\x0e.message.IdReq\x1a\x0e.message.Empty\x126\n" +
	"\rGetNoticeTask\x12\x0e.message.IdReq\x1a\x15.message.NoticeTaskVO\x12A\n" +
	"\x0fListNoticeTasks\x12\x10.message.PageReq\x1a\x1c.message.NoticeTaskListReply\x12H\n" +
	"\x13SaveMessageTemplate\x12\x1f.message.MessageTemplateSaveReq\x1a\x10.message.IdReply\x127\n" +
	"\x15DeleteMessageTemplate\x12\x0e.message.IdReq\x1a\x0e.message.Empty\x12K\n" +
	"\x14ListMessageTemplates\x12\x10.message.PageReq\x1a!.message.MessageTemplateListReply\x12A\n" +
	"\x10ListSmsPlatforms\x12\x0e.message.Empty\x1a\x1d.message.SmsPlatformListReply\x126\n" +
	"\n" +
	"SendNotice\x12\x16.message.SendNoticeReq\x1a\x10.message.IdReply\x12;\n" +
	"\tListInbox\x12\x15.message.InboxPageReq\x1a\x17.message.InboxListReply\x12/\n" +
	"\rMarkInboxRead\x12\x0e.message.IdReq\x1a\x0e.message.Empty\x12-\n" +
	"\vDeleteInbox\x12\x0e.message.IdReq\x1a\x0e.message.Empty\x12B\n" +
	"\x10SavePublicNotice\x12\x1c.message.PublicNoticeSaveReq\x1a\x10.message.IdReply\x124\n" +
	"\x12DeletePublicNotice\x12\x0e.message.IdReq\x1a\x0e.message.Empty\x12E\n" +
	"\x11ListPublicNotices\x12\x10.message.PageReq\x1a\x1e.message.PublicNoticeListReplyB\x06Z\x04./pbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_message_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: message.Empty
	(*IdReq)(nil),                    // 1: message.IdReq
	(*IdReply)(nil),                  // 2: message.IdReply
	(*PageReq)(nil),                  // 3: message.PageReq
	(*NoticeTemplateVO)(nil),         // 4: message.NoticeTemplateVO
	(*NoticeTemplateSaveReq)(nil),    // 5: message.NoticeTemplateSaveReq
	(*NoticeTemplateListReply)(nil),  // 6: message.NoticeTemplateListReply
	(*NoticeTaskVO)(nil),             // 7: message.NoticeTaskVO
	(*NoticeTaskSaveReq)(nil),        // 8: message.NoticeTaskSaveReq
	(*NoticeTaskListReply)(nil),      // 9: message.NoticeTaskListReply
	(*MessageTemplateVO)(nil),        // 10: message.MessageTemplateVO
	(*MessageTemplateSaveReq)(nil),   // 11: message.MessageTemplateSaveReq
	(*MessageTemplateListReply)(nil), // 12: message.MessageTemplateListReply
	(*SmsPlatformVO)(nil),            // 13: message.SmsPlatformVO
	(*SmsPlatformListReply)(nil),     // 14: message.SmsPlatformListReply
	(*UserInboxVO)(nil),              // 15: message.UserInboxVO
	(*SendNoticeReq)(nil),            // 16: message.SendNoticeReq
	(*InboxPageReq)(nil),             // 17: message.InboxPageReq
	(*InboxListReply)(nil),           // 18: message.InboxListReply
	(*PublicNoticeVO)(nil),           // 19: message.PublicNoticeVO
	(*PublicNoticeSaveReq)(nil),      // 20: message.PublicNoticeSaveReq
	(*PublicNoticeListReply)(nil),    // 21: message.PublicNoticeListReply
}
var file_message_proto_depIdxs = []int32{
	4,  // 0: message.NoticeTemplateListReply.list:type_name -> message.NoticeTemplateVO
	7,  // 1: message.NoticeTaskListReply.list:type_name -> message.NoticeTaskVO
	10, // 2: message.MessageTemplateListReply.list:type_name -> message.MessageTemplateVO
	13, // 3: message.SmsPlatformListReply.list:type_name -> message.SmsPlatformVO
	15, // 4: message.InboxListReply.list:type_name -> message.UserInboxVO
	19, // 5: message.PublicNoticeListReply.list:type_name -> message.PublicNoticeVO
	5,  // 6: message.Message.SaveNoticeTemplate:input_type -> message.NoticeTemplateSaveReq
	1,  // 7: message.Message.DeleteNoticeTemplate:input_type -> message.IdReq
	1,  // 8: message.Message.GetNoticeTemplate:input_type -> message.IdReq
	3,  // 9: message.Message.ListNoticeTemplates:input_type -> message.PageReq
	8,  // 10: message.Message.SaveNoticeTask:input_type -> message.NoticeTaskSaveReq
	1,  // 11: message.Message.DeleteNoticeTask:input_type -> message.IdReq
	1,  // 12: message.Message.GetNoticeTask:input_type -> message.IdReq
	3,  // 13: message.Message.ListNoticeTasks:input_type -> message.PageReq
	11, // 14: message.Message.SaveMessageTemplate:input_type -> message.MessageTemplateSaveReq
	1,  // 15: message.Message.DeleteMessageTemplate:input_type -> message.IdReq
	3,  // 16: message.Message.ListMessageTemplates:input_type -> message.PageReq
	0,  // 17: message.Message.ListSmsPlatforms:input_type -> message.Empty
	16, // 18: message.Message.SendNotice:input_type -> message.SendNoticeReq
	17, // 19: message.Message.ListInbox:input_type -> message.InboxPageReq
	1,  // 20: message.Message.MarkInboxRead:input_type -> message.IdReq
	1,  // 21: message.Message.DeleteInbox:input_type -> message.IdReq
	20, // 22: message.Message.SavePublicNotice:input_type -> message.PublicNoticeSaveReq
	1,  // 23: message.Message.DeletePublicNotice:input_type -> message.IdReq
	3,  // 24: message.Message.ListPublicNotices:input_type -> message.PageReq
	2,  // 25: message.Message.SaveNoticeTemplate:output_type -> message.IdReply
	0,  // 26: message.Message.DeleteNoticeTemplate:output_type -> message.Empty
	4,  // 27: message.Message.GetNoticeTemplate:output_type -> message.NoticeTemplateVO
	6,  // 28: message.Message.ListNoticeTemplates:output_type -> message.NoticeTemplateListReply
	2,  // 29: message.Message.SaveNoticeTask:output_type -> message.IdReply
	0,  // 30: message.Message.DeleteNoticeTask:output_type -> message.Empty
	7,  // 31: message.Message.GetNoticeTask:output_type -> message.NoticeTaskVO
	9,  // 32: message.Message.ListNoticeTasks:output_type -> message.NoticeTaskListReply
	2,  // 33: message.Message.SaveMessageTemplate:output_type -> message.IdReply
	0,  // 34: message.Message.DeleteMessageTemplate:output_type -> message.Empty
	12, // 35: message.Message.ListMessageTemplates:output_type -> message.MessageTemplateListReply
	14, // 36: message.Message.ListSmsPlatforms:output_type -> message.SmsPlatformListReply
	2,  // 37: message.Message.SendNotice:output_type -> message.IdReply
	18, // 38: message.Message.ListInbox:output_type -> message.InboxListReply
	0,  // 39: message.Message.MarkInboxRead:output_type -> message.Empty
	0,  // 40: message.Message.DeleteInbox:output_type -> message.Empty
	2,  // 41: message.Message.SavePublicNotice:output_type -> message.IdReply
	0,  // 42: message.Message.DeletePublicNotice:output_type -> message.Empty
	21, // 43: message.Message.ListPublicNotices:output_type -> message.PublicNoticeListReply
	25, // [25:44] is the sub-list for method output_type
	6,  // [6:25] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
