// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderDetailFieldNames          = builder.RawFieldNames(&OrderDetail{})
	orderDetailRows                = strings.Join(orderDetailFieldNames, ",")
	orderDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(orderDetailFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(orderDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTjTradeOrderDetailIdPrefix = "cache:tjTrade:orderDetail:id:"
)

type (
	orderDetailModel interface {
		Insert(ctx context.Context, data *OrderDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OrderDetail, error)
		Update(ctx context.Context, data *OrderDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOrderDetailModel struct {
		sqlc.CachedConn
		table string
	}

	OrderDetail struct {
		Id               int64         `db:"id"`                 // 订单明细id
		OrderId          int64         `db:"order_id"`           // 订单id
		UserId           int64         `db:"user_id"`            // 用户id
		CourseId         int64         `db:"course_id"`          // 课程id
		Price            int64         `db:"price"`              // 课程价格
		Name             string        `db:"name"`               // 课程名称
		CoverUrl         string        `db:"cover_url"`          // 封面地址
		ValidDuration    sql.NullInt64 `db:"valid_duration"`     // 课程学习有效期，单位月。空则代表永久有效
		CourseExpireTime sql.NullTime  `db:"course_expire_time"` // 课程学习的过期时间，支付成功开始计时
		DiscountAmount   int64         `db:"discount_amount"`    // 折扣金额
		RealPayAmount    int64         `db:"real_pay_amount"`    // 实付金额
		Status           int64         `db:"status"`             // 订单详情状态，1：待支付，2：已支付，3：已关闭，4：已完成，5：已报名
		RefundStatus     sql.NullInt64 `db:"refund_status"`      // 1：待审批，2：取消退款，3：同意退款，4：拒绝退款，5：退款成功，6：退款失败'
		PayChannel       string        `db:"pay_channel"`        // 支付渠道名称
		CreateTime       time.Time     `db:"create_time"`        // 创建时间
		UpdateTime       time.Time     `db:"update_time"`        // 更新时间
		Creater          int64         `db:"creater"`            // 创建人
		Updater          int64         `db:"updater"`            // 更新人
	}
)

func newOrderDetailModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOrderDetailModel {
	return &defaultOrderDetailModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`order_detail`",
	}
}

func (m *defaultOrderDetailModel) Delete(ctx context.Context, id int64) error {
	tjTradeOrderDetailIdKey := fmt.Sprintf("%s%v", cacheTjTradeOrderDetailIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tjTradeOrderDetailIdKey)
	return err
}

func (m *defaultOrderDetailModel) FindOne(ctx context.Context, id int64) (*OrderDetail, error) {
	tjTradeOrderDetailIdKey := fmt.Sprintf("%s%v", cacheTjTradeOrderDetailIdPrefix, id)
	var resp OrderDetail
	err := m.QueryRowCtx(ctx, &resp, tjTradeOrderDetailIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderDetailRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderDetailModel) Insert(ctx context.Context, data *OrderDetail) (sql.Result, error) {
	tjTradeOrderDetailIdKey := fmt.Sprintf("%s%v", cacheTjTradeOrderDetailIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderDetailRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.OrderId, data.UserId, data.CourseId, data.Price, data.Name, data.CoverUrl, data.ValidDuration, data.CourseExpireTime, data.DiscountAmount, data.RealPayAmount, data.Status, data.RefundStatus, data.PayChannel, data.Creater, data.Updater)
	}, tjTradeOrderDetailIdKey)
	return ret, err
}

func (m *defaultOrderDetailModel) Update(ctx context.Context, data *OrderDetail) error {
	tjTradeOrderDetailIdKey := fmt.Sprintf("%s%v", cacheTjTradeOrderDetailIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderDetailRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.OrderId, data.UserId, data.CourseId, data.Price, data.Name, data.CoverUrl, data.ValidDuration, data.CourseExpireTime, data.DiscountAmount, data.RealPayAmount, data.Status, data.RefundStatus, data.PayChannel, data.Creater, data.Updater, data.Id)
	}, tjTradeOrderDetailIdKey)
	return err
}

func (m *defaultOrderDetailModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTjTradeOrderDetailIdPrefix, primary)
}

func (m *defaultOrderDetailModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderDetailRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderDetailModel) tableName() string {
	return m.table
}
