// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderFieldNames          = builder.RawFieldNames(&Order{})
	orderRows                = strings.Join(orderFieldNames, ",")
	orderRowsExpectAutoSet   = strings.Join(stringx.Remove(orderFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderRowsWithPlaceHolder = strings.Join(stringx.Remove(orderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTjTradeOrderIdPrefix = "cache:tjTrade:order:id:"
)

type (
	orderModel interface {
		Insert(ctx context.Context, data *Order) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Order, error)
		Update(ctx context.Context, data *Order) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOrderModel struct {
		sqlc.CachedConn
		table string
	}

	Order struct {
		Id             int64          `db:"id"`              // 订单id
		UserId         int64          `db:"user_id"`         // 用户id
		PayOrderNo     sql.NullInt64  `db:"pay_order_no"`    // 交易流水支付单号
		Status         int64          `db:"status"`          // 订单状态，1：待支付，2：已支付，3：已关闭，4：已完成，5：已报名，6：已申请退款
		Message        string         `db:"message"`         // 状态备注
		TotalAmount    int64          `db:"total_amount"`    // 订单总金额，单位分
		RealAmount     int64          `db:"real_amount"`     // 实付金额，单位分
		DiscountAmount int64          `db:"discount_amount"` // 优惠金额，单位分
		PayChannel     string         `db:"pay_channel"`     // 支付渠道
		CouponIds      sql.NullString `db:"coupon_ids"`      // 优惠券id
		CreateTime     time.Time      `db:"create_time"`     // 创建订单时间
		PayTime        sql.NullTime   `db:"pay_time"`        // 支付时间
		CloseTime      sql.NullTime   `db:"close_time"`      // 订单关闭时间
		FinishTime     sql.NullTime   `db:"finish_time"`     // 订单完成时间，支付后30天
		RefundTime     sql.NullTime   `db:"refund_time"`     // 申请退款时间
		UpdateTime     time.Time      `db:"update_time"`     // 更新时间
		Creater        int64          `db:"creater"`         // 创建人
		Updater        int64          `db:"updater"`         // 更新人
		Deleted        int64          `db:"deleted"`         // 逻辑删除
	}
)

func newOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOrderModel {
	return &defaultOrderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`order`",
	}
}

func (m *defaultOrderModel) Delete(ctx context.Context, id int64) error {
	tjTradeOrderIdKey := fmt.Sprintf("%s%v", cacheTjTradeOrderIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tjTradeOrderIdKey)
	return err
}

func (m *defaultOrderModel) FindOne(ctx context.Context, id int64) (*Order, error) {
	tjTradeOrderIdKey := fmt.Sprintf("%s%v", cacheTjTradeOrderIdPrefix, id)
	var resp Order
	err := m.QueryRowCtx(ctx, &resp, tjTradeOrderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) Insert(ctx context.Context, data *Order) (sql.Result, error) {
	tjTradeOrderIdKey := fmt.Sprintf("%s%v", cacheTjTradeOrderIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.PayOrderNo, data.Status, data.Message, data.TotalAmount, data.RealAmount, data.DiscountAmount, data.PayChannel, data.CouponIds, data.PayTime, data.CloseTime, data.FinishTime, data.RefundTime, data.Creater, data.Updater, data.Deleted)
	}, tjTradeOrderIdKey)
	return ret, err
}

func (m *defaultOrderModel) Update(ctx context.Context, data *Order) error {
	tjTradeOrderIdKey := fmt.Sprintf("%s%v", cacheTjTradeOrderIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.PayOrderNo, data.Status, data.Message, data.TotalAmount, data.RealAmount, data.DiscountAmount, data.PayChannel, data.CouponIds, data.PayTime, data.CloseTime, data.FinishTime, data.RefundTime, data.Creater, data.Updater, data.Deleted, data.Id)
	}, tjTradeOrderIdKey)
	return err
}

func (m *defaultOrderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTjTradeOrderIdPrefix, primary)
}

func (m *defaultOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderModel) tableName() string {
	return m.table
}
