// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	learningLessonFieldNames          = builder.RawFieldNames(&LearningLesson{})
	learningLessonRows                = strings.Join(learningLessonFieldNames, ",")
	learningLessonRowsExpectAutoSet   = strings.Join(stringx.Remove(learningLessonFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	learningLessonRowsWithPlaceHolder = strings.Join(stringx.Remove(learningLessonFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTjLearningLearningLessonIdPrefix             = "cache:tjLearning:learningLesson:id:"
	cacheTjLearningLearningLessonUserIdCourseIdPrefix = "cache:tjLearning:learningLesson:userId:courseId:"
)

type (
	learningLessonModel interface {
		Insert(ctx context.Context, data *LearningLesson) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LearningLesson, error)
		FindOneByUserIdCourseId(ctx context.Context, userId int64, courseId int64) (*LearningLesson, error)
		Update(ctx context.Context, data *LearningLesson) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLearningLessonModel struct {
		sqlc.CachedConn
		table string
	}

	LearningLesson struct {
		Id              int64         `db:"id"`                // 雪花主键
		UserId          int64         `db:"user_id"`           // 学员ID
		CourseId        int64         `db:"course_id"`         // 课程ID
		Status          int64         `db:"status"`            // 0未开始，1学习中，2完成，3失效
		WeekFreq        sql.NullInt64 `db:"week_freq"`         // 每周学习章节数
		PlanStatus      int64         `db:"plan_status"`       // 0无计划，1计划中
		LearnedSections int64         `db:"learned_sections"`  // 已学习章节数
		LatestSectionId sql.NullInt64 `db:"latest_section_id"` // 最近学习小节
		LatestLearnTime sql.NullTime  `db:"latest_learn_time"` // 最近学习时间
		CreateTime      time.Time     `db:"create_time"`
		ExpireTime      sql.NullTime  `db:"expire_time"` // 课程失效时间
		UpdateTime      time.Time     `db:"update_time"`
	}
)

func newLearningLessonModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLearningLessonModel {
	return &defaultLearningLessonModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`learning_lesson`",
	}
}

func (m *defaultLearningLessonModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tjLearningLearningLessonIdKey := fmt.Sprintf("%s%v", cacheTjLearningLearningLessonIdPrefix, id)
	tjLearningLearningLessonUserIdCourseIdKey := fmt.Sprintf("%s%v:%v", cacheTjLearningLearningLessonUserIdCourseIdPrefix, data.UserId, data.CourseId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tjLearningLearningLessonIdKey, tjLearningLearningLessonUserIdCourseIdKey)
	return err
}

func (m *defaultLearningLessonModel) FindOne(ctx context.Context, id int64) (*LearningLesson, error) {
	tjLearningLearningLessonIdKey := fmt.Sprintf("%s%v", cacheTjLearningLearningLessonIdPrefix, id)
	var resp LearningLesson
	err := m.QueryRowCtx(ctx, &resp, tjLearningLearningLessonIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", learningLessonRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLearningLessonModel) FindOneByUserIdCourseId(ctx context.Context, userId int64, courseId int64) (*LearningLesson, error) {
	tjLearningLearningLessonUserIdCourseIdKey := fmt.Sprintf("%s%v:%v", cacheTjLearningLearningLessonUserIdCourseIdPrefix, userId, courseId)
	var resp LearningLesson
	err := m.QueryRowIndexCtx(ctx, &resp, tjLearningLearningLessonUserIdCourseIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `course_id` = ? limit 1", learningLessonRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, courseId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLearningLessonModel) Insert(ctx context.Context, data *LearningLesson) (sql.Result, error) {
	tjLearningLearningLessonIdKey := fmt.Sprintf("%s%v", cacheTjLearningLearningLessonIdPrefix, data.Id)
	tjLearningLearningLessonUserIdCourseIdKey := fmt.Sprintf("%s%v:%v", cacheTjLearningLearningLessonUserIdCourseIdPrefix, data.UserId, data.CourseId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, learningLessonRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.CourseId, data.Status, data.WeekFreq, data.PlanStatus, data.LearnedSections, data.LatestSectionId, data.LatestLearnTime, data.ExpireTime)
	}, tjLearningLearningLessonIdKey, tjLearningLearningLessonUserIdCourseIdKey)
	return ret, err
}

func (m *defaultLearningLessonModel) Update(ctx context.Context, newData *LearningLesson) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	tjLearningLearningLessonIdKey := fmt.Sprintf("%s%v", cacheTjLearningLearningLessonIdPrefix, data.Id)
	tjLearningLearningLessonUserIdCourseIdKey := fmt.Sprintf("%s%v:%v", cacheTjLearningLearningLessonUserIdCourseIdPrefix, data.UserId, data.CourseId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, learningLessonRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.CourseId, newData.Status, newData.WeekFreq, newData.PlanStatus, newData.LearnedSections, newData.LatestSectionId, newData.LatestLearnTime, newData.ExpireTime, newData.Id)
	}, tjLearningLearningLessonIdKey, tjLearningLearningLessonUserIdCourseIdKey)
	return err
}

func (m *defaultLearningLessonModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTjLearningLearningLessonIdPrefix, primary)
}

func (m *defaultLearningLessonModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", learningLessonRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLearningLessonModel) tableName() string {
	return m.table
}
