// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: learning.proto

package learning

import (
	"context"

	"tjxt/apps/learning/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty                       = pb.Empty
	GrantCoursesRequest         = pb.GrantCoursesRequest
	LearningLessonVO            = pb.LearningLessonVO
	LearningRecordCommitRequest = pb.LearningRecordCommitRequest
	LearningRecordDTO           = pb.LearningRecordDTO
	LearningRecordsReply        = pb.LearningRecordsReply
	LessonCountReply            = pb.LessonCountReply
	LessonCountRequest          = pb.LessonCountRequest
	LessonPageReply             = pb.LessonPageReply
	LessonPageRequest           = pb.LessonPageRequest
	LessonRequest               = pb.LessonRequest
	LessonValidReply            = pb.LessonValidReply
	PlanPageReply               = pb.PlanPageReply
	PlanSaveRequest             = pb.PlanSaveRequest

	Learning interface {
		// 当前正在学习的课程
		LearningNow(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LearningLessonVO, error)
		// 我的课表分页
		LessonPage(ctx context.Context, in *LessonPageRequest, opts ...grpc.CallOption) (*LessonPageReply, error)
		// 我的学习计划分页
		PlanPage(ctx context.Context, in *LessonPageRequest, opts ...grpc.CallOption) (*PlanPageReply, error)
		// 指定课程的学习信息
		LessonGet(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LearningLessonVO, error)
		// 学员是否已报名（返回 lesson_id；未报名返回 0/NotFound 由调用方判）
		LessonValid(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LessonValidReply, error)
		// 课程的学习人数
		LessonCount(ctx context.Context, in *LessonCountRequest, opts ...grpc.CallOption) (*LessonCountReply, error)
		// 提交学习记录（更新 lesson 的 latest_section/learn_time/learned_sections）
		LearningRecordCommit(ctx context.Context, in *LearningRecordCommitRequest, opts ...grpc.CallOption) (*Empty, error)
		// 查询某课程的学习记录
		LearningRecordsByCourse(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LearningRecordsReply, error)
		// 创建/更新学习计划
		PlanSave(ctx context.Context, in *PlanSaveRequest, opts ...grpc.CallOption) (*Empty, error)
		// ---- 内部：来自 trade 的 mq 事件 / 内部 RPC 调用 ----
		GrantCourses(ctx context.Context, in *GrantCoursesRequest, opts ...grpc.CallOption) (*Empty, error)
		// 撤销课程
		RevokeCourses(ctx context.Context, in *GrantCoursesRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultLearning struct {
		cli zrpc.Client
	}
)

func NewLearning(cli zrpc.Client) Learning {
	return &defaultLearning{
		cli: cli,
	}
}

// 当前正在学习的课程
func (m *defaultLearning) LearningNow(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LearningLessonVO, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.LearningNow(ctx, in, opts...)
}

// 我的课表分页
func (m *defaultLearning) LessonPage(ctx context.Context, in *LessonPageRequest, opts ...grpc.CallOption) (*LessonPageReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.LessonPage(ctx, in, opts...)
}

// 我的学习计划分页
func (m *defaultLearning) PlanPage(ctx context.Context, in *LessonPageRequest, opts ...grpc.CallOption) (*PlanPageReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.PlanPage(ctx, in, opts...)
}

// 指定课程的学习信息
func (m *defaultLearning) LessonGet(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LearningLessonVO, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.LessonGet(ctx, in, opts...)
}

// 学员是否已报名（返回 lesson_id；未报名返回 0/NotFound 由调用方判）
func (m *defaultLearning) LessonValid(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LessonValidReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.LessonValid(ctx, in, opts...)
}

// 课程的学习人数
func (m *defaultLearning) LessonCount(ctx context.Context, in *LessonCountRequest, opts ...grpc.CallOption) (*LessonCountReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.LessonCount(ctx, in, opts...)
}

// 提交学习记录（更新 lesson 的 latest_section/learn_time/learned_sections）
func (m *defaultLearning) LearningRecordCommit(ctx context.Context, in *LearningRecordCommitRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.LearningRecordCommit(ctx, in, opts...)
}

// 查询某课程的学习记录
func (m *defaultLearning) LearningRecordsByCourse(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LearningRecordsReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.LearningRecordsByCourse(ctx, in, opts...)
}

// 创建/更新学习计划
func (m *defaultLearning) PlanSave(ctx context.Context, in *PlanSaveRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.PlanSave(ctx, in, opts...)
}

// ---- 内部：来自 trade 的 mq 事件 / 内部 RPC 调用 ----
func (m *defaultLearning) GrantCourses(ctx context.Context, in *GrantCoursesRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.GrantCourses(ctx, in, opts...)
}

// 撤销课程
func (m *defaultLearning) RevokeCourses(ctx context.Context, in *GrantCoursesRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.RevokeCourses(ctx, in, opts...)
}
