// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginReq struct {
	Username  string `json:"username,optional"`  // 员工登录用用户名
	CellPhone string `json:"cellPhone,optional"` // 学员/老师登录用手机号
	Password  string `json:"password"`
	Type      int32  `json:"type"` // 1-员工, 2-学员, 3-老师
}

type LoginVO struct {
	UserId       int64  `json:"userId"`
	Username     string `json:"username"`
	CellPhone    string `json:"cellPhone"`
	Type         int32  `json:"type"`
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpireTime   int64  `json:"expireTime"`
}

type OkVO struct {
	Success bool `json:"success"`
}

type PageRequest struct {
	PageNo   int64  `form:"pageNo,optional"`
	PageSize int64  `form:"pageSize,optional"`
	IsAsc    bool   `form:"isAsc,optional"`
	SortBy   string `form:"sortBy,optional"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RegisterReq struct {
	CellPhone string `json:"cellPhone"` // 学员手机号注册，密码由服务自动生成
}

type RegisterVO struct {
	UserId    int64  `json:"userId"`
	CellPhone string `json:"cellPhone"`
}

type UpdateUserReq struct {
	Name   string `json:"name,optional"`
	Gender int32  `json:"gender,optional"`
	Icon   string `json:"icon,optional"`
	Email  string `json:"email,optional"`
	Photo  string `json:"photo,optional"`
	Intro  string `json:"intro,optional"`
	Job    string `json:"job,optional"`
}

type UserPageVO struct {
	Total int64    `json:"total"`
	Pages int64    `json:"pages"`
	List  []UserVO `json:"list"`
}

type UserVO struct {
	Id         int64  `json:"id"`
	Username   string `json:"username"`
	CellPhone  string `json:"cellPhone"`
	Type       int32  `json:"type"`
	Status     int32  `json:"status"`
	Name       string `json:"name"`
	Gender     int32  `json:"gender"`
	Icon       string `json:"icon"`
	Email      string `json:"email"`
	Photo      string `json:"photo"`
	RoleId     int64  `json:"roleId"`
	DepId      int64  `json:"depId"`
	Job        string `json:"job"`
	Intro      string `json:"intro"`
	CreateTime string `json:"createTime"`
}
