// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	noticeTaskFieldNames          = builder.RawFieldNames(&NoticeTask{})
	noticeTaskRows                = strings.Join(noticeTaskFieldNames, ",")
	noticeTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(noticeTaskFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	noticeTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(noticeTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheNoticeTaskIdPrefix = "cache:noticeTask:id:"
)

type (
	noticeTaskModel interface {
		Insert(ctx context.Context, data *NoticeTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*NoticeTask, error)
		Update(ctx context.Context, data *NoticeTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultNoticeTaskModel struct {
		sqlc.CachedConn
		table string
	}

	NoticeTask struct {
		Id         int64         `db:"id"`          // 公告任务id
		TemplateId int64         `db:"template_id"` // 任务对应的通知模板id
		Name       string        `db:"name"`        // 任务名称
		Partial    byte          `db:"partial"`     // 是否是部分人的通告
		PushTime   sql.NullTime  `db:"push_time"`   // 任务预期执行时间
		Interval   sql.NullInt64 `db:"interval"`    // 任务延迟执行时间间隔，单位是分钟
		ExpireTime sql.NullTime  `db:"expire_time"` // 任务失效时间
		MaxTimes   int64         `db:"max_times"`   // 任务重复执行次数上限
		Finished   byte          `db:"finished"`    // 任务是否完成
		Creater    int64         `db:"creater"`     // 创建人
		Updater    int64         `db:"updater"`     // 更新人
		CreateTime time.Time     `db:"create_time"` // 创建时间
		UpdateTime time.Time     `db:"update_time"` // 更新时间
	}
)

func newNoticeTaskModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultNoticeTaskModel {
	return &defaultNoticeTaskModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`notice_task`",
	}
}

func (m *defaultNoticeTaskModel) Delete(ctx context.Context, id int64) error {
	noticeTaskIdKey := fmt.Sprintf("%s%v", cacheNoticeTaskIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, noticeTaskIdKey)
	return err
}

func (m *defaultNoticeTaskModel) FindOne(ctx context.Context, id int64) (*NoticeTask, error) {
	noticeTaskIdKey := fmt.Sprintf("%s%v", cacheNoticeTaskIdPrefix, id)
	var resp NoticeTask
	err := m.QueryRowCtx(ctx, &resp, noticeTaskIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", noticeTaskRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNoticeTaskModel) Insert(ctx context.Context, data *NoticeTask) (sql.Result, error) {
	noticeTaskIdKey := fmt.Sprintf("%s%v", cacheNoticeTaskIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, noticeTaskRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.TemplateId, data.Name, data.Partial, data.PushTime, data.Interval, data.ExpireTime, data.MaxTimes, data.Finished, data.Creater, data.Updater)
	}, noticeTaskIdKey)
	return ret, err
}

func (m *defaultNoticeTaskModel) Update(ctx context.Context, data *NoticeTask) error {
	noticeTaskIdKey := fmt.Sprintf("%s%v", cacheNoticeTaskIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, noticeTaskRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TemplateId, data.Name, data.Partial, data.PushTime, data.Interval, data.ExpireTime, data.MaxTimes, data.Finished, data.Creater, data.Updater, data.Id)
	}, noticeTaskIdKey)
	return err
}

func (m *defaultNoticeTaskModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheNoticeTaskIdPrefix, primary)
}

func (m *defaultNoticeTaskModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", noticeTaskRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultNoticeTaskModel) tableName() string {
	return m.table
}
