// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===================== 通用 =====================
type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type IdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdResponse) Reset() {
	*x = IdResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdResponse) ProtoMessage() {}

func (x *IdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdResponse.ProtoReflect.Descriptor instead.
func (*IdResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *IdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *BoolResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type UserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdsRequest) Reset() {
	*x = UserIdsRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdsRequest) ProtoMessage() {}

func (x *UserIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdsRequest.ProtoReflect.Descriptor instead.
func (*UserIdsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserIdsRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// ===================== 身份核验 =====================
type LoginVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellPhone     string                 `protobuf:"bytes,1,opt,name=cell_phone,json=cellPhone,proto3" json:"cell_phone,omitempty"` // 学员/老师用手机号
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                    // 员工用用户名
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"` // 1-员工 2-学员 3-老师
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginVerifyRequest) Reset() {
	*x = LoginVerifyRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginVerifyRequest) ProtoMessage() {}

func (x *LoginVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginVerifyRequest.ProtoReflect.Descriptor instead.
func (*LoginVerifyRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginVerifyRequest) GetCellPhone() string {
	if x != nil {
		return x.CellPhone
	}
	return ""
}

func (x *LoginVerifyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginVerifyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginVerifyRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type LoginVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CellPhone     string                 `protobuf:"bytes,3,opt,name=cell_phone,json=cellPhone,proto3" json:"cell_phone,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginVerifyResponse) Reset() {
	*x = LoginVerifyResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginVerifyResponse) ProtoMessage() {}

func (x *LoginVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginVerifyResponse.ProtoReflect.Descriptor instead.
func (*LoginVerifyResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *LoginVerifyResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginVerifyResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginVerifyResponse) GetCellPhone() string {
	if x != nil {
		return x.CellPhone
	}
	return ""
}

func (x *LoginVerifyResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LoginVerifyResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LoginVerifyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ===================== 学员表单 =====================
// 对应文档 StudentFormDTO：注册与改密复用同一结构。
type StudentFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellPhone     string                 `protobuf:"bytes,1,opt,name=cell_phone,json=cellPhone,proto3" json:"cell_phone,omitempty"` // 手机号
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                            // 短信验证码
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`                    // 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentFormRequest) Reset() {
	*x = StudentFormRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentFormRequest) ProtoMessage() {}

func (x *StudentFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentFormRequest.ProtoReflect.Descriptor instead.
func (*StudentFormRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *StudentFormRequest) GetCellPhone() string {
	if x != nil {
		return x.CellPhone
	}
	return ""
}

func (x *StudentFormRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StudentFormRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// ===================== 用户信息 =====================
// 对应文档 UserDTO。
type UserDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CellPhone     string                 `protobuf:"bytes,3,opt,name=cell_phone,json=cellPhone,proto3" json:"cell_phone,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"` // 1-其他员工, 2-普通学员, 3-老师
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"` // 0-男性, 1-女性
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Qq            string                 `protobuf:"bytes,9,opt,name=qq,proto3" json:"qq,omitempty"`
	Job           string                 `protobuf:"bytes,10,opt,name=job,proto3" json:"job,omitempty"`
	Province      string                 `protobuf:"bytes,11,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,13,opt,name=district,proto3" json:"district,omitempty"`
	Intro         string                 `protobuf:"bytes,14,opt,name=intro,proto3" json:"intro,omitempty"`
	Photo         string                 `protobuf:"bytes,15,opt,name=photo,proto3" json:"photo,omitempty"`
	RoleId        int64                  `protobuf:"varint,16,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 老师和学生不用填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDTO) Reset() {
	*x = UserDTO{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDTO) ProtoMessage() {}

func (x *UserDTO) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDTO.ProtoReflect.Descriptor instead.
func (*UserDTO) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDTO) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDTO) GetCellPhone() string {
	if x != nil {
		return x.CellPhone
	}
	return ""
}

func (x *UserDTO) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UserDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDTO) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserDTO) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UserDTO) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDTO) GetQq() string {
	if x != nil {
		return x.Qq
	}
	return ""
}

func (x *UserDTO) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *UserDTO) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserDTO) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserDTO) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UserDTO) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *UserDTO) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *UserDTO) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserDTO             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserListResponse) GetList() []*UserDTO {
	if x != nil {
		return x.List
	}
	return nil
}

// 对应文档 UserDetailVO：当前登录用户详情。
type UserDetailVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CellPhone     string                 `protobuf:"bytes,3,opt,name=cell_phone,json=cellPhone,proto3" json:"cell_phone,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Icon          string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Qq            string                 `protobuf:"bytes,8,opt,name=qq,proto3" json:"qq,omitempty"`
	Province      string                 `protobuf:"bytes,9,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,11,opt,name=district,proto3" json:"district,omitempty"`
	Intro         string                 `protobuf:"bytes,12,opt,name=intro,proto3" json:"intro,omitempty"`
	RoleName      string                 `protobuf:"bytes,13,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`       // 角色名称，归属 auth 服务的 role 表
	CreateTime    string                 `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 注册时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailVO) Reset() {
	*x = UserDetailVO{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailVO) ProtoMessage() {}

func (x *UserDetailVO) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailVO.ProtoReflect.Descriptor instead.
func (*UserDetailVO) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserDetailVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDetailVO) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDetailVO) GetCellPhone() string {
	if x != nil {
		return x.CellPhone
	}
	return ""
}

func (x *UserDetailVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDetailVO) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserDetailVO) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UserDetailVO) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDetailVO) GetQq() string {
	if x != nil {
		return x.Qq
	}
	return ""
}

func (x *UserDetailVO) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserDetailVO) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserDetailVO) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UserDetailVO) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *UserDetailVO) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UserDetailVO) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// 对应文档 UserFormDTO：更新当前登录用户，可同时改密码。
type UserFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CellPhone     string                 `protobuf:"bytes,3,opt,name=cell_phone,json=cellPhone,proto3" json:"cell_phone,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Qq            string                 `protobuf:"bytes,9,opt,name=qq,proto3" json:"qq,omitempty"`
	Job           string                 `protobuf:"bytes,10,opt,name=job,proto3" json:"job,omitempty"`
	Province      string                 `protobuf:"bytes,11,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,13,opt,name=district,proto3" json:"district,omitempty"`
	Intro         string                 `protobuf:"bytes,14,opt,name=intro,proto3" json:"intro,omitempty"`
	Photo         string                 `protobuf:"bytes,15,opt,name=photo,proto3" json:"photo,omitempty"`
	RoleId        int64                  `protobuf:"varint,16,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,17,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"` // 原始密码
	Password      string                 `protobuf:"bytes,18,opt,name=password,proto3" json:"password,omitempty"`                          // 新密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFormRequest) Reset() {
	*x = UserFormRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFormRequest) ProtoMessage() {}

func (x *UserFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFormRequest.ProtoReflect.Descriptor instead.
func (*UserFormRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserFormRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserFormRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserFormRequest) GetCellPhone() string {
	if x != nil {
		return x.CellPhone
	}
	return ""
}

func (x *UserFormRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UserFormRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserFormRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserFormRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UserFormRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserFormRequest) GetQq() string {
	if x != nil {
		return x.Qq
	}
	return ""
}

func (x *UserFormRequest) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *UserFormRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserFormRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserFormRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UserFormRequest) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *UserFormRequest) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *UserFormRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserFormRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UserFormRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckCellPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellPhone     string                 `protobuf:"bytes,1,opt,name=cell_phone,json=cellPhone,proto3" json:"cell_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCellPhoneRequest) Reset() {
	*x = CheckCellPhoneRequest{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCellPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCellPhoneRequest) ProtoMessage() {}

func (x *CheckCellPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCellPhoneRequest.ProtoReflect.Descriptor instead.
func (*CheckCellPhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *CheckCellPhoneRequest) GetCellPhone() string {
	if x != nil {
		return x.CellPhone
	}
	return ""
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0-禁用 1-正常
	Operator      int64                  `protobuf:"varint,3,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateStatusRequest) GetOperator() int64 {
	if x != nil {
		return x.Operator
	}
	return 0
}

// ===================== 分页查询 =====================
type UserPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int64                  `protobuf:"varint,1,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	IsAsc         bool                   `protobuf:"varint,4,opt,name=is_asc,json=isAsc,proto3" json:"is_asc,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`      // 姓名模糊
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`    // 手机号模糊
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"` // 账户状态，-1 表示不过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPageRequest) Reset() {
	*x = UserPageRequest{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPageRequest) ProtoMessage() {}

func (x *UserPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPageRequest.ProtoReflect.Descriptor instead.
func (*UserPageRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserPageRequest) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *UserPageRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserPageRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *UserPageRequest) GetIsAsc() bool {
	if x != nil {
		return x.IsAsc
	}
	return false
}

func (x *UserPageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserPageRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserPageRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 对应文档 StudentPageVo。
type StudentPageVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CellPhone     string                 `protobuf:"bytes,3,opt,name=cell_phone,json=cellPhone,proto3" json:"cell_phone,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CourseAmount  int64                  `protobuf:"varint,7,opt,name=course_amount,json=courseAmount,proto3" json:"course_amount,omitempty"` // 购买/报名课程数量
	CreateTime    string                 `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentPageVO) Reset() {
	*x = StudentPageVO{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentPageVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentPageVO) ProtoMessage() {}

func (x *StudentPageVO) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentPageVO.ProtoReflect.Descriptor instead.
func (*StudentPageVO) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *StudentPageVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentPageVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentPageVO) GetCellPhone() string {
	if x != nil {
		return x.CellPhone
	}
	return ""
}

func (x *StudentPageVO) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *StudentPageVO) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *StudentPageVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StudentPageVO) GetCourseAmount() int64 {
	if x != nil {
		return x.CourseAmount
	}
	return 0
}

func (x *StudentPageVO) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type StudentPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pages         int64                  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	List          []*StudentPageVO       `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentPageResponse) Reset() {
	*x = StudentPageResponse{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentPageResponse) ProtoMessage() {}

func (x *StudentPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentPageResponse.ProtoReflect.Descriptor instead.
func (*StudentPageResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *StudentPageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StudentPageResponse) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *StudentPageResponse) GetList() []*StudentPageVO {
	if x != nil {
		return x.List
	}
	return nil
}

// 对应文档 TeacherPageVO。
type TeacherPageVO struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CellPhone          string                 `protobuf:"bytes,3,opt,name=cell_phone,json=cellPhone,proto3" json:"cell_phone,omitempty"`
	Icon               string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Photo              string                 `protobuf:"bytes,5,opt,name=photo,proto3" json:"photo,omitempty"`
	Job                string                 `protobuf:"bytes,6,opt,name=job,proto3" json:"job,omitempty"`
	Intro              string                 `protobuf:"bytes,7,opt,name=intro,proto3" json:"intro,omitempty"`
	Status             int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CourseAmount       int64                  `protobuf:"varint,9,opt,name=course_amount,json=courseAmount,proto3" json:"course_amount,omitempty"`                      // 负责的课程数量，归属 course 服务
	ExamQuestionAmount int64                  `protobuf:"varint,10,opt,name=exam_question_amount,json=examQuestionAmount,proto3" json:"exam_question_amount,omitempty"` // 出题数量，归属 exam 服务
	CreateTime         string                 `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TeacherPageVO) Reset() {
	*x = TeacherPageVO{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherPageVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherPageVO) ProtoMessage() {}

func (x *TeacherPageVO) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherPageVO.ProtoReflect.Descriptor instead.
func (*TeacherPageVO) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *TeacherPageVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TeacherPageVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeacherPageVO) GetCellPhone() string {
	if x != nil {
		return x.CellPhone
	}
	return ""
}

func (x *TeacherPageVO) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *TeacherPageVO) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *TeacherPageVO) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *TeacherPageVO) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *TeacherPageVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TeacherPageVO) GetCourseAmount() int64 {
	if x != nil {
		return x.CourseAmount
	}
	return 0
}

func (x *TeacherPageVO) GetExamQuestionAmount() int64 {
	if x != nil {
		return x.ExamQuestionAmount
	}
	return 0
}

func (x *TeacherPageVO) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type TeacherPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pages         int64                  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	List          []*TeacherPageVO       `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeacherPageResponse) Reset() {
	*x = TeacherPageResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherPageResponse) ProtoMessage() {}

func (x *TeacherPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherPageResponse.ProtoReflect.Descriptor instead.
func (*TeacherPageResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *TeacherPageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TeacherPageResponse) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *TeacherPageResponse) GetList() []*TeacherPageVO {
	if x != nil {
		return x.List
	}
	return nil
}

// 对应文档 StaffVO。
type StaffVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CellPhone     string                 `protobuf:"bytes,3,opt,name=cell_phone,json=cellPhone,proto3" json:"cell_phone,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	RoleId        int64                  `protobuf:"varint,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,7,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"` // 角色名称，归属 auth 服务的 role 表
	CreateTime    string                 `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffVO) Reset() {
	*x = StaffVO{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffVO) ProtoMessage() {}

func (x *StaffVO) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffVO.ProtoReflect.Descriptor instead.
func (*StaffVO) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *StaffVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StaffVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffVO) GetCellPhone() string {
	if x != nil {
		return x.CellPhone
	}
	return ""
}

func (x *StaffVO) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *StaffVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StaffVO) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *StaffVO) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *StaffVO) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type StaffPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pages         int64                  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	List          []*StaffVO             `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffPageResponse) Reset() {
	*x = StaffPageResponse{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffPageResponse) ProtoMessage() {}

func (x *StaffPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffPageResponse.ProtoReflect.Descriptor instead.
func (*StaffPageResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *StaffPageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StaffPageResponse) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *StaffPageResponse) GetList() []*StaffVO {
	if x != nil {
		return x.List
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"\x0f\n" +
	"\rEmptyResponse\"\x1c\n" +
	"\n" +
	"IdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"&\n" +
	"\fBoolResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"(\n" +
	"\rUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"+\n" +
	"\x0eUserIdsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"\x7f\n" +
	"\x12LoginVerifyRequest\x12\x1d\n" +
	"\n" +
	"cell_phone\x18\x01 \x01(\tR\tcellPhone\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\"\xa9\x01\n" +
	"\x13LoginVerifyResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"cell_phone\x18\x03 \x01(\tR\tcellPhone\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"c\n" +
	"\x12StudentFormRequest\x12\x1d\n" +
	"\n" +
	"cell_phone\x18\x01 \x01(\tR\tcellPhone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xf1\x02\n" +
	"\aUserDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"cell_phone\x18\x03 \x01(\tR\tcellPhone\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x0e\n" +
	"\x02qq\x18\t \x01(\tR\x02qq\x12\x10\n" +
	"\x03job\x18\n" +
	" \x01(\tR\x03job\x12\x1a\n" +
	"\bprovince\x18\v \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\f \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\r \x01(\tR\bdistrict\x12\x14\n" +
	"\x05intro\x18\x0e \x01(\tR\x05intro\x12\x14\n" +
	"\x05photo\x18\x0f \x01(\tR\x05photo\x12\x17\n" +
	"\arole_id\x18\x10 \x01(\x03R\x06roleId\"5\n" +
	"\x10UserListResponse\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.user.UserDTOR\x04list\"\xdf\x02\n" +
	"\fUserDetailVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"cell_phone\x18\x03 \x01(\tR\tcellPhone\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x0e\n" +
	"\x02qq\x18\b \x01(\tR\x02qq\x12\x1a\n" +
	"\bprovince\x18\t \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\v \x01(\tR\bdistrict\x12\x14\n" +
	"\x05intro\x18\f \x01(\tR\x05intro\x12\x1b\n" +
	"\trole_name\x18\r \x01(\tR\broleName\x12\x1f\n" +
	"\vcreate_time\x18\x0e \x01(\tR\n" +
	"createTime\"\xb8\x03\n" +
	"\x0fUserFormRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"cell_phone\x18\x03 \x01(\tR\tcellPhone\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x0e\n" +
	"\x02qq\x18\t \x01(\tR\x02qq\x12\x10\n" +
	"\x03job\x18\n" +
	" \x01(\tR\x03job\x12\x1a\n" +
	"\bprovince\x18\v \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\f \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\r \x01(\tR\bdistrict\x12\x14\n" +
	"\x05intro\x18\x0e \x01(\tR\x05intro\x12\x14\n" +
	"\x05photo\x18\x0f \x01(\tR\x05photo\x12\x17\n" +
	"\arole_id\x18\x10 \x01(\x03R\x06roleId\x12!\n" +
	"\fold_password\x18\x11 \x01(\tR\voldPassword\x12\x1a\n" +
	"\bpassword\x18\x12 \x01(\tR\bpassword\"6\n" +
	"\x15CheckCellPhoneRequest\x12\x1d\n" +
	"\n" +
	"cell_phone\x18\x01 \x01(\tR\tcellPhone\"b\n" +
	"\x13UpdateStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\x03R\boperator\"\xb9\x01\n" +
	"\x0fUserPageRequest\x12\x17\n" +
	"\apage_no\x18\x01 \x01(\x03R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x15\n" +
	"\x06is_asc\x18\x04 \x01(\bR\x05isAsc\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"\xdc\x01\n" +
	"\rStudentPageVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"cell_phone\x18\x03 \x01(\tR\tcellPhone\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12#\n" +
	"\rcourse_amount\x18\a \x01(\x03R\fcourseAmount\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\tR\n" +
	"createTime\"j\n" +
	"\x13StudentPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x14\n" +
	"\x05pages\x18\x02 \x01(\x03R\x05pages\x12'\n" +
	"\x04list\x18\x03 \x03(\v2\x13.user.StudentPageVOR\x04list\"\xb4\x02\n" +
	"\rTeacherPageVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"cell_phone\x18\x03 \x01(\tR\tcellPhone\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x14\n" +
	"\x05photo\x18\x05 \x01(\tR\x05photo\x12\x10\n" +
	"\x03job\x18\x06 \x01(\tR\x03job\x12\x14\n" +
	"\x05intro\x18\a \x01(\tR\x05intro\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12#\n" +
	"\rcourse_amount\x18\t \x01(\x03R\fcourseAmount\x120\n" +
	"\x14exam_question_amount\x18\n" +
	" \x01(\x03R\x12examQuestionAmount\x12\x1f\n" +
	"\vcreate_time\x18\v \x01(\tR\n" +
	"createTime\"j\n" +
	"\x13TeacherPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x14\n" +
	"\x05pages\x18\x02 \x01(\x03R\x05pages\x12'\n" +
	"\x04list\x18\x03 \x03(\v2\x13.user.TeacherPageVOR\x04list\"\xcf\x01\n" +
	"\aStaffVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"cell_phone\x18\x03 \x01(\tR\tcellPhone\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\x03R\x06roleId\x12\x1b\n" +
	"\trole_name\x18\a \x01(\tR\broleName\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\tR\n" +
	"createTime\"b\n" +
	"\x11StaffPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x14\n" +
	"\x05pages\x18\x02 \x01(\x03R\x05pages\x12!\n" +
	"\x04list\x18\x03 \x03(\v2\r.user.StaffVOR\x04list2\xb3\a\n" +
	"\x04User\x12B\n" +
	"\vLoginVerify\x12\x18.user.LoginVerifyRequest\x1a\x19.user.LoginVerifyResponse\x12=\n" +
	"\x0fRegisterStudent\x12\x18.user.StudentFormRequest\x1a\x10.user.IdResponse\x12F\n" +
	"\x15UpdateStudentPassword\x12\x18.user.StudentFormRequest\x1a\x13.user.EmptyResponse\x12*\n" +
	"\aAddUser\x12\r.user.UserDTO\x1a\x10.user.IdResponse\x121\n" +
	"\vGetUserById\x12\x13.user.UserIdRequest\x1a\r.user.UserDTO\x12=\n" +
	"\rGetUsersByIds\x12\x14.user.UserIdsRequest\x1a\x16.user.UserListResponse\x128\n" +
	"\rGetUserDetail\x12\x13.user.UserIdRequest\x1a\x12.user.UserDetailVO\x124\n" +
	"\x0eUpdateUserById\x12\r.user.UserDTO\x1a\x13.user.EmptyResponse\x12?\n" +
	"\x11UpdateCurrentUser\x12\x15.user.UserFormRequest\x1a\x13.user.EmptyResponse\x12A\n" +
	"\x0eCheckCellPhone\x12\x1b.user.CheckCellPhoneRequest\x1a\x12.user.BoolResponse\x129\n" +
	"\rResetPassword\x12\x13.user.UserIdRequest\x1a\x13.user.EmptyResponse\x12B\n" +
	"\x10UpdateUserStatus\x12\x19.user.UpdateStatusRequest\x1a\x13.user.EmptyResponse\x12E\n" +
	"\x11PageQueryStudents\x12\x15.user.UserPageRequest\x1a\x19.user.StudentPageResponse\x12E\n" +
	"\x11PageQueryTeachers\x12\x15.user.UserPageRequest\x1a\x19.user.TeacherPageResponse\x12A\n" +
	"\x0fPageQueryStaffs\x12\x15.user.UserPageRequest\x1a\x17.user.StaffPageResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_user_proto_goTypes = []any{
	(*EmptyResponse)(nil),         // 0: user.EmptyResponse
	(*IdResponse)(nil),            // 1: user.IdResponse
	(*BoolResponse)(nil),          // 2: user.BoolResponse
	(*UserIdRequest)(nil),         // 3: user.UserIdRequest
	(*UserIdsRequest)(nil),        // 4: user.UserIdsRequest
	(*LoginVerifyRequest)(nil),    // 5: user.LoginVerifyRequest
	(*LoginVerifyResponse)(nil),   // 6: user.LoginVerifyResponse
	(*StudentFormRequest)(nil),    // 7: user.StudentFormRequest
	(*UserDTO)(nil),               // 8: user.UserDTO
	(*UserListResponse)(nil),      // 9: user.UserListResponse
	(*UserDetailVO)(nil),          // 10: user.UserDetailVO
	(*UserFormRequest)(nil),       // 11: user.UserFormRequest
	(*CheckCellPhoneRequest)(nil), // 12: user.CheckCellPhoneRequest
	(*UpdateStatusRequest)(nil),   // 13: user.UpdateStatusRequest
	(*UserPageRequest)(nil),       // 14: user.UserPageRequest
	(*StudentPageVO)(nil),         // 15: user.StudentPageVO
	(*StudentPageResponse)(nil),   // 16: user.StudentPageResponse
	(*TeacherPageVO)(nil),         // 17: user.TeacherPageVO
	(*TeacherPageResponse)(nil),   // 18: user.TeacherPageResponse
	(*StaffVO)(nil),               // 19: user.StaffVO
	(*StaffPageResponse)(nil),     // 20: user.StaffPageResponse
}
var file_user_proto_depIdxs = []int32{
	8,  // 0: user.UserListResponse.list:type_name -> user.UserDTO
	15, // 1: user.StudentPageResponse.list:type_name -> user.StudentPageVO
	17, // 2: user.TeacherPageResponse.list:type_name -> user.TeacherPageVO
	19, // 3: user.StaffPageResponse.list:type_name -> user.StaffVO
	5,  // 4: user.User.LoginVerify:input_type -> user.LoginVerifyRequest
	7,  // 5: user.User.RegisterStudent:input_type -> user.StudentFormRequest
	7,  // 6: user.User.UpdateStudentPassword:input_type -> user.StudentFormRequest
	8,  // 7: user.User.AddUser:input_type -> user.UserDTO
	3,  // 8: user.User.GetUserById:input_type -> user.UserIdRequest
	4,  // 9: user.User.GetUsersByIds:input_type -> user.UserIdsRequest
	3,  // 10: user.User.GetUserDetail:input_type -> user.UserIdRequest
	8,  // 11: user.User.UpdateUserById:input_type -> user.UserDTO
	11, // 12: user.User.UpdateCurrentUser:input_type -> user.UserFormRequest
	12, // 13: user.User.CheckCellPhone:input_type -> user.CheckCellPhoneRequest
	3,  // 14: user.User.ResetPassword:input_type -> user.UserIdRequest
	13, // 15: user.User.UpdateUserStatus:input_type -> user.UpdateStatusRequest
	14, // 16: user.User.PageQueryStudents:input_type -> user.UserPageRequest
	14, // 17: user.User.PageQueryTeachers:input_type -> user.UserPageRequest
	14, // 18: user.User.PageQueryStaffs:input_type -> user.UserPageRequest
	6,  // 19: user.User.LoginVerify:output_type -> user.LoginVerifyResponse
	1,  // 20: user.User.RegisterStudent:output_type -> user.IdResponse
	0,  // 21: user.User.UpdateStudentPassword:output_type -> user.EmptyResponse
	1,  // 22: user.User.AddUser:output_type -> user.IdResponse
	8,  // 23: user.User.GetUserById:output_type -> user.UserDTO
	9,  // 24: user.User.GetUsersByIds:output_type -> user.UserListResponse
	10, // 25: user.User.GetUserDetail:output_type -> user.UserDetailVO
	0,  // 26: user.User.UpdateUserById:output_type -> user.EmptyResponse
	0,  // 27: user.User.UpdateCurrentUser:output_type -> user.EmptyResponse
	2,  // 28: user.User.CheckCellPhone:output_type -> user.BoolResponse
	0,  // 29: user.User.ResetPassword:output_type -> user.EmptyResponse
	0,  // 30: user.User.UpdateUserStatus:output_type -> user.EmptyResponse
	16, // 31: user.User.PageQueryStudents:output_type -> user.StudentPageResponse
	18, // 32: user.User.PageQueryTeachers:output_type -> user.TeacherPageResponse
	20, // 33: user.User.PageQueryStaffs:output_type -> user.StaffPageResponse
	19, // [19:34] is the sub-list for method output_type
	4,  // [4:19] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
