// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: learning.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_learning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{0}
}

type LessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonRequest) Reset() {
	*x = LessonRequest{}
	mi := &file_learning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonRequest) ProtoMessage() {}

func (x *LessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonRequest.ProtoReflect.Descriptor instead.
func (*LessonRequest) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{1}
}

func (x *LessonRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type LessonCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonCountRequest) Reset() {
	*x = LessonCountRequest{}
	mi := &file_learning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonCountRequest) ProtoMessage() {}

func (x *LessonCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonCountRequest.ProtoReflect.Descriptor instead.
func (*LessonCountRequest) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{2}
}

func (x *LessonCountRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type LessonPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int64                  `protobuf:"varint,1,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	IsAsc         bool                   `protobuf:"varint,3,opt,name=is_asc,json=isAsc,proto3" json:"is_asc,omitempty"`
	SortBy        string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPageRequest) Reset() {
	*x = LessonPageRequest{}
	mi := &file_learning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPageRequest) ProtoMessage() {}

func (x *LessonPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPageRequest.ProtoReflect.Descriptor instead.
func (*LessonPageRequest) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{3}
}

func (x *LessonPageRequest) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *LessonPageRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *LessonPageRequest) GetIsAsc() bool {
	if x != nil {
		return x.IsAsc
	}
	return false
}

func (x *LessonPageRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type LearningLessonVO struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId           int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseName         string                 `protobuf:"bytes,3,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	CourseCoverUrl     string                 `protobuf:"bytes,4,opt,name=course_cover_url,json=courseCoverUrl,proto3" json:"course_cover_url,omitempty"`
	CourseAmount       int64                  `protobuf:"varint,5,opt,name=course_amount,json=courseAmount,proto3" json:"course_amount,omitempty"`
	Sections           int32                  `protobuf:"varint,6,opt,name=sections,proto3" json:"sections,omitempty"`
	LearnedSections    int32                  `protobuf:"varint,7,opt,name=learned_sections,json=learnedSections,proto3" json:"learned_sections,omitempty"`
	Status             string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                           // NOT_BEGIN / LEARNING / FINISHED / EXPIRED
	PlanStatus         string                 `protobuf:"bytes,9,opt,name=plan_status,json=planStatus,proto3" json:"plan_status,omitempty"` // NO_PLAN / PLAN_RUNNING
	WeekFreq           int32                  `protobuf:"varint,10,opt,name=week_freq,json=weekFreq,proto3" json:"week_freq,omitempty"`
	LatestSectionId    int64                  `protobuf:"varint,11,opt,name=latest_section_id,json=latestSectionId,proto3" json:"latest_section_id,omitempty"`
	LatestSectionName  string                 `protobuf:"bytes,12,opt,name=latest_section_name,json=latestSectionName,proto3" json:"latest_section_name,omitempty"`
	LatestSectionIndex int32                  `protobuf:"varint,13,opt,name=latest_section_index,json=latestSectionIndex,proto3" json:"latest_section_index,omitempty"`
	CreateTime         string                 `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ExpireTime         string                 `protobuf:"bytes,15,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	LatestLearnTime    string                 `protobuf:"bytes,16,opt,name=latest_learn_time,json=latestLearnTime,proto3" json:"latest_learn_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LearningLessonVO) Reset() {
	*x = LearningLessonVO{}
	mi := &file_learning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningLessonVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningLessonVO) ProtoMessage() {}

func (x *LearningLessonVO) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningLessonVO.ProtoReflect.Descriptor instead.
func (*LearningLessonVO) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{4}
}

func (x *LearningLessonVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LearningLessonVO) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *LearningLessonVO) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *LearningLessonVO) GetCourseCoverUrl() string {
	if x != nil {
		return x.CourseCoverUrl
	}
	return ""
}

func (x *LearningLessonVO) GetCourseAmount() int64 {
	if x != nil {
		return x.CourseAmount
	}
	return 0
}

func (x *LearningLessonVO) GetSections() int32 {
	if x != nil {
		return x.Sections
	}
	return 0
}

func (x *LearningLessonVO) GetLearnedSections() int32 {
	if x != nil {
		return x.LearnedSections
	}
	return 0
}

func (x *LearningLessonVO) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LearningLessonVO) GetPlanStatus() string {
	if x != nil {
		return x.PlanStatus
	}
	return ""
}

func (x *LearningLessonVO) GetWeekFreq() int32 {
	if x != nil {
		return x.WeekFreq
	}
	return 0
}

func (x *LearningLessonVO) GetLatestSectionId() int64 {
	if x != nil {
		return x.LatestSectionId
	}
	return 0
}

func (x *LearningLessonVO) GetLatestSectionName() string {
	if x != nil {
		return x.LatestSectionName
	}
	return ""
}

func (x *LearningLessonVO) GetLatestSectionIndex() int32 {
	if x != nil {
		return x.LatestSectionIndex
	}
	return 0
}

func (x *LearningLessonVO) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *LearningLessonVO) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *LearningLessonVO) GetLatestLearnTime() string {
	if x != nil {
		return x.LatestLearnTime
	}
	return ""
}

type LessonPageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pages         int64                  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	List          []*LearningLessonVO    `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonPageReply) Reset() {
	*x = LessonPageReply{}
	mi := &file_learning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonPageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonPageReply) ProtoMessage() {}

func (x *LessonPageReply) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonPageReply.ProtoReflect.Descriptor instead.
func (*LessonPageReply) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{5}
}

func (x *LessonPageReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LessonPageReply) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *LessonPageReply) GetList() []*LearningLessonVO {
	if x != nil {
		return x.List
	}
	return nil
}

type PlanPageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pages         int64                  `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	WeekFinished  int32                  `protobuf:"varint,3,opt,name=week_finished,json=weekFinished,proto3" json:"week_finished,omitempty"`
	WeekPoints    int32                  `protobuf:"varint,4,opt,name=week_points,json=weekPoints,proto3" json:"week_points,omitempty"`
	WeekTotalPlan int32                  `protobuf:"varint,5,opt,name=week_total_plan,json=weekTotalPlan,proto3" json:"week_total_plan,omitempty"`
	List          []*LearningLessonVO    `protobuf:"bytes,6,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanPageReply) Reset() {
	*x = PlanPageReply{}
	mi := &file_learning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanPageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanPageReply) ProtoMessage() {}

func (x *PlanPageReply) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanPageReply.ProtoReflect.Descriptor instead.
func (*PlanPageReply) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{6}
}

func (x *PlanPageReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PlanPageReply) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *PlanPageReply) GetWeekFinished() int32 {
	if x != nil {
		return x.WeekFinished
	}
	return 0
}

func (x *PlanPageReply) GetWeekPoints() int32 {
	if x != nil {
		return x.WeekPoints
	}
	return 0
}

func (x *PlanPageReply) GetWeekTotalPlan() int32 {
	if x != nil {
		return x.WeekTotalPlan
	}
	return 0
}

func (x *PlanPageReply) GetList() []*LearningLessonVO {
	if x != nil {
		return x.List
	}
	return nil
}

type LessonCountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonCountReply) Reset() {
	*x = LessonCountReply{}
	mi := &file_learning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonCountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonCountReply) ProtoMessage() {}

func (x *LessonCountReply) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonCountReply.ProtoReflect.Descriptor instead.
func (*LessonCountReply) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{7}
}

func (x *LessonCountReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LessonValidReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      int64                  `protobuf:"varint,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonValidReply) Reset() {
	*x = LessonValidReply{}
	mi := &file_learning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonValidReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonValidReply) ProtoMessage() {}

func (x *LessonValidReply) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonValidReply.ProtoReflect.Descriptor instead.
func (*LessonValidReply) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{8}
}

func (x *LessonValidReply) GetLessonId() int64 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

type LearningRecordCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      int64                  `protobuf:"varint,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	SectionId     int64                  `protobuf:"varint,2,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	SectionType   int32                  `protobuf:"varint,3,opt,name=section_type,json=sectionType,proto3" json:"section_type,omitempty"` // 0 / 1 / 2 由 api 解析：VIDEO / EXAM 字符串映射
	Moment        int64                  `protobuf:"varint,4,opt,name=moment,proto3" json:"moment,omitempty"`
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	CommitTime    string                 `protobuf:"bytes,6,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearningRecordCommitRequest) Reset() {
	*x = LearningRecordCommitRequest{}
	mi := &file_learning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningRecordCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningRecordCommitRequest) ProtoMessage() {}

func (x *LearningRecordCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningRecordCommitRequest.ProtoReflect.Descriptor instead.
func (*LearningRecordCommitRequest) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{9}
}

func (x *LearningRecordCommitRequest) GetLessonId() int64 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

func (x *LearningRecordCommitRequest) GetSectionId() int64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *LearningRecordCommitRequest) GetSectionType() int32 {
	if x != nil {
		return x.SectionType
	}
	return 0
}

func (x *LearningRecordCommitRequest) GetMoment() int64 {
	if x != nil {
		return x.Moment
	}
	return 0
}

func (x *LearningRecordCommitRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *LearningRecordCommitRequest) GetCommitTime() string {
	if x != nil {
		return x.CommitTime
	}
	return ""
}

type LearningRecordDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     int64                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Moment        int64                  `protobuf:"varint,2,opt,name=moment,proto3" json:"moment,omitempty"`
	Duration      int64                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Finished      bool                   `protobuf:"varint,4,opt,name=finished,proto3" json:"finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearningRecordDTO) Reset() {
	*x = LearningRecordDTO{}
	mi := &file_learning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningRecordDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningRecordDTO) ProtoMessage() {}

func (x *LearningRecordDTO) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningRecordDTO.ProtoReflect.Descriptor instead.
func (*LearningRecordDTO) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{10}
}

func (x *LearningRecordDTO) GetSectionId() int64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *LearningRecordDTO) GetMoment() int64 {
	if x != nil {
		return x.Moment
	}
	return 0
}

func (x *LearningRecordDTO) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *LearningRecordDTO) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

type LearningRecordsReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LatestSectionId int64                  `protobuf:"varint,2,opt,name=latest_section_id,json=latestSectionId,proto3" json:"latest_section_id,omitempty"`
	Records         []*LearningRecordDTO   `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LearningRecordsReply) Reset() {
	*x = LearningRecordsReply{}
	mi := &file_learning_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningRecordsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningRecordsReply) ProtoMessage() {}

func (x *LearningRecordsReply) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningRecordsReply.ProtoReflect.Descriptor instead.
func (*LearningRecordsReply) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{11}
}

func (x *LearningRecordsReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LearningRecordsReply) GetLatestSectionId() int64 {
	if x != nil {
		return x.LatestSectionId
	}
	return 0
}

func (x *LearningRecordsReply) GetRecords() []*LearningRecordDTO {
	if x != nil {
		return x.Records
	}
	return nil
}

type PlanSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Freq          int64                  `protobuf:"varint,2,opt,name=freq,proto3" json:"freq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanSaveRequest) Reset() {
	*x = PlanSaveRequest{}
	mi := &file_learning_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanSaveRequest) ProtoMessage() {}

func (x *PlanSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanSaveRequest.ProtoReflect.Descriptor instead.
func (*PlanSaveRequest) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{12}
}

func (x *PlanSaveRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *PlanSaveRequest) GetFreq() int64 {
	if x != nil {
		return x.Freq
	}
	return 0
}

// ============== 内部事件（来自 trade） ==============
type GrantCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseIds     []int64                `protobuf:"varint,2,rep,packed,name=course_ids,json=courseIds,proto3" json:"course_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantCoursesRequest) Reset() {
	*x = GrantCoursesRequest{}
	mi := &file_learning_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantCoursesRequest) ProtoMessage() {}

func (x *GrantCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learning_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantCoursesRequest.ProtoReflect.Descriptor instead.
func (*GrantCoursesRequest) Descriptor() ([]byte, []int) {
	return file_learning_proto_rawDescGZIP(), []int{13}
}

func (x *GrantCoursesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GrantCoursesRequest) GetCourseIds() []int64 {
	if x != nil {
		return x.CourseIds
	}
	return nil
}

var File_learning_proto protoreflect.FileDescriptor

const file_learning_proto_rawDesc = "" +
	"\n" +
	"\x0elearning.proto\x12\blearning\"\a\n" +
	"\x05Empty\",\n" +
	"\rLessonRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\"1\n" +
	"\x12LessonCountRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\"y\n" +
	"\x11LessonPageRequest\x12\x17\n" +
	"\apage_no\x18\x01 \x01(\x03R\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x15\n" +
	"\x06is_asc\x18\x03 \x01(\bR\x05isAsc\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\"\xc8\x04\n" +
	"\x10LearningLessonVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x1f\n" +
	"\vcourse_name\x18\x03 \x01(\tR\n" +
	"courseName\x12(\n" +
	"\x10course_cover_url\x18\x04 \x01(\tR\x0ecourseCoverUrl\x12#\n" +
	"\rcourse_amount\x18\x05 \x01(\x03R\fcourseAmount\x12\x1a\n" +
	"\bsections\x18\x06 \x01(\x05R\bsections\x12)\n" +
	"\x10learned_sections\x18\a \x01(\x05R\x0flearnedSections\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1f\n" +
	"\vplan_status\x18\t \x01(\tR\n" +
	"planStatus\x12\x1b\n" +
	"\tweek_freq\x18\n" +
	" \x01(\x05R\bweekFreq\x12*\n" +
	"\x11latest_section_id\x18\v \x01(\x03R\x0flatestSectionId\x12.\n" +
	"\x13latest_section_name\x18\f \x01(\tR\x11latestSectionName\x120\n" +
	"\x14latest_section_index\x18\r \x01(\x05R\x12latestSectionIndex\x12\x1f\n" +
	"\vcreate_time\x18\x0e \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vexpire_time\x18\x0f \x01(\tR\n" +
	"expireTime\x12*\n" +
	"\x11latest_learn_time\x18\x10 \x01(\tR\x0flatestLearnTime\"m\n" +
	"\x0fLessonPageReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x14\n" +
	"\x05pages\x18\x02 \x01(\x03R\x05pages\x12.\n" +
	"\x04list\x18\x03 \x03(\v2\x1a.learning.LearningLessonVOR\x04list\"\xd9\x01\n" +
	"\rPlanPageReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x14\n" +
	"\x05pages\x18\x02 \x01(\x03R\x05pages\x12#\n" +
	"\rweek_finished\x18\x03 \x01(\x05R\fweekFinished\x12\x1f\n" +
	"\vweek_points\x18\x04 \x01(\x05R\n" +
	"weekPoints\x12&\n" +
	"\x0fweek_total_plan\x18\x05 \x01(\x05R\rweekTotalPlan\x12.\n" +
	"\x04list\x18\x06 \x03(\v2\x1a.learning.LearningLessonVOR\x04list\"(\n" +
	"\x10LessonCountReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"/\n" +
	"\x10LessonValidReply\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\x03R\blessonId\"\xd1\x01\n" +
	"\x1bLearningRecordCommitRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\x03R\blessonId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x02 \x01(\x03R\tsectionId\x12!\n" +
	"\fsection_type\x18\x03 \x01(\x05R\vsectionType\x12\x16\n" +
	"\x06moment\x18\x04 \x01(\x03R\x06moment\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x12\x1f\n" +
	"\vcommit_time\x18\x06 \x01(\tR\n" +
	"commitTime\"\x82\x01\n" +
	"\x11LearningRecordDTO\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x03R\tsectionId\x12\x16\n" +
	"\x06moment\x18\x02 \x01(\x03R\x06moment\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x03R\bduration\x12\x1a\n" +
	"\bfinished\x18\x04 \x01(\bR\bfinished\"\x89\x01\n" +
	"\x14LearningRecordsReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x11latest_section_id\x18\x02 \x01(\x03R\x0flatestSectionId\x125\n" +
	"\arecords\x18\x03 \x03(\v2\x1b.learning.LearningRecordDTOR\arecords\"B\n" +
	"\x0fPlanSaveRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x12\n" +
	"\x04freq\x18\x02 \x01(\x03R\x04freq\"M\n" +
	"\x13GrantCoursesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"course_ids\x18\x02 \x03(\x03R\tcourseIds2\xfa\x05\n" +
	"\bLearning\x12:\n" +
	"\vLearningNow\x12\x0f.learning.Empty\x1a\x1a.learning.LearningLessonVO\x12D\n" +
	"\n" +
	"LessonPage\x12\x1b.learning.LessonPageRequest\x1a\x19.learning.LessonPageReply\x12@\n" +
	"\bPlanPage\x12\x1b.learning.LessonPageRequest\x1a\x17.learning.PlanPageReply\x12@\n" +
	"\tLessonGet\x12\x17.learning.LessonRequest\x1a\x1a.learning.LearningLessonVO\x12B\n" +
	"\vLessonValid\x12\x17.learning.LessonRequest\x1a\x1a.learning.LessonValidReply\x12G\n" +
	"\vLessonCount\x12\x1c.learning.LessonCountRequest\x1a\x1a.learning.LessonCountReply\x12N\n" +
	"\x14LearningRecordCommit\x12%.learning.LearningRecordCommitRequest\x1a\x0f.learning.Empty\x12R\n" +
	"\x17LearningRecordsByCourse\x12\x17.learning.LessonRequest\x1a\x1e.learning.LearningRecordsReply\x126\n" +
	"\bPlanSave\x12\x19.learning.PlanSaveRequest\x1a\x0f.learning.Empty\x12>\n" +
	"\fGrantCourses\x12\x1d.learning.GrantCoursesRequest\x1a\x0f.learning.Empty\x12?\n" +
	"\rRevokeCourses\x12\x1d.learning.GrantCoursesRequest\x1a\x0f.learning.EmptyB\x06Z\x04./pbb\x06proto3"

var (
	file_learning_proto_rawDescOnce sync.Once
	file_learning_proto_rawDescData []byte
)

func file_learning_proto_rawDescGZIP() []byte {
	file_learning_proto_rawDescOnce.Do(func() {
		file_learning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learning_proto_rawDesc), len(file_learning_proto_rawDesc)))
	})
	return file_learning_proto_rawDescData
}

var file_learning_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_learning_proto_goTypes = []any{
	(*Empty)(nil),                       // 0: learning.Empty
	(*LessonRequest)(nil),               // 1: learning.LessonRequest
	(*LessonCountRequest)(nil),          // 2: learning.LessonCountRequest
	(*LessonPageRequest)(nil),           // 3: learning.LessonPageRequest
	(*LearningLessonVO)(nil),            // 4: learning.LearningLessonVO
	(*LessonPageReply)(nil),             // 5: learning.LessonPageReply
	(*PlanPageReply)(nil),               // 6: learning.PlanPageReply
	(*LessonCountReply)(nil),            // 7: learning.LessonCountReply
	(*LessonValidReply)(nil),            // 8: learning.LessonValidReply
	(*LearningRecordCommitRequest)(nil), // 9: learning.LearningRecordCommitRequest
	(*LearningRecordDTO)(nil),           // 10: learning.LearningRecordDTO
	(*LearningRecordsReply)(nil),        // 11: learning.LearningRecordsReply
	(*PlanSaveRequest)(nil),             // 12: learning.PlanSaveRequest
	(*GrantCoursesRequest)(nil),         // 13: learning.GrantCoursesRequest
}
var file_learning_proto_depIdxs = []int32{
	4,  // 0: learning.LessonPageReply.list:type_name -> learning.LearningLessonVO
	4,  // 1: learning.PlanPageReply.list:type_name -> learning.LearningLessonVO
	10, // 2: learning.LearningRecordsReply.records:type_name -> learning.LearningRecordDTO
	0,  // 3: learning.Learning.LearningNow:input_type -> learning.Empty
	3,  // 4: learning.Learning.LessonPage:input_type -> learning.LessonPageRequest
	3,  // 5: learning.Learning.PlanPage:input_type -> learning.LessonPageRequest
	1,  // 6: learning.Learning.LessonGet:input_type -> learning.LessonRequest
	1,  // 7: learning.Learning.LessonValid:input_type -> learning.LessonRequest
	2,  // 8: learning.Learning.LessonCount:input_type -> learning.LessonCountRequest
	9,  // 9: learning.Learning.LearningRecordCommit:input_type -> learning.LearningRecordCommitRequest
	1,  // 10: learning.Learning.LearningRecordsByCourse:input_type -> learning.LessonRequest
	12, // 11: learning.Learning.PlanSave:input_type -> learning.PlanSaveRequest
	13, // 12: learning.Learning.GrantCourses:input_type -> learning.GrantCoursesRequest
	13, // 13: learning.Learning.RevokeCourses:input_type -> learning.GrantCoursesRequest
	4,  // 14: learning.Learning.LearningNow:output_type -> learning.LearningLessonVO
	5,  // 15: learning.Learning.LessonPage:output_type -> learning.LessonPageReply
	6,  // 16: learning.Learning.PlanPage:output_type -> learning.PlanPageReply
	4,  // 17: learning.Learning.LessonGet:output_type -> learning.LearningLessonVO
	8,  // 18: learning.Learning.LessonValid:output_type -> learning.LessonValidReply
	7,  // 19: learning.Learning.LessonCount:output_type -> learning.LessonCountReply
	0,  // 20: learning.Learning.LearningRecordCommit:output_type -> learning.Empty
	11, // 21: learning.Learning.LearningRecordsByCourse:output_type -> learning.LearningRecordsReply
	0,  // 22: learning.Learning.PlanSave:output_type -> learning.Empty
	0,  // 23: learning.Learning.GrantCourses:output_type -> learning.Empty
	0,  // 24: learning.Learning.RevokeCourses:output_type -> learning.Empty
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_learning_proto_init() }
func file_learning_proto_init() {
	if File_learning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learning_proto_rawDesc), len(file_learning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learning_proto_goTypes,
		DependencyIndexes: file_learning_proto_depIdxs,
		MessageInfos:      file_learning_proto_msgTypes,
	}.Build()
	File_learning_proto = out.File
	file_learning_proto_goTypes = nil
	file_learning_proto_depIdxs = nil
}
