// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"tjxt/apps/pay/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pay/channels",
				Handler: ListPayChannelsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pay/orders",
				Handler: ApplyPayOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pay/orders",
				Handler: QueryPayOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/pay/orders/:payOrderNo/close",
				Handler: ClosePayOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pay/orders/result",
				Handler: QueryPayResultHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pay/refunds",
				Handler: ApplyRefundHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/pay/refunds/result",
				Handler: QueryRefundResultHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/channels",
				Handler: AddPayChannelHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/channels",
				Handler: UpdatePayChannelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/channels/code/:code",
				Handler: GetPayChannelByCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/channels/page",
				Handler: PagePayChannelsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/channels/status",
				Handler: UpdatePayChannelStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/pay-admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/pay-failed",
				Handler: NotifyPayFailedHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pay-success",
				Handler: NotifyPaySuccessHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refund-failed",
				Handler: NotifyRefundFailedHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refund-success",
				Handler: NotifyRefundSuccessHandler(serverCtx),
			},
		},
		rest.WithPrefix("/pay-notify"),
	)
}
