// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseCatalogueFieldNames          = builder.RawFieldNames(&CourseCatalogue{})
	courseCatalogueRows                = strings.Join(courseCatalogueFieldNames, ",")
	courseCatalogueRowsExpectAutoSet   = strings.Join(stringx.Remove(courseCatalogueFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseCatalogueRowsWithPlaceHolder = strings.Join(stringx.Remove(courseCatalogueFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCourseCatalogueIdPrefix = "cache:courseCatalogue:id:"
)

type (
	courseCatalogueModel interface {
		Insert(ctx context.Context, data *CourseCatalogue) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CourseCatalogue, error)
		Update(ctx context.Context, data *CourseCatalogue) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseCatalogueModel struct {
		sqlc.CachedConn
		table string
	}

	CourseCatalogue struct {
		Id                int64         `db:"id"`                  // 课程目录id
		Name              string        `db:"name"`                // 目录名称
		Trailer           int64         `db:"trailer"`             // 是否支持试看
		CourseId          int64         `db:"course_id"`           // 课程id
		Type              int64         `db:"type"`                // 目录类型1：章，2：节，3：测试
		ParentCatalogueId int64         `db:"parent_catalogue_id"` // 所属章id，只有小节和测试有该值，章没有，章默认为0
		MediaId           int64         `db:"media_id"`            // 媒资id
		VideoId           sql.NullInt64 `db:"video_id"`            // 视频id
		VideoName         string        `db:"video_name"`          // 视频名称
		LivingStartTime   sql.NullTime  `db:"living_start_time"`   // 直播开始时间
		LivingEndTime     sql.NullTime  `db:"living_end_time"`     // 直播结束时间
		PlayBack          int64         `db:"play_back"`           // 是否支持回放
		MediaDuration     int64         `db:"media_duration"`      // 视频时长，以秒为单位
		CIndex            int64         `db:"c_index"`             // 用于章节排序
		DepId             int64         `db:"dep_id"`              // 部门id
		CreateTime        time.Time     `db:"create_time"`         // 创建时间
		UpdateTime        time.Time     `db:"update_time"`         // 更新时间
		Creater           int64         `db:"creater"`             // 创建人
		Updater           int64         `db:"updater"`             // 更新人
		Deleted           int64         `db:"deleted"`             // 逻辑删除
	}
)

func newCourseCatalogueModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseCatalogueModel {
	return &defaultCourseCatalogueModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course_catalogue`",
	}
}

func (m *defaultCourseCatalogueModel) Delete(ctx context.Context, id int64) error {
	courseCatalogueIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, courseCatalogueIdKey)
	return err
}

func (m *defaultCourseCatalogueModel) FindOne(ctx context.Context, id int64) (*CourseCatalogue, error) {
	courseCatalogueIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueIdPrefix, id)
	var resp CourseCatalogue
	err := m.QueryRowCtx(ctx, &resp, courseCatalogueIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseCatalogueRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseCatalogueModel) Insert(ctx context.Context, data *CourseCatalogue) (sql.Result, error) {
	courseCatalogueIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, courseCatalogueRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.Trailer, data.CourseId, data.Type, data.ParentCatalogueId, data.MediaId, data.VideoId, data.VideoName, data.LivingStartTime, data.LivingEndTime, data.PlayBack, data.MediaDuration, data.CIndex, data.DepId, data.Creater, data.Updater, data.Deleted)
	}, courseCatalogueIdKey)
	return ret, err
}

func (m *defaultCourseCatalogueModel) Update(ctx context.Context, data *CourseCatalogue) error {
	courseCatalogueIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseCatalogueRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Trailer, data.CourseId, data.Type, data.ParentCatalogueId, data.MediaId, data.VideoId, data.VideoName, data.LivingStartTime, data.LivingEndTime, data.PlayBack, data.MediaDuration, data.CIndex, data.DepId, data.Creater, data.Updater, data.Deleted, data.Id)
	}, courseCatalogueIdKey)
	return err
}

func (m *defaultCourseCatalogueModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCourseCatalogueIdPrefix, primary)
}

func (m *defaultCourseCatalogueModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseCatalogueRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseCatalogueModel) tableName() string {
	return m.table
}
