// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseCatalogueDraftFieldNames          = builder.RawFieldNames(&CourseCatalogueDraft{})
	courseCatalogueDraftRows                = strings.Join(courseCatalogueDraftFieldNames, ",")
	courseCatalogueDraftRowsExpectAutoSet   = strings.Join(stringx.Remove(courseCatalogueDraftFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseCatalogueDraftRowsWithPlaceHolder = strings.Join(stringx.Remove(courseCatalogueDraftFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCourseCatalogueDraftIdPrefix = "cache:courseCatalogueDraft:id:"
)

type (
	courseCatalogueDraftModel interface {
		Insert(ctx context.Context, data *CourseCatalogueDraft) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CourseCatalogueDraft, error)
		Update(ctx context.Context, data *CourseCatalogueDraft) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseCatalogueDraftModel struct {
		sqlc.CachedConn
		table string
	}

	CourseCatalogueDraft struct {
		Id                int64         `db:"id"`                  // 课程目录id
		Name              string        `db:"name"`                // 目录名称
		Trailer           int64         `db:"trailer"`             // 是否支持试看
		CourseId          int64         `db:"course_id"`           // 课程id
		Type              int64         `db:"type"`                // 目录类型1：章节，2：小节，3：测试
		ParentCatalogueId int64         `db:"parent_catalogue_id"` // 所属章节id，只有小节和测试有该值，章节没有，章节默认为0
		MediaId           int64         `db:"media_id"`            // 媒资id
		VideoId           sql.NullInt64 `db:"video_id"`            // 视频id
		VideoName         string        `db:"video_name"`          // 视频名称
		LivingStartTime   sql.NullTime  `db:"living_start_time"`   // 直播开始时间
		LivingEndTime     sql.NullTime  `db:"living_end_time"`     // 直播结束时间
		PlayBack          int64         `db:"play_back"`           // 是否支持回放
		CIndex            int64         `db:"c_index"`             // 用于章节排序
		MediaDuration     int64         `db:"media_duration"`      // 以s为单位
		CanUpdate         int64         `db:"can_update"`          // 是否可以更新0：不可以更新，1：可以更新
		DepId             int64         `db:"dep_id"`              // 部门id
		CreateTime        time.Time     `db:"create_time"`         // 创建时间
		UpdateTime        time.Time     `db:"update_time"`         // 更新时间
		Creater           int64         `db:"creater"`             // 创建人
		Updater           int64         `db:"updater"`             // 更新人
		Deleted           int64         `db:"deleted"`             // 逻辑删除
	}
)

func newCourseCatalogueDraftModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseCatalogueDraftModel {
	return &defaultCourseCatalogueDraftModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course_catalogue_draft`",
	}
}

func (m *defaultCourseCatalogueDraftModel) Delete(ctx context.Context, id int64) error {
	courseCatalogueDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueDraftIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, courseCatalogueDraftIdKey)
	return err
}

func (m *defaultCourseCatalogueDraftModel) FindOne(ctx context.Context, id int64) (*CourseCatalogueDraft, error) {
	courseCatalogueDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueDraftIdPrefix, id)
	var resp CourseCatalogueDraft
	err := m.QueryRowCtx(ctx, &resp, courseCatalogueDraftIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseCatalogueDraftRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseCatalogueDraftModel) Insert(ctx context.Context, data *CourseCatalogueDraft) (sql.Result, error) {
	courseCatalogueDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueDraftIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, courseCatalogueDraftRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.Trailer, data.CourseId, data.Type, data.ParentCatalogueId, data.MediaId, data.VideoId, data.VideoName, data.LivingStartTime, data.LivingEndTime, data.PlayBack, data.CIndex, data.MediaDuration, data.CanUpdate, data.DepId, data.Creater, data.Updater, data.Deleted)
	}, courseCatalogueDraftIdKey)
	return ret, err
}

func (m *defaultCourseCatalogueDraftModel) Update(ctx context.Context, data *CourseCatalogueDraft) error {
	courseCatalogueDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueDraftIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseCatalogueDraftRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Trailer, data.CourseId, data.Type, data.ParentCatalogueId, data.MediaId, data.VideoId, data.VideoName, data.LivingStartTime, data.LivingEndTime, data.PlayBack, data.CIndex, data.MediaDuration, data.CanUpdate, data.DepId, data.Creater, data.Updater, data.Deleted, data.Id)
	}, courseCatalogueDraftIdKey)
	return err
}

func (m *defaultCourseCatalogueDraftModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCourseCatalogueDraftIdPrefix, primary)
}

func (m *defaultCourseCatalogueDraftModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseCatalogueDraftRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseCatalogueDraftModel) tableName() string {
	return m.table
}
