// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseSubjectFieldNames          = builder.RawFieldNames(&CourseSubject{})
	courseSubjectRows                = strings.Join(courseSubjectFieldNames, ",")
	courseSubjectRowsExpectAutoSet   = strings.Join(stringx.Remove(courseSubjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseSubjectRowsWithPlaceHolder = strings.Join(stringx.Remove(courseSubjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCourseSubjectIdPrefix = "cache:courseSubject:id:"
)

type (
	courseSubjectModel interface {
		Insert(ctx context.Context, data *CourseSubject) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CourseSubject, error)
		Update(ctx context.Context, data *CourseSubject) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseSubjectModel struct {
		sqlc.CachedConn
		table string
	}

	CourseSubject struct {
		Id        int64 `db:"id"` // 课程题目关系id
		CourseId  int64 `db:"course_id"`
		SubjectId int64 `db:"subject_id"`
	}
)

func newCourseSubjectModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseSubjectModel {
	return &defaultCourseSubjectModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course_subject`",
	}
}

func (m *defaultCourseSubjectModel) Delete(ctx context.Context, id int64) error {
	courseSubjectIdKey := fmt.Sprintf("%s%v", cacheCourseSubjectIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, courseSubjectIdKey)
	return err
}

func (m *defaultCourseSubjectModel) FindOne(ctx context.Context, id int64) (*CourseSubject, error) {
	courseSubjectIdKey := fmt.Sprintf("%s%v", cacheCourseSubjectIdPrefix, id)
	var resp CourseSubject
	err := m.QueryRowCtx(ctx, &resp, courseSubjectIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseSubjectRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseSubjectModel) Insert(ctx context.Context, data *CourseSubject) (sql.Result, error) {
	courseSubjectIdKey := fmt.Sprintf("%s%v", cacheCourseSubjectIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, courseSubjectRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CourseId, data.SubjectId)
	}, courseSubjectIdKey)
	return ret, err
}

func (m *defaultCourseSubjectModel) Update(ctx context.Context, data *CourseSubject) error {
	courseSubjectIdKey := fmt.Sprintf("%s%v", cacheCourseSubjectIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseSubjectRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CourseId, data.SubjectId, data.Id)
	}, courseSubjectIdKey)
	return err
}

func (m *defaultCourseSubjectModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCourseSubjectIdPrefix, primary)
}

func (m *defaultCourseSubjectModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseSubjectRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseSubjectModel) tableName() string {
	return m.table
}
