// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	subjectFieldNames          = builder.RawFieldNames(&Subject{})
	subjectRows                = strings.Join(subjectFieldNames, ",")
	subjectRowsExpectAutoSet   = strings.Join(stringx.Remove(subjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	subjectRowsWithPlaceHolder = strings.Join(stringx.Remove(subjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSubjectIdPrefix = "cache:subject:id:"
)

type (
	subjectModel interface {
		Insert(ctx context.Context, data *Subject) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Subject, error)
		Update(ctx context.Context, data *Subject) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSubjectModel struct {
		sqlc.CachedConn
		table string
	}

	Subject struct {
		Id          int64         `db:"id"`           // 题目id
		Name        string        `db:"name"`         // 题干
		SubjectType int64         `db:"subject_type"` // 题目类型，1：单选题，2：多选题，3：不定向选择题，4：判断题，5：主观题
		Difficulty  int64         `db:"difficulty"`   // 难易度，1：简单，2：中等，3：困难
		Option1     string        `db:"option1"`      // 选择题答案1，
		Option2     string        `db:"option2"`      // 选择题答案2
		Option3     string        `db:"option3"`      // 选择题答案3
		Option4     string        `db:"option4"`      // 选择题答案4
		Option5     string        `db:"option5"`      // 选择题答案5
		Option6     string        `db:"option6"`      // 选择题答案6
		Option7     string        `db:"option7"`      // 选择题答案7
		Option8     string        `db:"option8"`      // 选择题答案8
		Option9     string        `db:"option9"`      // 选择题答案9
		Option10    string        `db:"option10"`     // 选择题答案10
		Answer      string        `db:"answer"`       // 选择题正确答案1到10，如果有多个答案，中间使用逗号隔开，如果是判断题，1：代表正确，其他代表错误
		Analysis    string        `db:"analysis"`     // 答案解析
		UseTimes    int64         `db:"use_times"`    // 引用次数
		AnswerTimes int64         `db:"answer_times"` // 回答次数
		Score       int64         `db:"score"`        // 分值
		DepId       sql.NullInt64 `db:"dep_id"`       // 部门id
		CreateTime  time.Time     `db:"create_time"`  // 创建时间
		UpdateTime  time.Time     `db:"update_time"`  // 更新时间
		Creater     int64         `db:"creater"`      // 创建人
		Updater     int64         `db:"updater"`      // 更新人
		Deleted     int64         `db:"deleted"`      // 逻辑删除
	}
)

func newSubjectModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSubjectModel {
	return &defaultSubjectModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`subject`",
	}
}

func (m *defaultSubjectModel) Delete(ctx context.Context, id int64) error {
	subjectIdKey := fmt.Sprintf("%s%v", cacheSubjectIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, subjectIdKey)
	return err
}

func (m *defaultSubjectModel) FindOne(ctx context.Context, id int64) (*Subject, error) {
	subjectIdKey := fmt.Sprintf("%s%v", cacheSubjectIdPrefix, id)
	var resp Subject
	err := m.QueryRowCtx(ctx, &resp, subjectIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", subjectRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubjectModel) Insert(ctx context.Context, data *Subject) (sql.Result, error) {
	subjectIdKey := fmt.Sprintf("%s%v", cacheSubjectIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, subjectRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.SubjectType, data.Difficulty, data.Option1, data.Option2, data.Option3, data.Option4, data.Option5, data.Option6, data.Option7, data.Option8, data.Option9, data.Option10, data.Answer, data.Analysis, data.UseTimes, data.AnswerTimes, data.Score, data.DepId, data.Creater, data.Updater, data.Deleted)
	}, subjectIdKey)
	return ret, err
}

func (m *defaultSubjectModel) Update(ctx context.Context, data *Subject) error {
	subjectIdKey := fmt.Sprintf("%s%v", cacheSubjectIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, subjectRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.SubjectType, data.Difficulty, data.Option1, data.Option2, data.Option3, data.Option4, data.Option5, data.Option6, data.Option7, data.Option8, data.Option9, data.Option10, data.Answer, data.Analysis, data.UseTimes, data.AnswerTimes, data.Score, data.DepId, data.Creater, data.Updater, data.Deleted, data.Id)
	}, subjectIdKey)
	return err
}

func (m *defaultSubjectModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSubjectIdPrefix, primary)
}

func (m *defaultSubjectModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", subjectRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSubjectModel) tableName() string {
	return m.table
}
