// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponCodeFieldNames          = builder.RawFieldNames(&CouponCode{})
	couponCodeRows                = strings.Join(couponCodeFieldNames, ",")
	couponCodeRowsExpectAutoSet   = strings.Join(stringx.Remove(couponCodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponCodeRowsWithPlaceHolder = strings.Join(stringx.Remove(couponCodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCouponCodeIdPrefix   = "cache:couponCode:id:"
	cacheCouponCodeCodePrefix = "cache:couponCode:code:"
)

type (
	couponCodeModel interface {
		Insert(ctx context.Context, data *CouponCode) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CouponCode, error)
		FindOneByCode(ctx context.Context, code string) (*CouponCode, error)
		Update(ctx context.Context, data *CouponCode) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCouponCodeModel struct {
		sqlc.CachedConn
		table string
	}

	CouponCode struct {
		Id         int64         `db:"id"`          // 兑换码id
		CouponId   int64         `db:"coupon_id"`   // 关联优惠券id
		Code       string        `db:"code"`        // 兑换码
		Status     string        `db:"status"`      // 状态：unused-未使用 used-已使用
		UserId     sql.NullInt64 `db:"user_id"`     // 兑换用户id
		ExpireTime sql.NullTime  `db:"expire_time"` // 过期时间
		CreateTime time.Time     `db:"create_time"` // 创建时间
		UpdateTime time.Time     `db:"update_time"` // 更新时间
		Creater    int64         `db:"creater"`     // 创建人
		Updater    int64         `db:"updater"`     // 更新人
		Deleted    int64         `db:"deleted"`     // 逻辑删除
	}
)

func newCouponCodeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCouponCodeModel {
	return &defaultCouponCodeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`coupon_code`",
	}
}

func (m *defaultCouponCodeModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	couponCodeCodeKey := fmt.Sprintf("%s%v", cacheCouponCodeCodePrefix, data.Code)
	couponCodeIdKey := fmt.Sprintf("%s%v", cacheCouponCodeIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, couponCodeCodeKey, couponCodeIdKey)
	return err
}

func (m *defaultCouponCodeModel) FindOne(ctx context.Context, id int64) (*CouponCode, error) {
	couponCodeIdKey := fmt.Sprintf("%s%v", cacheCouponCodeIdPrefix, id)
	var resp CouponCode
	err := m.QueryRowCtx(ctx, &resp, couponCodeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponCodeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponCodeModel) FindOneByCode(ctx context.Context, code string) (*CouponCode, error) {
	couponCodeCodeKey := fmt.Sprintf("%s%v", cacheCouponCodeCodePrefix, code)
	var resp CouponCode
	err := m.QueryRowIndexCtx(ctx, &resp, couponCodeCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", couponCodeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, code); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponCodeModel) Insert(ctx context.Context, data *CouponCode) (sql.Result, error) {
	couponCodeCodeKey := fmt.Sprintf("%s%v", cacheCouponCodeCodePrefix, data.Code)
	couponCodeIdKey := fmt.Sprintf("%s%v", cacheCouponCodeIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, couponCodeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CouponId, data.Code, data.Status, data.UserId, data.ExpireTime, data.Creater, data.Updater, data.Deleted)
	}, couponCodeCodeKey, couponCodeIdKey)
	return ret, err
}

func (m *defaultCouponCodeModel) Update(ctx context.Context, newData *CouponCode) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	couponCodeCodeKey := fmt.Sprintf("%s%v", cacheCouponCodeCodePrefix, data.Code)
	couponCodeIdKey := fmt.Sprintf("%s%v", cacheCouponCodeIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponCodeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CouponId, newData.Code, newData.Status, newData.UserId, newData.ExpireTime, newData.Creater, newData.Updater, newData.Deleted, newData.Id)
	}, couponCodeCodeKey, couponCodeIdKey)
	return err
}

func (m *defaultCouponCodeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCouponCodeIdPrefix, primary)
}

func (m *defaultCouponCodeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponCodeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCouponCodeModel) tableName() string {
	return m.table
}
