// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponFieldNames          = builder.RawFieldNames(&Coupon{})
	couponRows                = strings.Join(couponFieldNames, ",")
	couponRowsExpectAutoSet   = strings.Join(stringx.Remove(couponFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponRowsWithPlaceHolder = strings.Join(stringx.Remove(couponFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCouponIdPrefix = "cache:coupon:id:"
)

type (
	couponModel interface {
		Insert(ctx context.Context, data *Coupon) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Coupon, error)
		Update(ctx context.Context, data *Coupon) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCouponModel struct {
		sqlc.CachedConn
		table string
	}

	Coupon struct {
		Id                int64          `db:"id"`                  // 优惠券id
		Name              string         `db:"name"`                // 优惠券名称
		DiscountType      string         `db:"discount_type"`       // 优惠类型：reduce-满减 discount-折扣 no_threshold-无门槛
		DiscountValue     int64          `db:"discount_value"`      // 优惠值：满减金额/折扣百分比，单位分
		MaxDiscountAmount int64          `db:"max_discount_amount"` // 最高优惠金额，单位分
		ThresholdAmount   int64          `db:"threshold_amount"`    // 使用门槛金额，单位分，0表示无门槛
		ObtainWay         string         `db:"obtain_way"`          // 获取方式：receive-领取 exchange-兑换码 assign-发放
		Specific          int64          `db:"specific"`            // 是否限定适用范围：0-不限 1-限定
		Scopes            sql.NullString `db:"scopes"`              // 适用范围id列表（课程/分类），specific=1时有效
		TotalNum          int64          `db:"total_num"`           // 发行总量
		IssueNum          int64          `db:"issue_num"`           // 已领取数量
		UsedNum           int64          `db:"used_num"`            // 已使用数量
		UserLimit         int64          `db:"user_limit"`          // 每人限领数量，0-不限
		IssueBeginTime    sql.NullTime   `db:"issue_begin_time"`    // 发放开始时间
		IssueEndTime      sql.NullTime   `db:"issue_end_time"`      // 发放结束时间
		TermBeginTime     sql.NullTime   `db:"term_begin_time"`     // 使用开始时间
		TermEndTime       sql.NullTime   `db:"term_end_time"`       // 使用结束时间
		TermDays          int64          `db:"term_days"`           // 有效期天数（相对领取日），与term_begin/end二选一
		Status            string         `db:"status"`              // 状态：draft-草稿 issued-已发放 paused-暂停 ended-结束
		Remark            string         `db:"remark"`              // 备注
		CreateTime        time.Time      `db:"create_time"`         // 创建时间
		UpdateTime        time.Time      `db:"update_time"`         // 更新时间
		Creater           int64          `db:"creater"`             // 创建人
		Updater           int64          `db:"updater"`             // 更新人
		Deleted           int64          `db:"deleted"`             // 逻辑删除
	}
)

func newCouponModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCouponModel {
	return &defaultCouponModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`coupon`",
	}
}

func (m *defaultCouponModel) Delete(ctx context.Context, id int64) error {
	couponIdKey := fmt.Sprintf("%s%v", cacheCouponIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, couponIdKey)
	return err
}

func (m *defaultCouponModel) FindOne(ctx context.Context, id int64) (*Coupon, error) {
	couponIdKey := fmt.Sprintf("%s%v", cacheCouponIdPrefix, id)
	var resp Coupon
	err := m.QueryRowCtx(ctx, &resp, couponIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponModel) Insert(ctx context.Context, data *Coupon) (sql.Result, error) {
	couponIdKey := fmt.Sprintf("%s%v", cacheCouponIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, couponRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.DiscountType, data.DiscountValue, data.MaxDiscountAmount, data.ThresholdAmount, data.ObtainWay, data.Specific, data.Scopes, data.TotalNum, data.IssueNum, data.UsedNum, data.UserLimit, data.IssueBeginTime, data.IssueEndTime, data.TermBeginTime, data.TermEndTime, data.TermDays, data.Status, data.Remark, data.Creater, data.Updater, data.Deleted)
	}, couponIdKey)
	return ret, err
}

func (m *defaultCouponModel) Update(ctx context.Context, data *Coupon) error {
	couponIdKey := fmt.Sprintf("%s%v", cacheCouponIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.DiscountType, data.DiscountValue, data.MaxDiscountAmount, data.ThresholdAmount, data.ObtainWay, data.Specific, data.Scopes, data.TotalNum, data.IssueNum, data.UsedNum, data.UserLimit, data.IssueBeginTime, data.IssueEndTime, data.TermBeginTime, data.TermEndTime, data.TermDays, data.Status, data.Remark, data.Creater, data.Updater, data.Deleted, data.Id)
	}, couponIdKey)
	return err
}

func (m *defaultCouponModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCouponIdPrefix, primary)
}

func (m *defaultCouponModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCouponModel) tableName() string {
	return m.table
}
