// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Lesson struct {
	Id              int64  `json:"id"`
	CourseId        int64  `json:"courseId"`
	Status          int64  `json:"status"`
	WeekFreq        int64  `json:"weekFreq"`
	PlanStatus      int64  `json:"planStatus"`
	LearnedSections int64  `json:"learnedSections"`
	CreateTime      string `json:"createTime"`
	ExpireTime      string `json:"expireTime,omitempty"`
}

type LessonPage struct {
	List  []Lesson `json:"list"`
	Total int64    `json:"total"`
	Pages int64    `json:"pages"`
}

type LessonRequest struct {
	CourseId int64 `path:"courseId"`
}

type PageRequest struct {
	PageNo   int64 `form:"pageNo,omitempty"`
	PageSize int64 `form:"pageSize,omitempty"`
	IsAsc    bool  `form:"isAsc,omitempty"`
}

type PlanRequest struct {
	CourseId int64 `json:"courseId"`
	Freq     int64 `json:"freq"`
}

type Result struct {
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
	RequestId string `json:"requestId"`
	Data      any    `json:"data"`
}
