// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type IdPathReq struct {
	Id int64 `path:"id"`
}

type IdVO struct {
	Id int64 `json:"id"`
}

type OkVO struct {
	Success bool `json:"success"`
}

type QuestionBizListReq struct {
	BizId    int64 `form:"bizId"`
	PageNo   int64 `form:"pageNo,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type QuestionBizReq struct {
	BizId      int64 `json:"bizId"`
	QuestionId int64 `json:"questionId"`
}

type QuestionListReq struct {
	PageNo     int64  `form:"pageNo,optional"`
	PageSize   int64  `form:"pageSize,optional"`
	Name       string `form:"name,optional"`
	Type       int32  `form:"type,optional"`
	CateId1    int64  `form:"cateId1,optional"`
	CateId2    int64  `form:"cateId2,optional"`
	Difficulty int32  `form:"difficulty,optional"`
}

type QuestionListVO struct {
	Total int64        `json:"total"`
	List  []QuestionVO `json:"list"`
}

type QuestionSaveReq struct {
	Id         int64  `json:"id,optional"`
	Name       string `json:"name"`
	Type       int32  `json:"type"`
	CateId1    int64  `json:"cateId1"`
	CateId2    int64  `json:"cateId2"`
	CateId3    int64  `json:"cateId3"`
	Difficulty int32  `json:"difficulty"`
	Score      int32  `json:"score"`
	Options    string `json:"options,optional"`
	Answer     string `json:"answer"`
	Analysis   string `json:"analysis"`
}

type QuestionVO struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Type         int32  `json:"type"`
	CateId1      int64  `json:"cateId1"`
	CateId2      int64  `json:"cateId2"`
	CateId3      int64  `json:"cateId3"`
	Difficulty   int32  `json:"difficulty"`
	AnswerTimes  int32  `json:"answerTimes"`
	CorrectTimes int32  `json:"correctTimes"`
	Score        int32  `json:"score"`
	CreateTime   string `json:"createTime"`
	Options      string `json:"options"`
	Answer       string `json:"answer"`
	Analysis     string `json:"analysis"`
}
