// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: media.proto

package media

import (
	"context"

	"tjxt/apps/media/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty            = pb.Empty
	FileIdReply      = pb.FileIdReply
	FileIdRequest    = pb.FileIdRequest
	FileSaveRequest  = pb.FileSaveRequest
	FileVO           = pb.FileVO
	MediaIdReply     = pb.MediaIdReply
	MediaIdRequest   = pb.MediaIdRequest
	MediaListReply   = pb.MediaListReply
	MediaListRequest = pb.MediaListRequest
	MediaSaveRequest = pb.MediaSaveRequest
	MediaVO          = pb.MediaVO
	OkVO             = pb.OkVO
	SignatureRequest = pb.SignatureRequest
	SignatureVO      = pb.SignatureVO

	Media interface {
		// 媒资管理
		MediaGet(ctx context.Context, in *MediaIdRequest, opts ...grpc.CallOption) (*MediaVO, error)
		MediaList(ctx context.Context, in *MediaListRequest, opts ...grpc.CallOption) (*MediaListReply, error)
		MediaSave(ctx context.Context, in *MediaSaveRequest, opts ...grpc.CallOption) (*MediaIdReply, error)
		MediaDelete(ctx context.Context, in *MediaIdRequest, opts ...grpc.CallOption) (*Empty, error)
		// 签名相关
		SignatureUpload(ctx context.Context, in *SignatureRequest, opts ...grpc.CallOption) (*SignatureVO, error)
		SignaturePreview(ctx context.Context, in *SignatureRequest, opts ...grpc.CallOption) (*SignatureVO, error)
		SignaturePlay(ctx context.Context, in *SignatureRequest, opts ...grpc.CallOption) (*SignatureVO, error)
		// 文件管理
		FileGet(ctx context.Context, in *FileIdRequest, opts ...grpc.CallOption) (*FileVO, error)
		FileSave(ctx context.Context, in *FileSaveRequest, opts ...grpc.CallOption) (*FileIdReply, error)
		FileDelete(ctx context.Context, in *FileIdRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultMedia struct {
		cli zrpc.Client
	}
)

func NewMedia(cli zrpc.Client) Media {
	return &defaultMedia{
		cli: cli,
	}
}

// 媒资管理
func (m *defaultMedia) MediaGet(ctx context.Context, in *MediaIdRequest, opts ...grpc.CallOption) (*MediaVO, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.MediaGet(ctx, in, opts...)
}

func (m *defaultMedia) MediaList(ctx context.Context, in *MediaListRequest, opts ...grpc.CallOption) (*MediaListReply, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.MediaList(ctx, in, opts...)
}

func (m *defaultMedia) MediaSave(ctx context.Context, in *MediaSaveRequest, opts ...grpc.CallOption) (*MediaIdReply, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.MediaSave(ctx, in, opts...)
}

func (m *defaultMedia) MediaDelete(ctx context.Context, in *MediaIdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.MediaDelete(ctx, in, opts...)
}

// 签名相关
func (m *defaultMedia) SignatureUpload(ctx context.Context, in *SignatureRequest, opts ...grpc.CallOption) (*SignatureVO, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.SignatureUpload(ctx, in, opts...)
}

func (m *defaultMedia) SignaturePreview(ctx context.Context, in *SignatureRequest, opts ...grpc.CallOption) (*SignatureVO, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.SignaturePreview(ctx, in, opts...)
}

func (m *defaultMedia) SignaturePlay(ctx context.Context, in *SignatureRequest, opts ...grpc.CallOption) (*SignatureVO, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.SignaturePlay(ctx, in, opts...)
}

// 文件管理
func (m *defaultMedia) FileGet(ctx context.Context, in *FileIdRequest, opts ...grpc.CallOption) (*FileVO, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.FileGet(ctx, in, opts...)
}

func (m *defaultMedia) FileSave(ctx context.Context, in *FileSaveRequest, opts ...grpc.CallOption) (*FileIdReply, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.FileSave(ctx, in, opts...)
}

func (m *defaultMedia) FileDelete(ctx context.Context, in *FileIdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.FileDelete(ctx, in, opts...)
}
