// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	account "tjxt/apps/auth/api/internal/handler/account"
	assign "tjxt/apps/auth/api/internal/handler/assign"
	loginrecord "tjxt/apps/auth/api/internal/handler/loginrecord"
	menu "tjxt/apps/auth/api/internal/handler/menu"
	privilege "tjxt/apps/auth/api/internal/handler/privilege"
	role "tjxt/apps/auth/api/internal/handler/role"
	"tjxt/apps/auth/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/accounts/:id/roles",
				Handler: account.SaveAccountRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/accounts/:id/roles",
				Handler: account.GetAccountRolesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/accounts/login",
				Handler: account.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/roles/:id/menus",
				Handler: assign.SaveRoleMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles/:id/menus",
				Handler: assign.GetRoleMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/roles/:id/privileges",
				Handler: assign.SaveRolePrivilegesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles/:id/privileges",
				Handler: assign.GetRolePrivilegesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/login-records",
				Handler: loginrecord.ListLoginRecordsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/menus",
				Handler: menu.SaveMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/menus/:id",
				Handler: menu.DeleteMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/menus/tree",
				Handler: menu.GetMenuTreeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/menus/:id/privileges",
				Handler: privilege.GetPrivilegesByMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/privileges",
				Handler: privilege.SavePrivilegeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/privileges/:id",
				Handler: privilege.DeletePrivilegeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/roles",
				Handler: role.SaveRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles",
				Handler: role.ListRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/roles/:id",
				Handler: role.DeleteRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles/:id",
				Handler: role.GetRoleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
