// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseCataSubjectDraftFieldNames          = builder.RawFieldNames(&CourseCataSubjectDraft{})
	courseCataSubjectDraftRows                = strings.Join(courseCataSubjectDraftFieldNames, ",")
	courseCataSubjectDraftRowsExpectAutoSet   = strings.Join(stringx.Remove(courseCataSubjectDraftFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseCataSubjectDraftRowsWithPlaceHolder = strings.Join(stringx.Remove(courseCataSubjectDraftFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCourseCataSubjectDraftIdPrefix = "cache:courseCataSubjectDraft:id:"
)

type (
	courseCataSubjectDraftModel interface {
		Insert(ctx context.Context, data *CourseCataSubjectDraft) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CourseCataSubjectDraft, error)
		Update(ctx context.Context, data *CourseCataSubjectDraft) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseCataSubjectDraftModel struct {
		sqlc.CachedConn
		table string
	}

	CourseCataSubjectDraft struct {
		Id        int64         `db:"id"` // 小节题目关系id
		CourseId  sql.NullInt64 `db:"course_id"`
		CataId    int64         `db:"cata_id"`    // 小节id
		SubjectId int64         `db:"subject_id"` // 题目id
	}
)

func newCourseCataSubjectDraftModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseCataSubjectDraftModel {
	return &defaultCourseCataSubjectDraftModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course_cata_subject_draft`",
	}
}

func (m *defaultCourseCataSubjectDraftModel) Delete(ctx context.Context, id int64) error {
	courseCataSubjectDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCataSubjectDraftIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, courseCataSubjectDraftIdKey)
	return err
}

func (m *defaultCourseCataSubjectDraftModel) FindOne(ctx context.Context, id int64) (*CourseCataSubjectDraft, error) {
	courseCataSubjectDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCataSubjectDraftIdPrefix, id)
	var resp CourseCataSubjectDraft
	err := m.QueryRowCtx(ctx, &resp, courseCataSubjectDraftIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseCataSubjectDraftRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseCataSubjectDraftModel) Insert(ctx context.Context, data *CourseCataSubjectDraft) (sql.Result, error) {
	courseCataSubjectDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCataSubjectDraftIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, courseCataSubjectDraftRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CourseId, data.CataId, data.SubjectId)
	}, courseCataSubjectDraftIdKey)
	return ret, err
}

func (m *defaultCourseCataSubjectDraftModel) Update(ctx context.Context, data *CourseCataSubjectDraft) error {
	courseCataSubjectDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCataSubjectDraftIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseCataSubjectDraftRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CourseId, data.CataId, data.SubjectId, data.Id)
	}, courseCataSubjectDraftIdKey)
	return err
}

func (m *defaultCourseCataSubjectDraftModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCourseCataSubjectDraftIdPrefix, primary)
}

func (m *defaultCourseCataSubjectDraftModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseCataSubjectDraftRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseCataSubjectDraftModel) tableName() string {
	return m.table
}
