// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseCatalogueDraftFieldNames          = builder.RawFieldNames(&CourseCatalogueDraft{})
	courseCatalogueDraftRows                = strings.Join(courseCatalogueDraftFieldNames, ",")
	courseCatalogueDraftRowsExpectAutoSet   = strings.Join(stringx.Remove(courseCatalogueDraftFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseCatalogueDraftRowsWithPlaceHolder = strings.Join(stringx.Remove(courseCatalogueDraftFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCourseCatalogueDraftIdPrefix = "cache:courseCatalogueDraft:id:"
)

type (
	courseCatalogueDraftModel interface {
		Insert(ctx context.Context, data *CourseCatalogueDraft) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CourseCatalogueDraft, error)
		Update(ctx context.Context, data *CourseCatalogueDraft) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseCatalogueDraftModel struct {
		sqlc.CachedConn
		table string
	}

	CourseCatalogueDraft struct {
		Id            int64     `db:"id"`             // 目录id
		CourseId      int64     `db:"course_id"`      // 课程id
		ParentId      int64     `db:"parent_id"`      // 父id，章的父id为0
		Index         int64     `db:"index"`          // 序号
		Name          string    `db:"name"`           // 目录名称
		Type          int64     `db:"type"`           // 目录类型，1：章，2：节，3：练习
		MediaDuration int64     `db:"media_duration"` // 媒资时长，单位秒
		Trailer       int64     `db:"trailer"`        // 是否试看，0否，1是
		MediaName     string    `db:"media_name"`     // 媒资名称
		MediaId       int64     `db:"media_id"`       // 媒资id
		SubjectNum    int64     `db:"subject_num"`    // 题目数量
		TotalScore    int64     `db:"total_score"`    // 总分
		CanUpdate     int64     `db:"can_update"`     // 是否可更新
		CreateTime    time.Time `db:"create_time"`    // 创建时间
		UpdateTime    time.Time `db:"update_time"`    // 更新时间
		Deleted       int64     `db:"deleted"`
	}
)

func newCourseCatalogueDraftModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseCatalogueDraftModel {
	return &defaultCourseCatalogueDraftModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course_catalogue_draft`",
	}
}

func (m *defaultCourseCatalogueDraftModel) Delete(ctx context.Context, id int64) error {
	courseCatalogueDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueDraftIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, courseCatalogueDraftIdKey)
	return err
}

func (m *defaultCourseCatalogueDraftModel) FindOne(ctx context.Context, id int64) (*CourseCatalogueDraft, error) {
	courseCatalogueDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueDraftIdPrefix, id)
	var resp CourseCatalogueDraft
	err := m.QueryRowCtx(ctx, &resp, courseCatalogueDraftIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseCatalogueDraftRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseCatalogueDraftModel) Insert(ctx context.Context, data *CourseCatalogueDraft) (sql.Result, error) {
	courseCatalogueDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueDraftIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, courseCatalogueDraftRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CourseId, data.ParentId, data.Index, data.Name, data.Type, data.MediaDuration, data.Trailer, data.MediaName, data.MediaId, data.SubjectNum, data.TotalScore, data.CanUpdate, data.Deleted)
	}, courseCatalogueDraftIdKey)
	return ret, err
}

func (m *defaultCourseCatalogueDraftModel) Update(ctx context.Context, data *CourseCatalogueDraft) error {
	courseCatalogueDraftIdKey := fmt.Sprintf("%s%v", cacheCourseCatalogueDraftIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseCatalogueDraftRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CourseId, data.ParentId, data.Index, data.Name, data.Type, data.MediaDuration, data.Trailer, data.MediaName, data.MediaId, data.SubjectNum, data.TotalScore, data.CanUpdate, data.Deleted, data.Id)
	}, courseCatalogueDraftIdKey)
	return err
}

func (m *defaultCourseCatalogueDraftModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCourseCatalogueDraftIdPrefix, primary)
}

func (m *defaultCourseCatalogueDraftModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseCatalogueDraftRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseCatalogueDraftModel) tableName() string {
	return m.table
}
