// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"course/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/categories",
				Handler: CategoryAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/categories",
				Handler: CategoryUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/categories/:id",
				Handler: CategoryInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/categories/page",
				Handler: CategoryPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/categories/status",
				Handler: CategoryDisableOrEnableHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/categories/tree",
				Handler: CategoryTreeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/course/andCatalog/:id",
				Handler: CourseAndCatalogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/course/dtoById/:id",
				Handler: CourseDTOByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/course/infoById/:id",
				Handler: CourseInfoByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/course/infoByTeacherIds",
				Handler: CourseInfoByTeacherIdsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/course/media/useInfo",
				Handler: CourseMediaUseInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/course/name",
				Handler: CourseNameQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/course/simpleInfo/list",
				Handler: CourseSimpleInfoListHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/courses/:id",
				Handler: CourseDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/:id/checkUpShelf",
				Handler: CourseUpShelfCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/courses/:id/downShelf",
				Handler: CourseDownShelfHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/courses/:id/upShelf",
				Handler: CourseUpShelfHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/baseInfo/:id",
				Handler: CourseBaseInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/courses/baseInfo/save",
				Handler: CourseBaseInfoSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/catas/:id",
				Handler: CourseCatasHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/catas/index/list/:id",
				Handler: CourseCatasIndexListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/courses/catas/save/:id/:step",
				Handler: CourseCatasSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/courses/media/save/:id",
				Handler: CourseMediaSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/name",
				Handler: CourseCheckNameHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/page",
				Handler: CoursePageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/subjects/:id",
				Handler: CourseSubjectsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/courses/subjects/save/:id",
				Handler: CourseSubjectsSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/courses/teachers/:id",
				Handler: CourseTeachersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/courses/teachers/save",
				Handler: CourseTeachersSaveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
