// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type FileIdPathReq struct {
	Id int64 `path:"id"`
}

type FileIdVO struct {
	Id int64 `json:"id"`
}

type FileSaveReq struct {
	Filename string `json:"filename"`
	Key      string `json:"key"`
	Size     int64  `json:"size"`
}

type FileVO struct {
	Id       int64  `json:"id"`
	Key      string `json:"key"`
	Filename string `json:"filename"`
	Path     string `json:"path"`
	Status   int32  `json:"status"`
}

type MediaIdPathReq struct {
	Id int64 `path:"id"`
}

type MediaIdVO struct {
	Id int64 `json:"id"`
}

type MediaListReq struct {
	PageNo   int64  `form:"pageNo,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Name     string `form:"name,optional"`
	SortBy   string `form:"sortBy,optional"`
	IsAsc    string `form:"isAsc,optional"`
}

type MediaListVO struct {
	Total int64     `json:"total"`
	List  []MediaVO `json:"list"`
}

type MediaSaveReq struct {
	Id       int64   `json:"id,optional"`
	Filename string  `json:"filename"`
	Duration float64 `json:"duration"`
	Size     int64   `json:"size"`
	FileId   string  `json:"fileId"`
}

type MediaVO struct {
	Id         int64   `json:"id"`
	Filename   string  `json:"filename"`
	MediaUrl   string  `json:"mediaUrl"`
	CoverUrl   string  `json:"coverUrl"`
	Duration   float64 `json:"duration"`
	Size       int64   `json:"size"`
	Status     int32   `json:"status"`
	Creater    string  `json:"creater"`
	CreateTime string  `json:"createTime"`
	UseTimes   int32   `json:"useTimes"`
}

type OkVO struct {
	Success bool `json:"success"`
}

type SignatureReq struct {
	MediaId   int64  `json:"mediaId,optional"`
	FileName  string `json:"fileName"`
	MediaType string `json:"mediaType"`
}

type SignatureVO struct {
	Token     string `json:"token"`
	Url       string `json:"url"`
	UploadUrl string `json:"uploadUrl"`
	PlayUrl   string `json:"playUrl"`
}
