// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: promotion.proto

package server

import (
	"context"

	"tjxt/apps/promotion/rpc/internal/logic"
	"tjxt/apps/promotion/rpc/internal/svc"
	"tjxt/apps/promotion/rpc/pb"
)

type PromotionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPromotionServer
}

func NewPromotionServer(svcCtx *svc.ServiceContext) *PromotionServer {
	return &PromotionServer{
		svcCtx: svcCtx,
	}
}

// 优惠券管理
func (s *PromotionServer) CouponCreate(ctx context.Context, in *pb.CouponFormDTO) (*pb.CouponDetailVO, error) {
	l := logic.NewCouponCreateLogic(ctx, s.svcCtx)
	return l.CouponCreate(in)
}

func (s *PromotionServer) CouponList(ctx context.Context, in *pb.CouponListRequest) (*pb.CouponListReply, error) {
	l := logic.NewCouponListLogic(ctx, s.svcCtx)
	return l.CouponList(in)
}

func (s *PromotionServer) CouponPage(ctx context.Context, in *pb.CouponPageRequest) (*pb.CouponPageReply, error) {
	l := logic.NewCouponPageLogic(ctx, s.svcCtx)
	return l.CouponPage(in)
}

func (s *PromotionServer) CouponGet(ctx context.Context, in *pb.IdRequest) (*pb.CouponDetailVO, error) {
	l := logic.NewCouponGetLogic(ctx, s.svcCtx)
	return l.CouponGet(in)
}

func (s *PromotionServer) CouponDelete(ctx context.Context, in *pb.IdRequest) (*pb.Empty, error) {
	l := logic.NewCouponDeleteLogic(ctx, s.svcCtx)
	return l.CouponDelete(in)
}

func (s *PromotionServer) CouponIssue(ctx context.Context, in *pb.CouponIssueFormDTO) (*pb.Empty, error) {
	l := logic.NewCouponIssueLogic(ctx, s.svcCtx)
	return l.CouponIssue(in)
}

func (s *PromotionServer) CouponPause(ctx context.Context, in *pb.IdRequest) (*pb.Empty, error) {
	l := logic.NewCouponPauseLogic(ctx, s.svcCtx)
	return l.CouponPause(in)
}

// 用户优惠券
func (s *PromotionServer) UserCouponAvailable(ctx context.Context, in *pb.OrderCourseListRequest) (*pb.CouponDiscountListReply, error) {
	l := logic.NewUserCouponAvailableLogic(ctx, s.svcCtx)
	return l.UserCouponAvailable(in)
}

func (s *PromotionServer) UserCouponDiscount(ctx context.Context, in *pb.OrderCouponDTO) (*pb.CouponDiscountDTO, error) {
	l := logic.NewUserCouponDiscountLogic(ctx, s.svcCtx)
	return l.UserCouponDiscount(in)
}

func (s *PromotionServer) UserCouponPage(ctx context.Context, in *pb.UserCouponPageRequest) (*pb.UserCouponPageReply, error) {
	l := logic.NewUserCouponPageLogic(ctx, s.svcCtx)
	return l.UserCouponPage(in)
}

func (s *PromotionServer) UserCouponRefund(ctx context.Context, in *pb.IdsRequest) (*pb.Empty, error) {
	l := logic.NewUserCouponRefundLogic(ctx, s.svcCtx)
	return l.UserCouponRefund(in)
}

func (s *PromotionServer) UserCouponRules(ctx context.Context, in *pb.IdsRequest) (*pb.RulesReply, error) {
	l := logic.NewUserCouponRulesLogic(ctx, s.svcCtx)
	return l.UserCouponRules(in)
}

func (s *PromotionServer) UserCouponUse(ctx context.Context, in *pb.IdsRequest) (*pb.Empty, error) {
	l := logic.NewUserCouponUseLogic(ctx, s.svcCtx)
	return l.UserCouponUse(in)
}

func (s *PromotionServer) UserCouponExchange(ctx context.Context, in *pb.ExchangeRequest) (*pb.Empty, error) {
	l := logic.NewUserCouponExchangeLogic(ctx, s.svcCtx)
	return l.UserCouponExchange(in)
}

func (s *PromotionServer) UserCouponReceive(ctx context.Context, in *pb.IdRequest) (*pb.Empty, error) {
	l := logic.NewUserCouponReceiveLogic(ctx, s.svcCtx)
	return l.UserCouponReceive(in)
}

// 兑换码
func (s *PromotionServer) CouponCodePage(ctx context.Context, in *pb.CouponCodePageRequest) (*pb.CouponCodePageReply, error) {
	l := logic.NewCouponCodePageLogic(ctx, s.svcCtx)
	return l.CouponCodePage(in)
}
