// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	inbox "tjxt/apps/message/api/internal/handler/inbox"
	messagetemplate "tjxt/apps/message/api/internal/handler/messagetemplate"
	notice "tjxt/apps/message/api/internal/handler/notice"
	noticetask "tjxt/apps/message/api/internal/handler/noticetask"
	noticetemplate "tjxt/apps/message/api/internal/handler/noticetemplate"
	smsplatform "tjxt/apps/message/api/internal/handler/smsplatform"
	"tjxt/apps/message/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/inbox",
				Handler: inbox.ListInboxHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/inbox/:id",
				Handler: inbox.DeleteInboxHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/inbox/:id/read",
				Handler: inbox.MarkInboxReadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/message-templates",
				Handler: messagetemplate.SaveMessageTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/message-templates",
				Handler: messagetemplate.ListMessageTemplatesHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/message-templates/:id",
				Handler: messagetemplate.DeleteMessageTemplateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/notices",
				Handler: notice.SavePublicNoticeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notices",
				Handler: notice.ListPublicNoticesHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/notices/:id",
				Handler: notice.DeletePublicNoticeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/notice-tasks",
				Handler: noticetask.SaveNoticeTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notice-tasks",
				Handler: noticetask.ListNoticeTasksHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/notice-tasks/:id",
				Handler: noticetask.DeleteNoticeTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notice-tasks/:id",
				Handler: noticetask.GetNoticeTaskHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/notice-templates",
				Handler: noticetemplate.SaveNoticeTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notice-templates",
				Handler: noticetemplate.ListNoticeTemplatesHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/notice-templates/:id",
				Handler: noticetemplate.DeleteNoticeTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notice-templates/:id",
				Handler: noticetemplate.GetNoticeTemplateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/sms-platforms",
				Handler: smsplatform.ListSmsPlatformsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
