// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: exam.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Exam_SaveQuestion_FullMethodName      = "/exam.Exam/SaveQuestion"
	Exam_DeleteQuestion_FullMethodName    = "/exam.Exam/DeleteQuestion"
	Exam_GetQuestion_FullMethodName       = "/exam.Exam/GetQuestion"
	Exam_ListQuestions_FullMethodName     = "/exam.Exam/ListQuestions"
	Exam_AddQuestionBiz_FullMethodName    = "/exam.Exam/AddQuestionBiz"
	Exam_RemoveQuestionBiz_FullMethodName = "/exam.Exam/RemoveQuestionBiz"
	Exam_GetQuestionsByBiz_FullMethodName = "/exam.Exam/GetQuestionsByBiz"
)

// ExamClient is the client API for Exam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== 服务定义 ====================
type ExamClient interface {
	// 题目管理
	SaveQuestion(ctx context.Context, in *QuestionSaveReq, opts ...grpc.CallOption) (*IdReply, error)
	DeleteQuestion(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
	GetQuestion(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*QuestionVO, error)
	ListQuestions(ctx context.Context, in *QuestionListReq, opts ...grpc.CallOption) (*QuestionListReply, error)
	// 题目业务关联
	AddQuestionBiz(ctx context.Context, in *QuestionBizReq, opts ...grpc.CallOption) (*IdReply, error)
	RemoveQuestionBiz(ctx context.Context, in *QuestionBizReq, opts ...grpc.CallOption) (*Empty, error)
	GetQuestionsByBiz(ctx context.Context, in *QuestionBizListReq, opts ...grpc.CallOption) (*QuestionListReply, error)
}

type examClient struct {
	cc grpc.ClientConnInterface
}

func NewExamClient(cc grpc.ClientConnInterface) ExamClient {
	return &examClient{cc}
}

func (c *examClient) SaveQuestion(ctx context.Context, in *QuestionSaveReq, opts ...grpc.CallOption) (*IdReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdReply)
	err := c.cc.Invoke(ctx, Exam_SaveQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) DeleteQuestion(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Exam_DeleteQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetQuestion(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*QuestionVO, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionVO)
	err := c.cc.Invoke(ctx, Exam_GetQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) ListQuestions(ctx context.Context, in *QuestionListReq, opts ...grpc.CallOption) (*QuestionListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionListReply)
	err := c.cc.Invoke(ctx, Exam_ListQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) AddQuestionBiz(ctx context.Context, in *QuestionBizReq, opts ...grpc.CallOption) (*IdReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdReply)
	err := c.cc.Invoke(ctx, Exam_AddQuestionBiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) RemoveQuestionBiz(ctx context.Context, in *QuestionBizReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Exam_RemoveQuestionBiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetQuestionsByBiz(ctx context.Context, in *QuestionBizListReq, opts ...grpc.CallOption) (*QuestionListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionListReply)
	err := c.cc.Invoke(ctx, Exam_GetQuestionsByBiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExamServer is the server API for Exam service.
// All implementations must embed UnimplementedExamServer
// for forward compatibility.
//
// ==================== 服务定义 ====================
type ExamServer interface {
	// 题目管理
	SaveQuestion(context.Context, *QuestionSaveReq) (*IdReply, error)
	DeleteQuestion(context.Context, *IdReq) (*Empty, error)
	GetQuestion(context.Context, *IdReq) (*QuestionVO, error)
	ListQuestions(context.Context, *QuestionListReq) (*QuestionListReply, error)
	// 题目业务关联
	AddQuestionBiz(context.Context, *QuestionBizReq) (*IdReply, error)
	RemoveQuestionBiz(context.Context, *QuestionBizReq) (*Empty, error)
	GetQuestionsByBiz(context.Context, *QuestionBizListReq) (*QuestionListReply, error)
	mustEmbedUnimplementedExamServer()
}

// UnimplementedExamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExamServer struct{}

func (UnimplementedExamServer) SaveQuestion(context.Context, *QuestionSaveReq) (*IdReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveQuestion not implemented")
}
func (UnimplementedExamServer) DeleteQuestion(context.Context, *IdReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteQuestion not implemented")
}
func (UnimplementedExamServer) GetQuestion(context.Context, *IdReq) (*QuestionVO, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuestion not implemented")
}
func (UnimplementedExamServer) ListQuestions(context.Context, *QuestionListReq) (*QuestionListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQuestions not implemented")
}
func (UnimplementedExamServer) AddQuestionBiz(context.Context, *QuestionBizReq) (*IdReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AddQuestionBiz not implemented")
}
func (UnimplementedExamServer) RemoveQuestionBiz(context.Context, *QuestionBizReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveQuestionBiz not implemented")
}
func (UnimplementedExamServer) GetQuestionsByBiz(context.Context, *QuestionBizListReq) (*QuestionListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuestionsByBiz not implemented")
}
func (UnimplementedExamServer) mustEmbedUnimplementedExamServer() {}
func (UnimplementedExamServer) testEmbeddedByValue()              {}

// UnsafeExamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExamServer will
// result in compilation errors.
type UnsafeExamServer interface {
	mustEmbedUnimplementedExamServer()
}

func RegisterExamServer(s grpc.ServiceRegistrar, srv ExamServer) {
	// If the following call panics, it indicates UnimplementedExamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Exam_ServiceDesc, srv)
}

func _Exam_SaveQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).SaveQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_SaveQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).SaveQuestion(ctx, req.(*QuestionSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_DeleteQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).DeleteQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_DeleteQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).DeleteQuestion(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetQuestion(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_ListQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).ListQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_ListQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).ListQuestions(ctx, req.(*QuestionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_AddQuestionBiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionBizReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).AddQuestionBiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_AddQuestionBiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).AddQuestionBiz(ctx, req.(*QuestionBizReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_RemoveQuestionBiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionBizReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).RemoveQuestionBiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_RemoveQuestionBiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).RemoveQuestionBiz(ctx, req.(*QuestionBizReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetQuestionsByBiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionBizListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetQuestionsByBiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetQuestionsByBiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetQuestionsByBiz(ctx, req.(*QuestionBizListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Exam_ServiceDesc is the grpc.ServiceDesc for Exam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exam.Exam",
	HandlerType: (*ExamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveQuestion",
			Handler:    _Exam_SaveQuestion_Handler,
		},
		{
			MethodName: "DeleteQuestion",
			Handler:    _Exam_DeleteQuestion_Handler,
		},
		{
			MethodName: "GetQuestion",
			Handler:    _Exam_GetQuestion_Handler,
		},
		{
			MethodName: "ListQuestions",
			Handler:    _Exam_ListQuestions_Handler,
		},
		{
			MethodName: "AddQuestionBiz",
			Handler:    _Exam_AddQuestionBiz_Handler,
		},
		{
			MethodName: "RemoveQuestionBiz",
			Handler:    _Exam_RemoveQuestionBiz_Handler,
		},
		{
			MethodName: "GetQuestionsByBiz",
			Handler:    _Exam_GetQuestionsByBiz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exam.proto",
}
