// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: exam.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 空消息
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_exam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{0}
}

// 通用ID请求/回复
type IdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdReq) Reset() {
	*x = IdReq{}
	mi := &file_exam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReq) ProtoMessage() {}

func (x *IdReq) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReq.ProtoReflect.Descriptor instead.
func (*IdReq) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{1}
}

func (x *IdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdReply) Reset() {
	*x = IdReply{}
	mi := &file_exam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReply) ProtoMessage() {}

func (x *IdReply) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReply.ProtoReflect.Descriptor instead.
func (*IdReply) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{2}
}

func (x *IdReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int32                  `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	mi := &file_exam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{3}
}

func (x *PageReq) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *PageReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ==================== 题目 ====================
type QuestionVO struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type         int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	CateId1      int64                  `protobuf:"varint,4,opt,name=cateId1,proto3" json:"cateId1,omitempty"`
	CateId2      int64                  `protobuf:"varint,5,opt,name=cateId2,proto3" json:"cateId2,omitempty"`
	CateId3      int64                  `protobuf:"varint,6,opt,name=cateId3,proto3" json:"cateId3,omitempty"`
	Difficulty   int32                  `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	AnswerTimes  int32                  `protobuf:"varint,8,opt,name=answerTimes,proto3" json:"answerTimes,omitempty"`
	CorrectTimes int32                  `protobuf:"varint,9,opt,name=correctTimes,proto3" json:"correctTimes,omitempty"`
	Score        int32                  `protobuf:"varint,10,opt,name=score,proto3" json:"score,omitempty"`
	CreateTime   string                 `protobuf:"bytes,11,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 详情
	Options       string `protobuf:"bytes,12,opt,name=options,proto3" json:"options,omitempty"`
	Answer        string `protobuf:"bytes,13,opt,name=answer,proto3" json:"answer,omitempty"`
	Analysis      string `protobuf:"bytes,14,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionVO) Reset() {
	*x = QuestionVO{}
	mi := &file_exam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionVO) ProtoMessage() {}

func (x *QuestionVO) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionVO.ProtoReflect.Descriptor instead.
func (*QuestionVO) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{4}
}

func (x *QuestionVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuestionVO) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *QuestionVO) GetCateId1() int64 {
	if x != nil {
		return x.CateId1
	}
	return 0
}

func (x *QuestionVO) GetCateId2() int64 {
	if x != nil {
		return x.CateId2
	}
	return 0
}

func (x *QuestionVO) GetCateId3() int64 {
	if x != nil {
		return x.CateId3
	}
	return 0
}

func (x *QuestionVO) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *QuestionVO) GetAnswerTimes() int32 {
	if x != nil {
		return x.AnswerTimes
	}
	return 0
}

func (x *QuestionVO) GetCorrectTimes() int32 {
	if x != nil {
		return x.CorrectTimes
	}
	return 0
}

func (x *QuestionVO) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuestionVO) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *QuestionVO) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *QuestionVO) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QuestionVO) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

type QuestionSaveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	CateId1       int64                  `protobuf:"varint,4,opt,name=cateId1,proto3" json:"cateId1,omitempty"`
	CateId2       int64                  `protobuf:"varint,5,opt,name=cateId2,proto3" json:"cateId2,omitempty"`
	CateId3       int64                  `protobuf:"varint,6,opt,name=cateId3,proto3" json:"cateId3,omitempty"`
	Difficulty    int32                  `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Score         int32                  `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	Options       string                 `protobuf:"bytes,9,opt,name=options,proto3" json:"options,omitempty"`
	Answer        string                 `protobuf:"bytes,10,opt,name=answer,proto3" json:"answer,omitempty"`
	Analysis      string                 `protobuf:"bytes,11,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionSaveReq) Reset() {
	*x = QuestionSaveReq{}
	mi := &file_exam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionSaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionSaveReq) ProtoMessage() {}

func (x *QuestionSaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionSaveReq.ProtoReflect.Descriptor instead.
func (*QuestionSaveReq) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{5}
}

func (x *QuestionSaveReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionSaveReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuestionSaveReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *QuestionSaveReq) GetCateId1() int64 {
	if x != nil {
		return x.CateId1
	}
	return 0
}

func (x *QuestionSaveReq) GetCateId2() int64 {
	if x != nil {
		return x.CateId2
	}
	return 0
}

func (x *QuestionSaveReq) GetCateId3() int64 {
	if x != nil {
		return x.CateId3
	}
	return 0
}

func (x *QuestionSaveReq) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *QuestionSaveReq) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuestionSaveReq) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *QuestionSaveReq) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QuestionSaveReq) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

type QuestionListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int32                  `protobuf:"varint,1,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	CateId1       int64                  `protobuf:"varint,5,opt,name=cateId1,proto3" json:"cateId1,omitempty"`
	CateId2       int64                  `protobuf:"varint,6,opt,name=cateId2,proto3" json:"cateId2,omitempty"`
	Difficulty    int32                  `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionListReq) Reset() {
	*x = QuestionListReq{}
	mi := &file_exam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionListReq) ProtoMessage() {}

func (x *QuestionListReq) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionListReq.ProtoReflect.Descriptor instead.
func (*QuestionListReq) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{6}
}

func (x *QuestionListReq) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *QuestionListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QuestionListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuestionListReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *QuestionListReq) GetCateId1() int64 {
	if x != nil {
		return x.CateId1
	}
	return 0
}

func (x *QuestionListReq) GetCateId2() int64 {
	if x != nil {
		return x.CateId2
	}
	return 0
}

func (x *QuestionListReq) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

type QuestionListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*QuestionVO          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionListReply) Reset() {
	*x = QuestionListReply{}
	mi := &file_exam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionListReply) ProtoMessage() {}

func (x *QuestionListReply) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionListReply.ProtoReflect.Descriptor instead.
func (*QuestionListReply) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{7}
}

func (x *QuestionListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QuestionListReply) GetList() []*QuestionVO {
	if x != nil {
		return x.List
	}
	return nil
}

// ==================== 题目业务关联 ====================
type QuestionBizReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         int64                  `protobuf:"varint,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	QuestionId    int64                  `protobuf:"varint,2,opt,name=questionId,proto3" json:"questionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionBizReq) Reset() {
	*x = QuestionBizReq{}
	mi := &file_exam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionBizReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionBizReq) ProtoMessage() {}

func (x *QuestionBizReq) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionBizReq.ProtoReflect.Descriptor instead.
func (*QuestionBizReq) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{8}
}

func (x *QuestionBizReq) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *QuestionBizReq) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type QuestionBizListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         int64                  `protobuf:"varint,1,opt,name=bizId,proto3" json:"bizId,omitempty"`
	PageNo        int32                  `protobuf:"varint,2,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionBizListReq) Reset() {
	*x = QuestionBizListReq{}
	mi := &file_exam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionBizListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionBizListReq) ProtoMessage() {}

func (x *QuestionBizListReq) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionBizListReq.ProtoReflect.Descriptor instead.
func (*QuestionBizListReq) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{9}
}

func (x *QuestionBizListReq) GetBizId() int64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *QuestionBizListReq) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *QuestionBizListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_exam_proto protoreflect.FileDescriptor

const file_exam_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"exam.proto\x12\x04exam\"\a\n" +
	"\x05Empty\"\x17\n" +
	"\x05IdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x19\n" +
	"\aIdReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\aPageReq\x12\x16\n" +
	"\x06pageNo\x18\x01 \x01(\x05R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"\xfc\x02\n" +
	"\n" +
	"QuestionVO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x18\n" +
	"\acateId1\x18\x04 \x01(\x03R\acateId1\x12\x18\n" +
	"\acateId2\x18\x05 \x01(\x03R\acateId2\x12\x18\n" +
	"\acateId3\x18\x06 \x01(\x03R\acateId3\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\x05R\n" +
	"difficulty\x12 \n" +
	"\vanswerTimes\x18\b \x01(\x05R\vanswerTimes\x12\"\n" +
	"\fcorrectTimes\x18\t \x01(\x05R\fcorrectTimes\x12\x14\n" +
	"\x05score\x18\n" +
	" \x01(\x05R\x05score\x12\x1e\n" +
	"\n" +
	"createTime\x18\v \x01(\tR\n" +
	"createTime\x12\x18\n" +
	"\aoptions\x18\f \x01(\tR\aoptions\x12\x16\n" +
	"\x06answer\x18\r \x01(\tR\x06answer\x12\x1a\n" +
	"\banalysis\x18\x0e \x01(\tR\banalysis\"\x9b\x02\n" +
	"\x0fQuestionSaveReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x18\n" +
	"\acateId1\x18\x04 \x01(\x03R\acateId1\x12\x18\n" +
	"\acateId2\x18\x05 \x01(\x03R\acateId2\x12\x18\n" +
	"\acateId3\x18\x06 \x01(\x03R\acateId3\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\x05R\n" +
	"difficulty\x12\x14\n" +
	"\x05score\x18\b \x01(\x05R\x05score\x12\x18\n" +
	"\aoptions\x18\t \x01(\tR\aoptions\x12\x16\n" +
	"\x06answer\x18\n" +
	" \x01(\tR\x06answer\x12\x1a\n" +
	"\banalysis\x18\v \x01(\tR\banalysis\"\xc1\x01\n" +
	"\x0fQuestionListReq\x12\x16\n" +
	"\x06pageNo\x18\x01 \x01(\x05R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x18\n" +
	"\acateId1\x18\x05 \x01(\x03R\acateId1\x12\x18\n" +
	"\acateId2\x18\x06 \x01(\x03R\acateId2\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\x05R\n" +
	"difficulty\"O\n" +
	"\x11QuestionListReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12$\n" +
	"\x04list\x18\x02 \x03(\v2\x10.exam.QuestionVOR\x04list\"F\n" +
	"\x0eQuestionBizReq\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\x03R\x05bizId\x12\x1e\n" +
	"\n" +
	"questionId\x18\x02 \x01(\x03R\n" +
	"questionId\"^\n" +
	"\x12QuestionBizListReq\x12\x14\n" +
	"\x05bizId\x18\x01 \x01(\x03R\x05bizId\x12\x16\n" +
	"\x06pageNo\x18\x02 \x01(\x05R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize2\x8e\x03\n" +
	"\x04Exam\x124\n" +
	"\fSaveQuestion\x12\x15.exam.QuestionSaveReq\x1a\r.exam.IdReply\x12*\n" +
	"\x0eDeleteQuestion\x12\v.exam.IdReq\x1a\v.exam.Empty\x12,\n" +
	"\vGetQuestion\x12\v.exam.IdReq\x1a\x10.exam.QuestionVO\x12?\n" +
	"\rListQuestions\x12\x15.exam.QuestionListReq\x1a\x17.exam.QuestionListReply\x125\n" +
	"\x0eAddQuestionBiz\x12\x14.exam.QuestionBizReq\x1a\r.exam.IdReply\x126\n" +
	"\x11RemoveQuestionBiz\x12\x14.exam.QuestionBizReq\x1a\v.exam.Empty\x12F\n" +
	"\x11GetQuestionsByBiz\x12\x18.exam.QuestionBizListReq\x1a\x17.exam.QuestionListReplyB\x06Z\x04./pbb\x06proto3"

var (
	file_exam_proto_rawDescOnce sync.Once
	file_exam_proto_rawDescData []byte
)

func file_exam_proto_rawDescGZIP() []byte {
	file_exam_proto_rawDescOnce.Do(func() {
		file_exam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exam_proto_rawDesc), len(file_exam_proto_rawDesc)))
	})
	return file_exam_proto_rawDescData
}

var file_exam_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_exam_proto_goTypes = []any{
	(*Empty)(nil),              // 0: exam.Empty
	(*IdReq)(nil),              // 1: exam.IdReq
	(*IdReply)(nil),            // 2: exam.IdReply
	(*PageReq)(nil),            // 3: exam.PageReq
	(*QuestionVO)(nil),         // 4: exam.QuestionVO
	(*QuestionSaveReq)(nil),    // 5: exam.QuestionSaveReq
	(*QuestionListReq)(nil),    // 6: exam.QuestionListReq
	(*QuestionListReply)(nil),  // 7: exam.QuestionListReply
	(*QuestionBizReq)(nil),     // 8: exam.QuestionBizReq
	(*QuestionBizListReq)(nil), // 9: exam.QuestionBizListReq
}
var file_exam_proto_depIdxs = []int32{
	4, // 0: exam.QuestionListReply.list:type_name -> exam.QuestionVO
	5, // 1: exam.Exam.SaveQuestion:input_type -> exam.QuestionSaveReq
	1, // 2: exam.Exam.DeleteQuestion:input_type -> exam.IdReq
	1, // 3: exam.Exam.GetQuestion:input_type -> exam.IdReq
	6, // 4: exam.Exam.ListQuestions:input_type -> exam.QuestionListReq
	8, // 5: exam.Exam.AddQuestionBiz:input_type -> exam.QuestionBizReq
	8, // 6: exam.Exam.RemoveQuestionBiz:input_type -> exam.QuestionBizReq
	9, // 7: exam.Exam.GetQuestionsByBiz:input_type -> exam.QuestionBizListReq
	2, // 8: exam.Exam.SaveQuestion:output_type -> exam.IdReply
	0, // 9: exam.Exam.DeleteQuestion:output_type -> exam.Empty
	4, // 10: exam.Exam.GetQuestion:output_type -> exam.QuestionVO
	7, // 11: exam.Exam.ListQuestions:output_type -> exam.QuestionListReply
	2, // 12: exam.Exam.AddQuestionBiz:output_type -> exam.IdReply
	0, // 13: exam.Exam.RemoveQuestionBiz:output_type -> exam.Empty
	7, // 14: exam.Exam.GetQuestionsByBiz:output_type -> exam.QuestionListReply
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exam_proto_init() }
func file_exam_proto_init() {
	if File_exam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exam_proto_rawDesc), len(file_exam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exam_proto_goTypes,
		DependencyIndexes: file_exam_proto_depIdxs,
		MessageInfos:      file_exam_proto_msgTypes,
	}.Build()
	File_exam_proto = out.File
	file_exam_proto_goTypes = nil
	file_exam_proto_depIdxs = nil
}
