// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"trade/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			// 购物车
			{
				Method:  http.MethodGet,
				Path:    "/carts",
				Handler: CartListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/carts",
				Handler: CartAddHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/carts",
				Handler: CartDeleteHandler(serverCtx),
			},
			// 订单
			{
				Method:  http.MethodGet,
				Path:    "/orders/prePlaceOrder",
				Handler: PrePlaceOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/placeOrder",
				Handler: PlaceOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/freeCourse/:courseId",
				Handler: FreeCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/page",
				Handler: OrderPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/:id",
				Handler: OrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/orders/:id",
				Handler: DeleteOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/orders/:id/cancel",
				Handler: CancelOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders/:id/status",
				Handler: OrderStatusHandler(serverCtx),
			},
			// 订单明细
			{
				Method:  http.MethodGet,
				Path:    "/order-details/course/:id",
				Handler: OrderDetailCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order-details/enrollCourse",
				Handler: EnrollCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order-details/enrollNum",
				Handler: EnrollNumHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order-details/page",
				Handler: OrderDetailPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order-details/purchaseInfo",
				Handler: PurchaseInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order-details/:id",
				Handler: OrderDetailGetHandler(serverCtx),
			},
			// 支付
			{
				Method:  http.MethodGet,
				Path:    "/pay/channels",
				Handler: PayChannelsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pay/order",
				Handler: PayOrderHandler(serverCtx),
			},
			// 退款
			{
				Method:  http.MethodPost,
				Path:    "/refund-apply",
				Handler: RefundApplyCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/refund-apply/approval",
				Handler: RefundApplyApproveHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/refund-apply/cancel",
				Handler: RefundApplyCancelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/refund-apply/detail/:id",
				Handler: RefundApplyDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/refund-apply/next",
				Handler: RefundApplyNextHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/refund-apply/page",
				Handler: RefundApplyPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/refund-apply/:id",
				Handler: RefundApplyGetHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
