// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: pay.proto

package server

import (
	"context"

	"tjxt/apps/pay/rpc/internal/logic"
	"tjxt/apps/pay/rpc/internal/svc"
	"tjxt/apps/pay/rpc/pb"
)

type PayServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPayServer
}

func NewPayServer(svcCtx *svc.ServiceContext) *PayServer {
	return &PayServer{
		svcCtx: svcCtx,
	}
}

// ===== 支付渠道 =====
func (s *PayServer) ListPayChannels(ctx context.Context, in *pb.ListPayChannelsRequest) (*pb.ListPayChannelsResponse, error) {
	l := logic.NewListPayChannelsLogic(ctx, s.svcCtx)
	return l.ListPayChannels(in)
}

func (s *PayServer) AddPayChannel(ctx context.Context, in *pb.PayChannelRequest) (*pb.PayChannelIdResponse, error) {
	l := logic.NewAddPayChannelLogic(ctx, s.svcCtx)
	return l.AddPayChannel(in)
}

func (s *PayServer) UpdatePayChannel(ctx context.Context, in *pb.PayChannelRequest) (*pb.EmptyResponse, error) {
	l := logic.NewUpdatePayChannelLogic(ctx, s.svcCtx)
	return l.UpdatePayChannel(in)
}

func (s *PayServer) UpdatePayChannelStatus(ctx context.Context, in *pb.UpdatePayChannelStatusRequest) (*pb.EmptyResponse, error) {
	l := logic.NewUpdatePayChannelStatusLogic(ctx, s.svcCtx)
	return l.UpdatePayChannelStatus(in)
}

func (s *PayServer) QueryPayChannelByCode(ctx context.Context, in *pb.QueryPayChannelByCodeRequest) (*pb.PayChannelResponse, error) {
	l := logic.NewQueryPayChannelByCodeLogic(ctx, s.svcCtx)
	return l.QueryPayChannelByCode(in)
}

func (s *PayServer) PageQueryPayChannels(ctx context.Context, in *pb.PageQueryPayChannelsRequest) (*pb.PageQueryPayChannelsResponse, error) {
	l := logic.NewPageQueryPayChannelsLogic(ctx, s.svcCtx)
	return l.PageQueryPayChannels(in)
}

// ===== 支付订单 =====
func (s *PayServer) ApplyPayOrder(ctx context.Context, in *pb.ApplyPayOrderRequest) (*pb.ApplyPayOrderResponse, error) {
	l := logic.NewApplyPayOrderLogic(ctx, s.svcCtx)
	return l.ApplyPayOrder(in)
}

func (s *PayServer) QueryPayResult(ctx context.Context, in *pb.QueryPayResultRequest) (*pb.PayResultResponse, error) {
	l := logic.NewQueryPayResultLogic(ctx, s.svcCtx)
	return l.QueryPayResult(in)
}

func (s *PayServer) NotifyPaySuccess(ctx context.Context, in *pb.NotifyPaySuccessRequest) (*pb.EmptyResponse, error) {
	l := logic.NewNotifyPaySuccessLogic(ctx, s.svcCtx)
	return l.NotifyPaySuccess(in)
}

func (s *PayServer) NotifyPayFailed(ctx context.Context, in *pb.NotifyPayFailedRequest) (*pb.EmptyResponse, error) {
	l := logic.NewNotifyPayFailedLogic(ctx, s.svcCtx)
	return l.NotifyPayFailed(in)
}

func (s *PayServer) ClosePayOrder(ctx context.Context, in *pb.ClosePayOrderRequest) (*pb.EmptyResponse, error) {
	l := logic.NewClosePayOrderLogic(ctx, s.svcCtx)
	return l.ClosePayOrder(in)
}

func (s *PayServer) QueryPayOrderByBizOrderNo(ctx context.Context, in *pb.QueryPayOrderRequest) (*pb.PayOrderResponse, error) {
	l := logic.NewQueryPayOrderByBizOrderNoLogic(ctx, s.svcCtx)
	return l.QueryPayOrderByBizOrderNo(in)
}

// ===== 退款订单 =====
func (s *PayServer) ApplyRefund(ctx context.Context, in *pb.ApplyRefundRequest) (*pb.RefundResultResponse, error) {
	l := logic.NewApplyRefundLogic(ctx, s.svcCtx)
	return l.ApplyRefund(in)
}

func (s *PayServer) QueryRefundResult(ctx context.Context, in *pb.QueryRefundResultRequest) (*pb.RefundResultResponse, error) {
	l := logic.NewQueryRefundResultLogic(ctx, s.svcCtx)
	return l.QueryRefundResult(in)
}

func (s *PayServer) NotifyRefundSuccess(ctx context.Context, in *pb.NotifyRefundSuccessRequest) (*pb.EmptyResponse, error) {
	l := logic.NewNotifyRefundSuccessLogic(ctx, s.svcCtx)
	return l.NotifyRefundSuccess(in)
}

func (s *PayServer) NotifyRefundFailed(ctx context.Context, in *pb.NotifyRefundFailedRequest) (*pb.EmptyResponse, error) {
	l := logic.NewNotifyRefundFailedLogic(ctx, s.svcCtx)
	return l.NotifyRefundFailed(in)
}

func (s *PayServer) QueryRefundByBizRefundNo(ctx context.Context, in *pb.QueryRefundRequest) (*pb.RefundOrderResponse, error) {
	l := logic.NewQueryRefundByBizRefundNoLogic(ctx, s.svcCtx)
	return l.QueryRefundByBizRefundNo(in)
}
