// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	like "tjxt/apps/remark/api/internal/handler/like"
	"tjxt/apps/remark/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/likes",
				Handler: like.LikeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/likes/list",
				Handler: like.ListLikedHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
