// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseFieldNames          = builder.RawFieldNames(&Course{})
	courseRows                = strings.Join(courseFieldNames, ",")
	courseRowsExpectAutoSet   = strings.Join(stringx.Remove(courseFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseRowsWithPlaceHolder = strings.Join(stringx.Remove(courseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCourseIdPrefix = "cache:course:id:"
)

type (
	courseModel interface {
		Insert(ctx context.Context, data *Course) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Course, error)
		Update(ctx context.Context, data *Course) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseModel struct {
		sqlc.CachedConn
		table string
	}

	Course struct {
		Id                int64         `db:"id"`                  // 课程草稿id，对应正式草稿id
		Name              string        `db:"name"`                // 课程名称
		CourseType        int64         `db:"course_type"`         // 课程类型，1：直播课，2：录播课
		CoverUrl          string        `db:"cover_url"`           // 封面链接
		FirstCateId       int64         `db:"first_cate_id"`       // 一级课程分类id
		SecondCateId      int64         `db:"second_cate_id"`      // 二级课程分类id
		ThirdCateId       int64         `db:"third_cate_id"`       // 三级课程分类id
		Free              int64         `db:"free"`                // 售卖方式0付费，1：免费
		Price             int64         `db:"price"`               // 课程价格，单位为分
		TemplateType      int64         `db:"template_type"`       // 模板类型，1：固定模板，2：自定义模板
		TemplateUrl       string        `db:"template_url"`        // 自定义模板的连接
		Status            int64         `db:"status"`              // 课程状态，1：待上架，2：已上架，3：下架，4：已完结
		PurchaseStartTime sql.NullTime  `db:"purchase_start_time"` // 课程购买有效期开始时间
		PurchaseEndTime   time.Time     `db:"purchase_end_time"`   // 课程购买有效期结束时间
		Step              int64         `db:"step"`                // 信息填写进度
		Score             int64         `db:"score"`               // 课程评价得分，45代表4.5星
		MediaDuration     sql.NullInt64 `db:"media_duration"`      // 课程总时长
		ValidDuration     int64         `db:"valid_duration"`      // 课程有效期，单位月
		SectionNum        sql.NullInt64 `db:"section_num"`         // 课程总节数，包括练习
		DepId             int64         `db:"dep_id"`              // 部门id
		PublishTimes      int64         `db:"publish_times"`       // 发布次数
		PublishTime       sql.NullTime  `db:"publish_time"`        // 最近一次发布时间
		CreateTime        time.Time     `db:"create_time"`         // 创建时间
		UpdateTime        time.Time     `db:"update_time"`         // 更新时间
		Creater           int64         `db:"creater"`             // 创建人
		Updater           int64         `db:"updater"`             // 更新人
		Deleted           int64         `db:"deleted"`             // 逻辑删除
	}
)

func newCourseModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseModel {
	return &defaultCourseModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course`",
	}
}

func (m *defaultCourseModel) Delete(ctx context.Context, id int64) error {
	courseIdKey := fmt.Sprintf("%s%v", cacheCourseIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, courseIdKey)
	return err
}

func (m *defaultCourseModel) FindOne(ctx context.Context, id int64) (*Course, error) {
	courseIdKey := fmt.Sprintf("%s%v", cacheCourseIdPrefix, id)
	var resp Course
	err := m.QueryRowCtx(ctx, &resp, courseIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseModel) Insert(ctx context.Context, data *Course) (sql.Result, error) {
	courseIdKey := fmt.Sprintf("%s%v", cacheCourseIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, courseRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Name, data.CourseType, data.CoverUrl, data.FirstCateId, data.SecondCateId, data.ThirdCateId, data.Free, data.Price, data.TemplateType, data.TemplateUrl, data.Status, data.PurchaseStartTime, data.PurchaseEndTime, data.Step, data.Score, data.MediaDuration, data.ValidDuration, data.SectionNum, data.DepId, data.PublishTimes, data.PublishTime, data.Creater, data.Updater, data.Deleted)
	}, courseIdKey)
	return ret, err
}

func (m *defaultCourseModel) Update(ctx context.Context, data *Course) error {
	courseIdKey := fmt.Sprintf("%s%v", cacheCourseIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.CourseType, data.CoverUrl, data.FirstCateId, data.SecondCateId, data.ThirdCateId, data.Free, data.Price, data.TemplateType, data.TemplateUrl, data.Status, data.PurchaseStartTime, data.PurchaseEndTime, data.Step, data.Score, data.MediaDuration, data.ValidDuration, data.SectionNum, data.DepId, data.PublishTimes, data.PublishTime, data.Creater, data.Updater, data.Deleted, data.Id)
	}, courseIdKey)
	return err
}

func (m *defaultCourseModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCourseIdPrefix, primary)
}

func (m *defaultCourseModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseModel) tableName() string {
	return m.table
}
