// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseContentFieldNames          = builder.RawFieldNames(&CourseContent{})
	courseContentRows                = strings.Join(courseContentFieldNames, ",")
	courseContentRowsExpectAutoSet   = strings.Join(stringx.Remove(courseContentFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseContentRowsWithPlaceHolder = strings.Join(stringx.Remove(courseContentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCourseContentIdPrefix = "cache:courseContent:id:"
)

type (
	courseContentModel interface {
		Insert(ctx context.Context, data *CourseContent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CourseContent, error)
		Update(ctx context.Context, data *CourseContent) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCourseContentModel struct {
		sqlc.CachedConn
		table string
	}

	CourseContent struct {
		Id              int64          `db:"id"`               // 课程内容id，对应课程id
		CourseIntroduce sql.NullString `db:"course_introduce"` // 课程简介
		CourseDetail    sql.NullString `db:"course_detail"`    // 课程详情
		UsePeople       sql.NullString `db:"use_people"`       // 适用人群
		CreateTime      time.Time      `db:"create_time"`      // 创建时间
		UpdateTime      time.Time      `db:"update_time"`      // 更新时间
		Creater         int64          `db:"creater"`          // 创建人
		Updater         int64          `db:"updater"`          // 更新人
	}
)

func newCourseContentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseContentModel {
	return &defaultCourseContentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course_content`",
	}
}

func (m *defaultCourseContentModel) Delete(ctx context.Context, id int64) error {
	courseContentIdKey := fmt.Sprintf("%s%v", cacheCourseContentIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, courseContentIdKey)
	return err
}

func (m *defaultCourseContentModel) FindOne(ctx context.Context, id int64) (*CourseContent, error) {
	courseContentIdKey := fmt.Sprintf("%s%v", cacheCourseContentIdPrefix, id)
	var resp CourseContent
	err := m.QueryRowCtx(ctx, &resp, courseContentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseContentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseContentModel) Insert(ctx context.Context, data *CourseContent) (sql.Result, error) {
	courseContentIdKey := fmt.Sprintf("%s%v", cacheCourseContentIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, courseContentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.CourseIntroduce, data.CourseDetail, data.UsePeople, data.Creater, data.Updater)
	}, courseContentIdKey)
	return ret, err
}

func (m *defaultCourseContentModel) Update(ctx context.Context, data *CourseContent) error {
	courseContentIdKey := fmt.Sprintf("%s%v", cacheCourseContentIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseContentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CourseIntroduce, data.CourseDetail, data.UsePeople, data.Creater, data.Updater, data.Id)
	}, courseContentIdKey)
	return err
}

func (m *defaultCourseContentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCourseContentIdPrefix, primary)
}

func (m *defaultCourseContentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseContentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseContentModel) tableName() string {
	return m.table
}
