// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userDetailFieldNames          = builder.RawFieldNames(&UserDetail{})
	userDetailRows                = strings.Join(userDetailFieldNames, ",")
	userDetailRowsExpectAutoSet   = strings.Join(stringx.Remove(userDetailFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userDetailRowsWithPlaceHolder = strings.Join(stringx.Remove(userDetailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserDetailIdPrefix = "cache:userDetail:id:"
)

type (
	userDetailModel interface {
		Insert(ctx context.Context, data *UserDetail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserDetail, error)
		Update(ctx context.Context, data *UserDetail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserDetailModel struct {
		sqlc.CachedConn
		table string
	}

	UserDetail struct {
		Id           int64          `db:"id"`            // 关联用户id
		Type         int64          `db:"type"`          // 用户类型：1-员工, 2-普通学员，3-老师
		Name         string         `db:"name"`          // 名字
		Gender       int64          `db:"gender"`        // 性别：0-男性，1-女性
		Icon         sql.NullString `db:"icon"`          // 头像地址
		Email        sql.NullString `db:"email"`         // 邮箱
		Qq           sql.NullString `db:"qq"`            // QQ号码
		Birthday     sql.NullTime   `db:"birthday"`      // 生日
		Job          sql.NullString `db:"job"`           // 岗位
		Province     sql.NullString `db:"province"`      // 省
		City         sql.NullString `db:"city"`          // 市
		District     sql.NullString `db:"district"`      // 区
		Intro        sql.NullString `db:"intro"`         // 个人介绍
		Photo        sql.NullString `db:"photo"`         // 形象照地址
		RoleId       int64          `db:"role_id"`       // 角色id
		CourseAmount int64          `db:"course_amount"` // 购买课程数量，学生才有该字段信息
		CreateTime   time.Time      `db:"create_time"`   // 创建时间
		UpdateTime   time.Time      `db:"update_time"`   // 更新时间
		Creater      sql.NullInt64  `db:"creater"`       // 创建者id
		Updater      int64          `db:"updater"`       // 更新者id
		DepId        int64          `db:"dep_id"`        // 部门id
	}
)

func newUserDetailModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserDetailModel {
	return &defaultUserDetailModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_detail`",
	}
}

func (m *defaultUserDetailModel) Delete(ctx context.Context, id int64) error {
	userDetailIdKey := fmt.Sprintf("%s%v", cacheUserDetailIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userDetailIdKey)
	return err
}

func (m *defaultUserDetailModel) FindOne(ctx context.Context, id int64) (*UserDetail, error) {
	userDetailIdKey := fmt.Sprintf("%s%v", cacheUserDetailIdPrefix, id)
	var resp UserDetail
	err := m.QueryRowCtx(ctx, &resp, userDetailIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userDetailRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserDetailModel) Insert(ctx context.Context, data *UserDetail) (sql.Result, error) {
	userDetailIdKey := fmt.Sprintf("%s%v", cacheUserDetailIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userDetailRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Type, data.Name, data.Gender, data.Icon, data.Email, data.Qq, data.Birthday, data.Job, data.Province, data.City, data.District, data.Intro, data.Photo, data.RoleId, data.CourseAmount, data.Creater, data.Updater, data.DepId)
	}, userDetailIdKey)
	return ret, err
}

func (m *defaultUserDetailModel) Update(ctx context.Context, data *UserDetail) error {
	userDetailIdKey := fmt.Sprintf("%s%v", cacheUserDetailIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userDetailRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Type, data.Name, data.Gender, data.Icon, data.Email, data.Qq, data.Birthday, data.Job, data.Province, data.City, data.District, data.Intro, data.Photo, data.RoleId, data.CourseAmount, data.Creater, data.Updater, data.DepId, data.Id)
	}, userDetailIdKey)
	return err
}

func (m *defaultUserDetailModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserDetailIdPrefix, primary)
}

func (m *defaultUserDetailModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userDetailRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserDetailModel) tableName() string {
	return m.table
}
