// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: auth.proto

package server

import (
	"context"

	"tjxt/apps/auth/rpc/internal/logic/auth"
	"tjxt/apps/auth/rpc/internal/svc"
	"tjxt/apps/auth/rpc/pb"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

// 角色
func (s *AuthServer) SaveRole(ctx context.Context, in *pb.RoleSaveReq) (*pb.IdReply, error) {
	l := authlogic.NewSaveRoleLogic(ctx, s.svcCtx)
	return l.SaveRole(in)
}

func (s *AuthServer) DeleteRole(ctx context.Context, in *pb.IdReq) (*pb.Empty, error) {
	l := authlogic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

func (s *AuthServer) GetRole(ctx context.Context, in *pb.IdReq) (*pb.RoleVO, error) {
	l := authlogic.NewGetRoleLogic(ctx, s.svcCtx)
	return l.GetRole(in)
}

func (s *AuthServer) ListRoles(ctx context.Context, in *pb.PageReq) (*pb.RoleListReply, error) {
	l := authlogic.NewListRolesLogic(ctx, s.svcCtx)
	return l.ListRoles(in)
}

// 菜单
func (s *AuthServer) GetMenuTree(ctx context.Context, in *pb.Empty) (*pb.MenuTreeReply, error) {
	l := authlogic.NewGetMenuTreeLogic(ctx, s.svcCtx)
	return l.GetMenuTree(in)
}

func (s *AuthServer) SaveMenu(ctx context.Context, in *pb.MenuSaveReq) (*pb.IdReply, error) {
	l := authlogic.NewSaveMenuLogic(ctx, s.svcCtx)
	return l.SaveMenu(in)
}

func (s *AuthServer) DeleteMenu(ctx context.Context, in *pb.IdReq) (*pb.Empty, error) {
	l := authlogic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

// 权限
func (s *AuthServer) GetPrivilegesByMenu(ctx context.Context, in *pb.IdReq) (*pb.PrivilegeListReply, error) {
	l := authlogic.NewGetPrivilegesByMenuLogic(ctx, s.svcCtx)
	return l.GetPrivilegesByMenu(in)
}

func (s *AuthServer) SavePrivilege(ctx context.Context, in *pb.PrivilegeSaveReq) (*pb.IdReply, error) {
	l := authlogic.NewSavePrivilegeLogic(ctx, s.svcCtx)
	return l.SavePrivilege(in)
}

func (s *AuthServer) DeletePrivilege(ctx context.Context, in *pb.IdReq) (*pb.Empty, error) {
	l := authlogic.NewDeletePrivilegeLogic(ctx, s.svcCtx)
	return l.DeletePrivilege(in)
}

// 角色菜单/权限分配
func (s *AuthServer) SaveRoleMenus(ctx context.Context, in *pb.RoleMenuReq) (*pb.Empty, error) {
	l := authlogic.NewSaveRoleMenusLogic(ctx, s.svcCtx)
	return l.SaveRoleMenus(in)
}

func (s *AuthServer) SaveRolePrivileges(ctx context.Context, in *pb.RolePrivilegeReq) (*pb.Empty, error) {
	l := authlogic.NewSaveRolePrivilegesLogic(ctx, s.svcCtx)
	return l.SaveRolePrivileges(in)
}

func (s *AuthServer) GetRoleMenus(ctx context.Context, in *pb.IdReq) (*pb.IdListReply, error) {
	l := authlogic.NewGetRoleMenusLogic(ctx, s.svcCtx)
	return l.GetRoleMenus(in)
}

func (s *AuthServer) GetRolePrivileges(ctx context.Context, in *pb.IdReq) (*pb.IdListReply, error) {
	l := authlogic.NewGetRolePrivilegesLogic(ctx, s.svcCtx)
	return l.GetRolePrivileges(in)
}

// 账户角色
func (s *AuthServer) SaveAccountRoles(ctx context.Context, in *pb.AccountRoleReq) (*pb.Empty, error) {
	l := authlogic.NewSaveAccountRolesLogic(ctx, s.svcCtx)
	return l.SaveAccountRoles(in)
}

func (s *AuthServer) GetAccountRoles(ctx context.Context, in *pb.IdReq) (*pb.IdListReply, error) {
	l := authlogic.NewGetAccountRolesLogic(ctx, s.svcCtx)
	return l.GetAccountRoles(in)
}

// 登录记录
func (s *AuthServer) SaveLoginRecord(ctx context.Context, in *pb.LoginRecordReq) (*pb.Empty, error) {
	l := authlogic.NewSaveLoginRecordLogic(ctx, s.svcCtx)
	return l.SaveLoginRecord(in)
}

func (s *AuthServer) ListLoginRecords(ctx context.Context, in *pb.LoginRecordPageReq) (*pb.LoginRecordListReply, error) {
	l := authlogic.NewListLoginRecordsLogic(ctx, s.svcCtx)
	return l.ListLoginRecords(in)
}

// 令牌签发
func (s *AuthServer) SignToken(ctx context.Context, in *pb.SignTokenReq) (*pb.SignTokenReply, error) {
	l := authlogic.NewSignTokenLogic(ctx, s.svcCtx)
	return l.SignToken(in)
}
