// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: course.proto

package course

import (
	"context"

	"tjxt/apps/course/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CataSimple                   = pb.CataSimple
	CataSimpleList               = pb.CataSimpleList
	CataSubjectInfoList          = pb.CataSubjectInfoList
	CatalogSubjectBind           = pb.CatalogSubjectBind
	CatalogSubjectInfo           = pb.CatalogSubjectInfo
	CatalogueTreeList            = pb.CatalogueTreeList
	CategoryAddRequest           = pb.CategoryAddRequest
	CategoryInfo                 = pb.CategoryInfo
	CategoryList                 = pb.CategoryList
	CategoryListAllRequest       = pb.CategoryListAllRequest
	CategoryListQueryRequest     = pb.CategoryListQueryRequest
	CategoryNode                 = pb.CategoryNode
	CategoryNodeList             = pb.CategoryNodeList
	CategoryStatusRequest        = pb.CategoryStatusRequest
	CategoryUpdateRequest        = pb.CategoryUpdateRequest
	CourseAndSectionView         = pb.CourseAndSectionView
	CourseBaseInfoSaveRequest    = pb.CourseBaseInfoSaveRequest
	CourseBaseInfoView           = pb.CourseBaseInfoView
	CourseCatalogueQueryRequest  = pb.CourseCatalogueQueryRequest
	CourseCatalogueSaveRequest   = pb.CourseCatalogueSaveRequest
	CourseChapterInfo            = pb.CourseChapterInfo
	CourseChapterSave            = pb.CourseChapterSave
	CourseCheckNameRequest       = pb.CourseCheckNameRequest
	CourseFullInfo               = pb.CourseFullInfo
	CourseFullInfoGetRequest     = pb.CourseFullInfoGetRequest
	CourseIdList                 = pb.CourseIdList
	CourseMediaBind              = pb.CourseMediaBind
	CourseMediaSaveRequest       = pb.CourseMediaSaveRequest
	CourseNameRequest            = pb.CourseNameRequest
	CoursePageItem               = pb.CoursePageItem
	CoursePageQueryReply         = pb.CoursePageQueryReply
	CoursePageQueryRequest       = pb.CoursePageQueryRequest
	CoursePortalQueryRequest     = pb.CoursePortalQueryRequest
	CourseSearchIndexInfo        = pb.CourseSearchIndexInfo
	CourseSectionInfo            = pb.CourseSectionInfo
	CourseSimpleInfoItem         = pb.CourseSimpleInfoItem
	CourseSimpleInfoListReply    = pb.CourseSimpleInfoListReply
	CourseSimpleInfoQueryRequest = pb.CourseSimpleInfoQueryRequest
	CourseSubjectsSaveRequest    = pb.CourseSubjectsSaveRequest
	CourseTeachersGetRequest     = pb.CourseTeachersGetRequest
	CourseTeachersSaveRequest    = pb.CourseTeachersSaveRequest
	Empty                        = pb.Empty
	IdRequest                    = pb.IdRequest
	IdResponse                   = pb.IdResponse
	IdsRequest                   = pb.IdsRequest
	MediaIdsRequest              = pb.MediaIdsRequest
	MediaQuote                   = pb.MediaQuote
	MediaQuoteList               = pb.MediaQuoteList
	NameExistReply               = pb.NameExistReply
	SubjectInfo                  = pb.SubjectInfo
	TeacherCourseCount           = pb.TeacherCourseCount
	TeacherCourseCountList       = pb.TeacherCourseCountList
	TeacherIdsRequest            = pb.TeacherIdsRequest
	TeacherInfo                  = pb.TeacherInfo
	TeacherInfoList              = pb.TeacherInfoList
	TeacherShowBind              = pb.TeacherShowBind

	Course interface {
		// ===== 分类管理 =====
		CategoryAdd(ctx context.Context, in *CategoryAddRequest, opts ...grpc.CallOption) (*Empty, error)
		CategoryUpdate(ctx context.Context, in *CategoryUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		CategoryDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
		CategoryDisableOrEnable(ctx context.Context, in *CategoryStatusRequest, opts ...grpc.CallOption) (*Empty, error)
		CategoryGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CategoryInfo, error)
		CategoryListAll(ctx context.Context, in *CategoryListAllRequest, opts ...grpc.CallOption) (*CategoryNodeList, error)
		CategoryListOneLevel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CategoryList, error)
		CategoryListQuery(ctx context.Context, in *CategoryListQueryRequest, opts ...grpc.CallOption) (*CategoryList, error)
		// ===== 课程基础信息 =====
		CourseBaseInfoGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CourseBaseInfoView, error)
		CourseBaseInfoSave(ctx context.Context, in *CourseBaseInfoSaveRequest, opts ...grpc.CallOption) (*IdResponse, error)
		CourseCheckName(ctx context.Context, in *CourseCheckNameRequest, opts ...grpc.CallOption) (*NameExistReply, error)
		CourseDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
		CoursePageQuery(ctx context.Context, in *CoursePageQueryRequest, opts ...grpc.CallOption) (*CoursePageQueryReply, error)
		CoursePortalQuery(ctx context.Context, in *CoursePortalQueryRequest, opts ...grpc.CallOption) (*CoursePageQueryReply, error)
		CourseSimpleInfoList(ctx context.Context, in *CourseSimpleInfoQueryRequest, opts ...grpc.CallOption) (*CourseSimpleInfoListReply, error)
		CourseFullInfoGet(ctx context.Context, in *CourseFullInfoGetRequest, opts ...grpc.CallOption) (*CourseFullInfo, error)
		CourseSearchInfoForIndex(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CourseSearchIndexInfo, error)
		CourseName2Ids(ctx context.Context, in *CourseNameRequest, opts ...grpc.CallOption) (*CourseIdList, error)
		CourseInfoByTeacherIds(ctx context.Context, in *TeacherIdsRequest, opts ...grpc.CallOption) (*TeacherCourseCountList, error)
		CourseSectionGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CourseSectionInfo, error)
		CourseMediaUseInfo(ctx context.Context, in *MediaIdsRequest, opts ...grpc.CallOption) (*MediaQuoteList, error)
		CourseGenerator(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdResponse, error)
		// ===== 课程目录 (catalogue) =====
		CourseCatalogsGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CourseAndSectionView, error)
		CourseCatalogueTreeGet(ctx context.Context, in *CourseCatalogueQueryRequest, opts ...grpc.CallOption) (*CatalogueTreeList, error)
		CourseCatalogueSave(ctx context.Context, in *CourseCatalogueSaveRequest, opts ...grpc.CallOption) (*Empty, error)
		CourseCatalogueIndexList(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CataSimpleList, error)
		CourseCatalogueSectionInfo(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CourseSectionInfo, error)
		CourseCatalogueBatchQuery(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*CataSimpleList, error)
		// ===== 章节/小节的题目 =====
		CourseSubjectsGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CataSubjectInfoList, error)
		CourseSubjectsSave(ctx context.Context, in *CourseSubjectsSaveRequest, opts ...grpc.CallOption) (*Empty, error)
		// ===== 课程媒体 =====
		CourseMediaSave(ctx context.Context, in *CourseMediaSaveRequest, opts ...grpc.CallOption) (*Empty, error)
		// ===== 课程老师 =====
		CourseTeachersGet(ctx context.Context, in *CourseTeachersGetRequest, opts ...grpc.CallOption) (*TeacherInfoList, error)
		CourseTeachersSave(ctx context.Context, in *CourseTeachersSaveRequest, opts ...grpc.CallOption) (*Empty, error)
		// ===== 上下架 =====
		CourseUpShelf(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
		CourseDownShelf(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
		CourseCheckUpShelf(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
		CourseUp(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error)
		CourseDown(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultCourse struct {
		cli zrpc.Client
	}
)

func NewCourse(cli zrpc.Client) Course {
	return &defaultCourse{
		cli: cli,
	}
}

// ===== 分类管理 =====
func (m *defaultCourse) CategoryAdd(ctx context.Context, in *CategoryAddRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CategoryAdd(ctx, in, opts...)
}

func (m *defaultCourse) CategoryUpdate(ctx context.Context, in *CategoryUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CategoryUpdate(ctx, in, opts...)
}

func (m *defaultCourse) CategoryDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CategoryDelete(ctx, in, opts...)
}

func (m *defaultCourse) CategoryDisableOrEnable(ctx context.Context, in *CategoryStatusRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CategoryDisableOrEnable(ctx, in, opts...)
}

func (m *defaultCourse) CategoryGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CategoryInfo, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CategoryGet(ctx, in, opts...)
}

func (m *defaultCourse) CategoryListAll(ctx context.Context, in *CategoryListAllRequest, opts ...grpc.CallOption) (*CategoryNodeList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CategoryListAll(ctx, in, opts...)
}

func (m *defaultCourse) CategoryListOneLevel(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CategoryList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CategoryListOneLevel(ctx, in, opts...)
}

func (m *defaultCourse) CategoryListQuery(ctx context.Context, in *CategoryListQueryRequest, opts ...grpc.CallOption) (*CategoryList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CategoryListQuery(ctx, in, opts...)
}

// ===== 课程基础信息 =====
func (m *defaultCourse) CourseBaseInfoGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CourseBaseInfoView, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseBaseInfoGet(ctx, in, opts...)
}

func (m *defaultCourse) CourseBaseInfoSave(ctx context.Context, in *CourseBaseInfoSaveRequest, opts ...grpc.CallOption) (*IdResponse, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseBaseInfoSave(ctx, in, opts...)
}

func (m *defaultCourse) CourseCheckName(ctx context.Context, in *CourseCheckNameRequest, opts ...grpc.CallOption) (*NameExistReply, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseCheckName(ctx, in, opts...)
}

func (m *defaultCourse) CourseDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseDelete(ctx, in, opts...)
}

func (m *defaultCourse) CoursePageQuery(ctx context.Context, in *CoursePageQueryRequest, opts ...grpc.CallOption) (*CoursePageQueryReply, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CoursePageQuery(ctx, in, opts...)
}

func (m *defaultCourse) CoursePortalQuery(ctx context.Context, in *CoursePortalQueryRequest, opts ...grpc.CallOption) (*CoursePageQueryReply, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CoursePortalQuery(ctx, in, opts...)
}

func (m *defaultCourse) CourseSimpleInfoList(ctx context.Context, in *CourseSimpleInfoQueryRequest, opts ...grpc.CallOption) (*CourseSimpleInfoListReply, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseSimpleInfoList(ctx, in, opts...)
}

func (m *defaultCourse) CourseFullInfoGet(ctx context.Context, in *CourseFullInfoGetRequest, opts ...grpc.CallOption) (*CourseFullInfo, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseFullInfoGet(ctx, in, opts...)
}

func (m *defaultCourse) CourseSearchInfoForIndex(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CourseSearchIndexInfo, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseSearchInfoForIndex(ctx, in, opts...)
}

func (m *defaultCourse) CourseName2Ids(ctx context.Context, in *CourseNameRequest, opts ...grpc.CallOption) (*CourseIdList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseName2Ids(ctx, in, opts...)
}

func (m *defaultCourse) CourseInfoByTeacherIds(ctx context.Context, in *TeacherIdsRequest, opts ...grpc.CallOption) (*TeacherCourseCountList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseInfoByTeacherIds(ctx, in, opts...)
}

func (m *defaultCourse) CourseSectionGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CourseSectionInfo, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseSectionGet(ctx, in, opts...)
}

func (m *defaultCourse) CourseMediaUseInfo(ctx context.Context, in *MediaIdsRequest, opts ...grpc.CallOption) (*MediaQuoteList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseMediaUseInfo(ctx, in, opts...)
}

func (m *defaultCourse) CourseGenerator(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdResponse, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseGenerator(ctx, in, opts...)
}

// ===== 课程目录 (catalogue) =====
func (m *defaultCourse) CourseCatalogsGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CourseAndSectionView, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseCatalogsGet(ctx, in, opts...)
}

func (m *defaultCourse) CourseCatalogueTreeGet(ctx context.Context, in *CourseCatalogueQueryRequest, opts ...grpc.CallOption) (*CatalogueTreeList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseCatalogueTreeGet(ctx, in, opts...)
}

func (m *defaultCourse) CourseCatalogueSave(ctx context.Context, in *CourseCatalogueSaveRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseCatalogueSave(ctx, in, opts...)
}

func (m *defaultCourse) CourseCatalogueIndexList(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CataSimpleList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseCatalogueIndexList(ctx, in, opts...)
}

func (m *defaultCourse) CourseCatalogueSectionInfo(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CourseSectionInfo, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseCatalogueSectionInfo(ctx, in, opts...)
}

func (m *defaultCourse) CourseCatalogueBatchQuery(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*CataSimpleList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseCatalogueBatchQuery(ctx, in, opts...)
}

// ===== 章节/小节的题目 =====
func (m *defaultCourse) CourseSubjectsGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CataSubjectInfoList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseSubjectsGet(ctx, in, opts...)
}

func (m *defaultCourse) CourseSubjectsSave(ctx context.Context, in *CourseSubjectsSaveRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseSubjectsSave(ctx, in, opts...)
}

// ===== 课程媒体 =====
func (m *defaultCourse) CourseMediaSave(ctx context.Context, in *CourseMediaSaveRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseMediaSave(ctx, in, opts...)
}

// ===== 课程老师 =====
func (m *defaultCourse) CourseTeachersGet(ctx context.Context, in *CourseTeachersGetRequest, opts ...grpc.CallOption) (*TeacherInfoList, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseTeachersGet(ctx, in, opts...)
}

func (m *defaultCourse) CourseTeachersSave(ctx context.Context, in *CourseTeachersSaveRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseTeachersSave(ctx, in, opts...)
}

// ===== 上下架 =====
func (m *defaultCourse) CourseUpShelf(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseUpShelf(ctx, in, opts...)
}

func (m *defaultCourse) CourseDownShelf(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseDownShelf(ctx, in, opts...)
}

func (m *defaultCourse) CourseCheckUpShelf(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseCheckUpShelf(ctx, in, opts...)
}

func (m *defaultCourse) CourseUp(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseUp(ctx, in, opts...)
}

func (m *defaultCourse) CourseDown(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseDown(ctx, in, opts...)
}
