// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: data.proto

package data

import (
	"context"

	"tjxt/apps/data/rpc/data/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BoardDataReq    = pb.BoardDataReq
	BoardDataSetReq = pb.BoardDataSetReq
	EchartsVO       = pb.EchartsVO
	Empty           = pb.Empty
	OkReply         = pb.OkReply
	TodayDataSetReq = pb.TodayDataSetReq
	TodayDataVO     = pb.TodayDataVO
	Top10DataSetReq = pb.Top10DataSetReq
	Top10DataVO     = pb.Top10DataVO

	Data interface {
		GetBoardData(ctx context.Context, in *BoardDataReq, opts ...grpc.CallOption) (*EchartsVO, error)
		SetBoardData(ctx context.Context, in *BoardDataSetReq, opts ...grpc.CallOption) (*OkReply, error)
		GetTodayData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TodayDataVO, error)
		SetTodayData(ctx context.Context, in *TodayDataSetReq, opts ...grpc.CallOption) (*OkReply, error)
		GetTop10Data(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Top10DataVO, error)
		SetTop10Data(ctx context.Context, in *Top10DataSetReq, opts ...grpc.CallOption) (*OkReply, error)
	}

	defaultData struct {
		cli zrpc.Client
	}
)

func NewData(cli zrpc.Client) Data {
	return &defaultData{
		cli: cli,
	}
}

func (m *defaultData) GetBoardData(ctx context.Context, in *BoardDataReq, opts ...grpc.CallOption) (*EchartsVO, error) {
	client := pb.NewDataClient(m.cli.Conn())
	return client.GetBoardData(ctx, in, opts...)
}

func (m *defaultData) SetBoardData(ctx context.Context, in *BoardDataSetReq, opts ...grpc.CallOption) (*OkReply, error) {
	client := pb.NewDataClient(m.cli.Conn())
	return client.SetBoardData(ctx, in, opts...)
}

func (m *defaultData) GetTodayData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TodayDataVO, error) {
	client := pb.NewDataClient(m.cli.Conn())
	return client.GetTodayData(ctx, in, opts...)
}

func (m *defaultData) SetTodayData(ctx context.Context, in *TodayDataSetReq, opts ...grpc.CallOption) (*OkReply, error) {
	client := pb.NewDataClient(m.cli.Conn())
	return client.SetTodayData(ctx, in, opts...)
}

func (m *defaultData) GetTop10Data(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Top10DataVO, error) {
	client := pb.NewDataClient(m.cli.Conn())
	return client.GetTop10Data(ctx, in, opts...)
}

func (m *defaultData) SetTop10Data(ctx context.Context, in *Top10DataSetReq, opts ...grpc.CallOption) (*OkReply, error) {
	client := pb.NewDataClient(m.cli.Conn())
	return client.SetTop10Data(ctx, in, opts...)
}
