// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: auth.proto

package auth

import (
	"context"

	"tjxt/apps/auth/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountRoleReq       = pb.AccountRoleReq
	Empty                = pb.Empty
	IdListReply          = pb.IdListReply
	IdReply              = pb.IdReply
	IdReq                = pb.IdReq
	LoginRecordListReply = pb.LoginRecordListReply
	LoginRecordPageReq   = pb.LoginRecordPageReq
	LoginRecordReq       = pb.LoginRecordReq
	MenuSaveReq          = pb.MenuSaveReq
	MenuTreeReply        = pb.MenuTreeReply
	PageReq              = pb.PageReq
	PrivilegeListReply   = pb.PrivilegeListReply
	PrivilegeSaveReq     = pb.PrivilegeSaveReq
	RoleListReply        = pb.RoleListReply
	RoleMenuReq          = pb.RoleMenuReq
	RolePrivilegeReq     = pb.RolePrivilegeReq
	RoleSaveReq          = pb.RoleSaveReq
	RoleVO               = pb.RoleVO
	SignTokenReply       = pb.SignTokenReply
	SignTokenReq         = pb.SignTokenReq

	Auth interface {
		// 角色
		SaveRole(ctx context.Context, in *RoleSaveReq, opts ...grpc.CallOption) (*IdReply, error)
		DeleteRole(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
		GetRole(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*RoleVO, error)
		ListRoles(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*RoleListReply, error)
		// 菜单
		GetMenuTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuTreeReply, error)
		SaveMenu(ctx context.Context, in *MenuSaveReq, opts ...grpc.CallOption) (*IdReply, error)
		DeleteMenu(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
		// 权限
		GetPrivilegesByMenu(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*PrivilegeListReply, error)
		SavePrivilege(ctx context.Context, in *PrivilegeSaveReq, opts ...grpc.CallOption) (*IdReply, error)
		DeletePrivilege(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error)
		// 角色菜单/权限分配
		SaveRoleMenus(ctx context.Context, in *RoleMenuReq, opts ...grpc.CallOption) (*Empty, error)
		SaveRolePrivileges(ctx context.Context, in *RolePrivilegeReq, opts ...grpc.CallOption) (*Empty, error)
		GetRoleMenus(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IdListReply, error)
		GetRolePrivileges(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IdListReply, error)
		// 账户角色
		SaveAccountRoles(ctx context.Context, in *AccountRoleReq, opts ...grpc.CallOption) (*Empty, error)
		GetAccountRoles(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IdListReply, error)
		// 登录记录
		SaveLoginRecord(ctx context.Context, in *LoginRecordReq, opts ...grpc.CallOption) (*Empty, error)
		ListLoginRecords(ctx context.Context, in *LoginRecordPageReq, opts ...grpc.CallOption) (*LoginRecordListReply, error)
		// 令牌签发
		SignToken(ctx context.Context, in *SignTokenReq, opts ...grpc.CallOption) (*SignTokenReply, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

// 角色
func (m *defaultAuth) SaveRole(ctx context.Context, in *RoleSaveReq, opts ...grpc.CallOption) (*IdReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.SaveRole(ctx, in, opts...)
}

func (m *defaultAuth) DeleteRole(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultAuth) GetRole(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*RoleVO, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultAuth) ListRoles(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*RoleListReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.ListRoles(ctx, in, opts...)
}

// 菜单
func (m *defaultAuth) GetMenuTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuTreeReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.GetMenuTree(ctx, in, opts...)
}

func (m *defaultAuth) SaveMenu(ctx context.Context, in *MenuSaveReq, opts ...grpc.CallOption) (*IdReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.SaveMenu(ctx, in, opts...)
}

func (m *defaultAuth) DeleteMenu(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

// 权限
func (m *defaultAuth) GetPrivilegesByMenu(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*PrivilegeListReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.GetPrivilegesByMenu(ctx, in, opts...)
}

func (m *defaultAuth) SavePrivilege(ctx context.Context, in *PrivilegeSaveReq, opts ...grpc.CallOption) (*IdReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.SavePrivilege(ctx, in, opts...)
}

func (m *defaultAuth) DeletePrivilege(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.DeletePrivilege(ctx, in, opts...)
}

// 角色菜单/权限分配
func (m *defaultAuth) SaveRoleMenus(ctx context.Context, in *RoleMenuReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.SaveRoleMenus(ctx, in, opts...)
}

func (m *defaultAuth) SaveRolePrivileges(ctx context.Context, in *RolePrivilegeReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.SaveRolePrivileges(ctx, in, opts...)
}

func (m *defaultAuth) GetRoleMenus(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IdListReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.GetRoleMenus(ctx, in, opts...)
}

func (m *defaultAuth) GetRolePrivileges(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IdListReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.GetRolePrivileges(ctx, in, opts...)
}

// 账户角色
func (m *defaultAuth) SaveAccountRoles(ctx context.Context, in *AccountRoleReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.SaveAccountRoles(ctx, in, opts...)
}

func (m *defaultAuth) GetAccountRoles(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*IdListReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.GetAccountRoles(ctx, in, opts...)
}

// 登录记录
func (m *defaultAuth) SaveLoginRecord(ctx context.Context, in *LoginRecordReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.SaveLoginRecord(ctx, in, opts...)
}

func (m *defaultAuth) ListLoginRecords(ctx context.Context, in *LoginRecordPageReq, opts ...grpc.CallOption) (*LoginRecordListReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.ListLoginRecords(ctx, in, opts...)
}

// 令牌签发
func (m *defaultAuth) SignToken(ctx context.Context, in *SignTokenReq, opts ...grpc.CallOption) (*SignTokenReply, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.SignToken(ctx, in, opts...)
}
