// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: remark.proto

package remark

import (
	"context"

	"tjxt/apps/remark/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty     = pb.Empty
	LikeReq   = pb.LikeReq
	LikedReq  = pb.LikedReq
	LikedResp = pb.LikedResp

	Remark interface {
		Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*Empty, error)
		QueryLikedBizIds(ctx context.Context, in *LikedReq, opts ...grpc.CallOption) (*LikedResp, error)
	}

	defaultRemark struct {
		cli zrpc.Client
	}
)

func NewRemark(cli zrpc.Client) Remark {
	return &defaultRemark{
		cli: cli,
	}
}

func (m *defaultRemark) Like(ctx context.Context, in *LikeReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewRemarkClient(m.cli.Conn())
	return client.Like(ctx, in, opts...)
}

func (m *defaultRemark) QueryLikedBizIds(ctx context.Context, in *LikedReq, opts ...grpc.CallOption) (*LikedResp, error) {
	client := pb.NewRemarkClient(m.cli.Conn())
	return client.QueryLikedBizIds(ctx, in, opts...)
}
