// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: promotion.proto

package promotion

import (
	"context"

	"tjxt/apps/promotion/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CouponCodePageReply     = pb.CouponCodePageReply
	CouponCodePageRequest   = pb.CouponCodePageRequest
	CouponDetailVO          = pb.CouponDetailVO
	CouponDiscountDTO       = pb.CouponDiscountDTO
	CouponDiscountListReply = pb.CouponDiscountListReply
	CouponFormDTO           = pb.CouponFormDTO
	CouponIssueFormDTO      = pb.CouponIssueFormDTO
	CouponListReply         = pb.CouponListReply
	CouponListRequest       = pb.CouponListRequest
	CouponPageReply         = pb.CouponPageReply
	CouponPageRequest       = pb.CouponPageRequest
	CouponPageVO            = pb.CouponPageVO
	CouponScopeVO           = pb.CouponScopeVO
	CouponVO                = pb.CouponVO
	Empty                   = pb.Empty
	ExchangeCodeVO          = pb.ExchangeCodeVO
	ExchangeRequest         = pb.ExchangeRequest
	IdRequest               = pb.IdRequest
	IdsRequest              = pb.IdsRequest
	OrderCouponDTO          = pb.OrderCouponDTO
	OrderCourseDTO          = pb.OrderCourseDTO
	OrderCourseListRequest  = pb.OrderCourseListRequest
	PageRequest             = pb.PageRequest
	RulesReply              = pb.RulesReply
	UserCouponPageReply     = pb.UserCouponPageReply
	UserCouponPageRequest   = pb.UserCouponPageRequest

	Promotion interface {
		// 优惠券管理
		CouponCreate(ctx context.Context, in *CouponFormDTO, opts ...grpc.CallOption) (*CouponDetailVO, error)
		CouponList(ctx context.Context, in *CouponListRequest, opts ...grpc.CallOption) (*CouponListReply, error)
		CouponPage(ctx context.Context, in *CouponPageRequest, opts ...grpc.CallOption) (*CouponPageReply, error)
		CouponGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CouponDetailVO, error)
		CouponDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
		CouponIssue(ctx context.Context, in *CouponIssueFormDTO, opts ...grpc.CallOption) (*Empty, error)
		CouponPause(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
		// 用户优惠券
		UserCouponAvailable(ctx context.Context, in *OrderCourseListRequest, opts ...grpc.CallOption) (*CouponDiscountListReply, error)
		UserCouponDiscount(ctx context.Context, in *OrderCouponDTO, opts ...grpc.CallOption) (*CouponDiscountDTO, error)
		UserCouponPage(ctx context.Context, in *UserCouponPageRequest, opts ...grpc.CallOption) (*UserCouponPageReply, error)
		UserCouponRefund(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error)
		UserCouponRules(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*RulesReply, error)
		UserCouponUse(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error)
		UserCouponExchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*Empty, error)
		UserCouponReceive(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
		// 兑换码
		CouponCodePage(ctx context.Context, in *CouponCodePageRequest, opts ...grpc.CallOption) (*CouponCodePageReply, error)
	}

	defaultPromotion struct {
		cli zrpc.Client
	}
)

func NewPromotion(cli zrpc.Client) Promotion {
	return &defaultPromotion{
		cli: cli,
	}
}

// 优惠券管理
func (m *defaultPromotion) CouponCreate(ctx context.Context, in *CouponFormDTO, opts ...grpc.CallOption) (*CouponDetailVO, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.CouponCreate(ctx, in, opts...)
}

func (m *defaultPromotion) CouponList(ctx context.Context, in *CouponListRequest, opts ...grpc.CallOption) (*CouponListReply, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.CouponList(ctx, in, opts...)
}

func (m *defaultPromotion) CouponPage(ctx context.Context, in *CouponPageRequest, opts ...grpc.CallOption) (*CouponPageReply, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.CouponPage(ctx, in, opts...)
}

func (m *defaultPromotion) CouponGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CouponDetailVO, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.CouponGet(ctx, in, opts...)
}

func (m *defaultPromotion) CouponDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.CouponDelete(ctx, in, opts...)
}

func (m *defaultPromotion) CouponIssue(ctx context.Context, in *CouponIssueFormDTO, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.CouponIssue(ctx, in, opts...)
}

func (m *defaultPromotion) CouponPause(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.CouponPause(ctx, in, opts...)
}

// 用户优惠券
func (m *defaultPromotion) UserCouponAvailable(ctx context.Context, in *OrderCourseListRequest, opts ...grpc.CallOption) (*CouponDiscountListReply, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.UserCouponAvailable(ctx, in, opts...)
}

func (m *defaultPromotion) UserCouponDiscount(ctx context.Context, in *OrderCouponDTO, opts ...grpc.CallOption) (*CouponDiscountDTO, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.UserCouponDiscount(ctx, in, opts...)
}

func (m *defaultPromotion) UserCouponPage(ctx context.Context, in *UserCouponPageRequest, opts ...grpc.CallOption) (*UserCouponPageReply, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.UserCouponPage(ctx, in, opts...)
}

func (m *defaultPromotion) UserCouponRefund(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.UserCouponRefund(ctx, in, opts...)
}

func (m *defaultPromotion) UserCouponRules(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*RulesReply, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.UserCouponRules(ctx, in, opts...)
}

func (m *defaultPromotion) UserCouponUse(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.UserCouponUse(ctx, in, opts...)
}

func (m *defaultPromotion) UserCouponExchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.UserCouponExchange(ctx, in, opts...)
}

func (m *defaultPromotion) UserCouponReceive(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.UserCouponReceive(ctx, in, opts...)
}

// 兑换码
func (m *defaultPromotion) CouponCodePage(ctx context.Context, in *CouponCodePageRequest, opts ...grpc.CallOption) (*CouponCodePageReply, error) {
	client := pb.NewPromotionClient(m.cli.Conn())
	return client.CouponCodePage(ctx, in, opts...)
}
