// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: learning.proto

package server

import (
	"context"

	"learning/rpc/internal/logic"
	"learning/rpc/internal/svc"
	"learning/rpc/pb/pb"
)

type LearningServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLearningServer
}

func NewLearningServer(svcCtx *svc.ServiceContext) *LearningServer {
	return &LearningServer{
		svcCtx: svcCtx,
	}
}

func (s *LearningServer) GetLesson(ctx context.Context, in *pb.LessonRequest) (*pb.LessonReply, error) {
	l := logic.NewGetLessonLogic(ctx, s.svcCtx)
	return l.GetLesson(in)
}

func (s *LearningServer) ListLessons(ctx context.Context, in *pb.ListLessonsRequest) (*pb.ListLessonsReply, error) {
	l := logic.NewListLessonsLogic(ctx, s.svcCtx)
	return l.ListLessons(in)
}

func (s *LearningServer) CreatePlan(ctx context.Context, in *pb.CreatePlanRequest) (*pb.EmptyReply, error) {
	l := logic.NewCreatePlanLogic(ctx, s.svcCtx)
	return l.CreatePlan(in)
}

func (s *LearningServer) RemoveLesson(ctx context.Context, in *pb.LessonRequest) (*pb.EmptyReply, error) {
	l := logic.NewRemoveLessonLogic(ctx, s.svcCtx)
	return l.RemoveLesson(in)
}

func (s *LearningServer) CountLessons(ctx context.Context, in *pb.CourseRequest) (*pb.CountReply, error) {
	l := logic.NewCountLessonsLogic(ctx, s.svcCtx)
	return l.CountLessons(in)
}

func (s *LearningServer) ValidateLesson(ctx context.Context, in *pb.LessonRequest) (*pb.ValidateReply, error) {
	l := logic.NewValidateLessonLogic(ctx, s.svcCtx)
	return l.ValidateLesson(in)
}

func (s *LearningServer) GrantCourses(ctx context.Context, in *pb.GrantCoursesRequest) (*pb.EmptyReply, error) {
	l := logic.NewGrantCoursesLogic(ctx, s.svcCtx)
	return l.GrantCourses(in)
}

func (s *LearningServer) RevokeCourses(ctx context.Context, in *pb.GrantCoursesRequest) (*pb.EmptyReply, error) {
	l := logic.NewRevokeCoursesLogic(ctx, s.svcCtx)
	return l.RevokeCourses(in)
}
