// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package search

import (
	"context"

	"tjxt/apps/search/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty            = pb.Empty
	IdReq            = pb.IdReq
	InterestsVO      = pb.InterestsVO
	SaveInterestsReq = pb.SaveInterestsReq

	Search interface {
		// 用户兴趣
		SaveInterests(ctx context.Context, in *SaveInterestsReq, opts ...grpc.CallOption) (*Empty, error)
		GetInterests(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*InterestsVO, error)
	}

	defaultSearch struct {
		cli zrpc.Client
	}
)

func NewSearch(cli zrpc.Client) Search {
	return &defaultSearch{
		cli: cli,
	}
}

// 用户兴趣
func (m *defaultSearch) SaveInterests(ctx context.Context, in *SaveInterestsReq, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewSearchClient(m.cli.Conn())
	return client.SaveInterests(ctx, in, opts...)
}

func (m *defaultSearch) GetInterests(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*InterestsVO, error) {
	client := pb.NewSearchClient(m.cli.Conn())
	return client.GetInterests(ctx, in, opts...)
}
