// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: promotion.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Promotion_CouponCreate_FullMethodName        = "/promotion.Promotion/CouponCreate"
	Promotion_CouponList_FullMethodName          = "/promotion.Promotion/CouponList"
	Promotion_CouponPage_FullMethodName          = "/promotion.Promotion/CouponPage"
	Promotion_CouponGet_FullMethodName           = "/promotion.Promotion/CouponGet"
	Promotion_CouponDelete_FullMethodName        = "/promotion.Promotion/CouponDelete"
	Promotion_CouponIssue_FullMethodName         = "/promotion.Promotion/CouponIssue"
	Promotion_CouponPause_FullMethodName         = "/promotion.Promotion/CouponPause"
	Promotion_UserCouponAvailable_FullMethodName = "/promotion.Promotion/UserCouponAvailable"
	Promotion_UserCouponDiscount_FullMethodName  = "/promotion.Promotion/UserCouponDiscount"
	Promotion_UserCouponPage_FullMethodName      = "/promotion.Promotion/UserCouponPage"
	Promotion_UserCouponRefund_FullMethodName    = "/promotion.Promotion/UserCouponRefund"
	Promotion_UserCouponRules_FullMethodName     = "/promotion.Promotion/UserCouponRules"
	Promotion_UserCouponUse_FullMethodName       = "/promotion.Promotion/UserCouponUse"
	Promotion_UserCouponExchange_FullMethodName  = "/promotion.Promotion/UserCouponExchange"
	Promotion_UserCouponReceive_FullMethodName   = "/promotion.Promotion/UserCouponReceive"
	Promotion_CouponCodePage_FullMethodName      = "/promotion.Promotion/CouponCodePage"
)

// PromotionClient is the client API for Promotion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===================== 服务 =====================
type PromotionClient interface {
	// 优惠券管理
	CouponCreate(ctx context.Context, in *CouponFormDTO, opts ...grpc.CallOption) (*CouponDetailVO, error)
	CouponList(ctx context.Context, in *CouponListRequest, opts ...grpc.CallOption) (*CouponListReply, error)
	CouponPage(ctx context.Context, in *CouponPageRequest, opts ...grpc.CallOption) (*CouponPageReply, error)
	CouponGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CouponDetailVO, error)
	CouponDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
	CouponIssue(ctx context.Context, in *CouponIssueFormDTO, opts ...grpc.CallOption) (*Empty, error)
	CouponPause(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
	// 用户优惠券
	UserCouponAvailable(ctx context.Context, in *OrderCourseListRequest, opts ...grpc.CallOption) (*CouponDiscountListReply, error)
	UserCouponDiscount(ctx context.Context, in *OrderCouponDTO, opts ...grpc.CallOption) (*CouponDiscountDTO, error)
	UserCouponPage(ctx context.Context, in *UserCouponPageRequest, opts ...grpc.CallOption) (*UserCouponPageReply, error)
	UserCouponRefund(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error)
	UserCouponRules(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*RulesReply, error)
	UserCouponUse(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error)
	UserCouponExchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*Empty, error)
	UserCouponReceive(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error)
	// 兑换码
	CouponCodePage(ctx context.Context, in *CouponCodePageRequest, opts ...grpc.CallOption) (*CouponCodePageReply, error)
}

type promotionClient struct {
	cc grpc.ClientConnInterface
}

func NewPromotionClient(cc grpc.ClientConnInterface) PromotionClient {
	return &promotionClient{cc}
}

func (c *promotionClient) CouponCreate(ctx context.Context, in *CouponFormDTO, opts ...grpc.CallOption) (*CouponDetailVO, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponDetailVO)
	err := c.cc.Invoke(ctx, Promotion_CouponCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) CouponList(ctx context.Context, in *CouponListRequest, opts ...grpc.CallOption) (*CouponListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponListReply)
	err := c.cc.Invoke(ctx, Promotion_CouponList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) CouponPage(ctx context.Context, in *CouponPageRequest, opts ...grpc.CallOption) (*CouponPageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponPageReply)
	err := c.cc.Invoke(ctx, Promotion_CouponPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) CouponGet(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*CouponDetailVO, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponDetailVO)
	err := c.cc.Invoke(ctx, Promotion_CouponGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) CouponDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Promotion_CouponDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) CouponIssue(ctx context.Context, in *CouponIssueFormDTO, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Promotion_CouponIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) CouponPause(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Promotion_CouponPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) UserCouponAvailable(ctx context.Context, in *OrderCourseListRequest, opts ...grpc.CallOption) (*CouponDiscountListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponDiscountListReply)
	err := c.cc.Invoke(ctx, Promotion_UserCouponAvailable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) UserCouponDiscount(ctx context.Context, in *OrderCouponDTO, opts ...grpc.CallOption) (*CouponDiscountDTO, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponDiscountDTO)
	err := c.cc.Invoke(ctx, Promotion_UserCouponDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) UserCouponPage(ctx context.Context, in *UserCouponPageRequest, opts ...grpc.CallOption) (*UserCouponPageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCouponPageReply)
	err := c.cc.Invoke(ctx, Promotion_UserCouponPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) UserCouponRefund(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Promotion_UserCouponRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) UserCouponRules(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*RulesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RulesReply)
	err := c.cc.Invoke(ctx, Promotion_UserCouponRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) UserCouponUse(ctx context.Context, in *IdsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Promotion_UserCouponUse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) UserCouponExchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Promotion_UserCouponExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) UserCouponReceive(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Promotion_UserCouponReceive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionClient) CouponCodePage(ctx context.Context, in *CouponCodePageRequest, opts ...grpc.CallOption) (*CouponCodePageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouponCodePageReply)
	err := c.cc.Invoke(ctx, Promotion_CouponCodePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionServer is the server API for Promotion service.
// All implementations must embed UnimplementedPromotionServer
// for forward compatibility.
//
// ===================== 服务 =====================
type PromotionServer interface {
	// 优惠券管理
	CouponCreate(context.Context, *CouponFormDTO) (*CouponDetailVO, error)
	CouponList(context.Context, *CouponListRequest) (*CouponListReply, error)
	CouponPage(context.Context, *CouponPageRequest) (*CouponPageReply, error)
	CouponGet(context.Context, *IdRequest) (*CouponDetailVO, error)
	CouponDelete(context.Context, *IdRequest) (*Empty, error)
	CouponIssue(context.Context, *CouponIssueFormDTO) (*Empty, error)
	CouponPause(context.Context, *IdRequest) (*Empty, error)
	// 用户优惠券
	UserCouponAvailable(context.Context, *OrderCourseListRequest) (*CouponDiscountListReply, error)
	UserCouponDiscount(context.Context, *OrderCouponDTO) (*CouponDiscountDTO, error)
	UserCouponPage(context.Context, *UserCouponPageRequest) (*UserCouponPageReply, error)
	UserCouponRefund(context.Context, *IdsRequest) (*Empty, error)
	UserCouponRules(context.Context, *IdsRequest) (*RulesReply, error)
	UserCouponUse(context.Context, *IdsRequest) (*Empty, error)
	UserCouponExchange(context.Context, *ExchangeRequest) (*Empty, error)
	UserCouponReceive(context.Context, *IdRequest) (*Empty, error)
	// 兑换码
	CouponCodePage(context.Context, *CouponCodePageRequest) (*CouponCodePageReply, error)
	mustEmbedUnimplementedPromotionServer()
}

// UnimplementedPromotionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromotionServer struct{}

func (UnimplementedPromotionServer) CouponCreate(context.Context, *CouponFormDTO) (*CouponDetailVO, error) {
	return nil, status.Error(codes.Unimplemented, "method CouponCreate not implemented")
}
func (UnimplementedPromotionServer) CouponList(context.Context, *CouponListRequest) (*CouponListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CouponList not implemented")
}
func (UnimplementedPromotionServer) CouponPage(context.Context, *CouponPageRequest) (*CouponPageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CouponPage not implemented")
}
func (UnimplementedPromotionServer) CouponGet(context.Context, *IdRequest) (*CouponDetailVO, error) {
	return nil, status.Error(codes.Unimplemented, "method CouponGet not implemented")
}
func (UnimplementedPromotionServer) CouponDelete(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CouponDelete not implemented")
}
func (UnimplementedPromotionServer) CouponIssue(context.Context, *CouponIssueFormDTO) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CouponIssue not implemented")
}
func (UnimplementedPromotionServer) CouponPause(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CouponPause not implemented")
}
func (UnimplementedPromotionServer) UserCouponAvailable(context.Context, *OrderCourseListRequest) (*CouponDiscountListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCouponAvailable not implemented")
}
func (UnimplementedPromotionServer) UserCouponDiscount(context.Context, *OrderCouponDTO) (*CouponDiscountDTO, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCouponDiscount not implemented")
}
func (UnimplementedPromotionServer) UserCouponPage(context.Context, *UserCouponPageRequest) (*UserCouponPageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCouponPage not implemented")
}
func (UnimplementedPromotionServer) UserCouponRefund(context.Context, *IdsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCouponRefund not implemented")
}
func (UnimplementedPromotionServer) UserCouponRules(context.Context, *IdsRequest) (*RulesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCouponRules not implemented")
}
func (UnimplementedPromotionServer) UserCouponUse(context.Context, *IdsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCouponUse not implemented")
}
func (UnimplementedPromotionServer) UserCouponExchange(context.Context, *ExchangeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCouponExchange not implemented")
}
func (UnimplementedPromotionServer) UserCouponReceive(context.Context, *IdRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCouponReceive not implemented")
}
func (UnimplementedPromotionServer) CouponCodePage(context.Context, *CouponCodePageRequest) (*CouponCodePageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CouponCodePage not implemented")
}
func (UnimplementedPromotionServer) mustEmbedUnimplementedPromotionServer() {}
func (UnimplementedPromotionServer) testEmbeddedByValue()                   {}

// UnsafePromotionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromotionServer will
// result in compilation errors.
type UnsafePromotionServer interface {
	mustEmbedUnimplementedPromotionServer()
}

func RegisterPromotionServer(s grpc.ServiceRegistrar, srv PromotionServer) {
	// If the following call panics, it indicates UnimplementedPromotionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Promotion_ServiceDesc, srv)
}

func _Promotion_CouponCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponFormDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).CouponCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_CouponCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).CouponCreate(ctx, req.(*CouponFormDTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_CouponList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).CouponList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_CouponList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).CouponList(ctx, req.(*CouponListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_CouponPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).CouponPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_CouponPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).CouponPage(ctx, req.(*CouponPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_CouponGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).CouponGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_CouponGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).CouponGet(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_CouponDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).CouponDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_CouponDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).CouponDelete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_CouponIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponIssueFormDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).CouponIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_CouponIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).CouponIssue(ctx, req.(*CouponIssueFormDTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_CouponPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).CouponPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_CouponPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).CouponPause(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_UserCouponAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCourseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).UserCouponAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_UserCouponAvailable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).UserCouponAvailable(ctx, req.(*OrderCourseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_UserCouponDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCouponDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).UserCouponDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_UserCouponDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).UserCouponDiscount(ctx, req.(*OrderCouponDTO))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_UserCouponPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCouponPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).UserCouponPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_UserCouponPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).UserCouponPage(ctx, req.(*UserCouponPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_UserCouponRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).UserCouponRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_UserCouponRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).UserCouponRefund(ctx, req.(*IdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_UserCouponRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).UserCouponRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_UserCouponRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).UserCouponRules(ctx, req.(*IdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_UserCouponUse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).UserCouponUse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_UserCouponUse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).UserCouponUse(ctx, req.(*IdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_UserCouponExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).UserCouponExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_UserCouponExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).UserCouponExchange(ctx, req.(*ExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_UserCouponReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).UserCouponReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_UserCouponReceive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).UserCouponReceive(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Promotion_CouponCodePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponCodePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServer).CouponCodePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Promotion_CouponCodePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServer).CouponCodePage(ctx, req.(*CouponCodePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Promotion_ServiceDesc is the grpc.ServiceDesc for Promotion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Promotion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "promotion.Promotion",
	HandlerType: (*PromotionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CouponCreate",
			Handler:    _Promotion_CouponCreate_Handler,
		},
		{
			MethodName: "CouponList",
			Handler:    _Promotion_CouponList_Handler,
		},
		{
			MethodName: "CouponPage",
			Handler:    _Promotion_CouponPage_Handler,
		},
		{
			MethodName: "CouponGet",
			Handler:    _Promotion_CouponGet_Handler,
		},
		{
			MethodName: "CouponDelete",
			Handler:    _Promotion_CouponDelete_Handler,
		},
		{
			MethodName: "CouponIssue",
			Handler:    _Promotion_CouponIssue_Handler,
		},
		{
			MethodName: "CouponPause",
			Handler:    _Promotion_CouponPause_Handler,
		},
		{
			MethodName: "UserCouponAvailable",
			Handler:    _Promotion_UserCouponAvailable_Handler,
		},
		{
			MethodName: "UserCouponDiscount",
			Handler:    _Promotion_UserCouponDiscount_Handler,
		},
		{
			MethodName: "UserCouponPage",
			Handler:    _Promotion_UserCouponPage_Handler,
		},
		{
			MethodName: "UserCouponRefund",
			Handler:    _Promotion_UserCouponRefund_Handler,
		},
		{
			MethodName: "UserCouponRules",
			Handler:    _Promotion_UserCouponRules_Handler,
		},
		{
			MethodName: "UserCouponUse",
			Handler:    _Promotion_UserCouponUse_Handler,
		},
		{
			MethodName: "UserCouponExchange",
			Handler:    _Promotion_UserCouponExchange_Handler,
		},
		{
			MethodName: "UserCouponReceive",
			Handler:    _Promotion_UserCouponReceive_Handler,
		},
		{
			MethodName: "CouponCodePage",
			Handler:    _Promotion_CouponCodePage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promotion.proto",
}
