// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	accountRoleFieldNames          = builder.RawFieldNames(&AccountRole{})
	accountRoleRows                = strings.Join(accountRoleFieldNames, ",")
	accountRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(accountRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	accountRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(accountRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAccountRoleIdPrefix = "cache:accountRole:id:"
)

type (
	accountRoleModel interface {
		Insert(ctx context.Context, data *AccountRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AccountRole, error)
		Update(ctx context.Context, data *AccountRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAccountRoleModel struct {
		sqlc.CachedConn
		table string
	}

	AccountRole struct {
		Id        int64 `db:"id"`
		AccountId int64 `db:"account_id"` // 账户id
		RoleId    int64 `db:"role_id"`    // 角色id
	}
)

func newAccountRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAccountRoleModel {
	return &defaultAccountRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`account_role`",
	}
}

func (m *defaultAccountRoleModel) Delete(ctx context.Context, id int64) error {
	accountRoleIdKey := fmt.Sprintf("%s%v", cacheAccountRoleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, accountRoleIdKey)
	return err
}

func (m *defaultAccountRoleModel) FindOne(ctx context.Context, id int64) (*AccountRole, error) {
	accountRoleIdKey := fmt.Sprintf("%s%v", cacheAccountRoleIdPrefix, id)
	var resp AccountRole
	err := m.QueryRowCtx(ctx, &resp, accountRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", accountRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountRoleModel) Insert(ctx context.Context, data *AccountRole) (sql.Result, error) {
	accountRoleIdKey := fmt.Sprintf("%s%v", cacheAccountRoleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, accountRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AccountId, data.RoleId)
	}, accountRoleIdKey)
	return ret, err
}

func (m *defaultAccountRoleModel) Update(ctx context.Context, data *AccountRole) error {
	accountRoleIdKey := fmt.Sprintf("%s%v", cacheAccountRoleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, accountRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.AccountId, data.RoleId, data.Id)
	}, accountRoleIdKey)
	return err
}

func (m *defaultAccountRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAccountRoleIdPrefix, primary)
}

func (m *defaultAccountRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", accountRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAccountRoleModel) tableName() string {
	return m.table
}
