// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	loginRecordFieldNames          = builder.RawFieldNames(&LoginRecord{})
	loginRecordRows                = strings.Join(loginRecordFieldNames, ",")
	loginRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(loginRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	loginRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(loginRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLoginRecordIdPrefix = "cache:loginRecord:id:"
)

type (
	loginRecordModel interface {
		Insert(ctx context.Context, data *LoginRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LoginRecord, error)
		Update(ctx context.Context, data *LoginRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLoginRecordModel struct {
		sqlc.CachedConn
		table string
	}

	LoginRecord struct {
		Id         int64          `db:"id"`          // 主键
		UserId     int64          `db:"user_id"`     // 用户id
		CellPhone  sql.NullString `db:"cell_phone"`  // 手机号码
		LoginTime  time.Time      `db:"login_time"`  // 登录时间
		LogoutTime sql.NullTime   `db:"logout_time"` // 登出时间
		LoginDate  sql.NullTime   `db:"login_date"`  // 登录日期
		Duration   int64          `db:"duration"`    // 登录时长，单位是秒
		Ipv4       string         `db:"ipv4"`        // ip地址
	}
)

func newLoginRecordModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLoginRecordModel {
	return &defaultLoginRecordModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`login_record`",
	}
}

func (m *defaultLoginRecordModel) Delete(ctx context.Context, id int64) error {
	loginRecordIdKey := fmt.Sprintf("%s%v", cacheLoginRecordIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, loginRecordIdKey)
	return err
}

func (m *defaultLoginRecordModel) FindOne(ctx context.Context, id int64) (*LoginRecord, error) {
	loginRecordIdKey := fmt.Sprintf("%s%v", cacheLoginRecordIdPrefix, id)
	var resp LoginRecord
	err := m.QueryRowCtx(ctx, &resp, loginRecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", loginRecordRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLoginRecordModel) Insert(ctx context.Context, data *LoginRecord) (sql.Result, error) {
	loginRecordIdKey := fmt.Sprintf("%s%v", cacheLoginRecordIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, loginRecordRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.CellPhone, data.LoginTime, data.LogoutTime, data.LoginDate, data.Duration, data.Ipv4)
	}, loginRecordIdKey)
	return ret, err
}

func (m *defaultLoginRecordModel) Update(ctx context.Context, data *LoginRecord) error {
	loginRecordIdKey := fmt.Sprintf("%s%v", cacheLoginRecordIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, loginRecordRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.CellPhone, data.LoginTime, data.LogoutTime, data.LoginDate, data.Duration, data.Ipv4, data.Id)
	}, loginRecordIdKey)
	return err
}

func (m *defaultLoginRecordModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLoginRecordIdPrefix, primary)
}

func (m *defaultLoginRecordModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", loginRecordRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLoginRecordModel) tableName() string {
	return m.table
}
