// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: learning.proto

package learning

import (
	"context"

	"tjxt/apps/learning/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CountReply          = pb.CountReply
	CourseRequest       = pb.CourseRequest
	CreatePlanRequest   = pb.CreatePlanRequest
	EmptyReply          = pb.EmptyReply
	GrantCoursesRequest = pb.GrantCoursesRequest
	LessonReply         = pb.LessonReply
	LessonRequest       = pb.LessonRequest
	ListLessonsReply    = pb.ListLessonsReply
	ListLessonsRequest  = pb.ListLessonsRequest
	ValidateReply       = pb.ValidateReply

	Learning interface {
		GetLesson(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LessonReply, error)
		ListLessons(ctx context.Context, in *ListLessonsRequest, opts ...grpc.CallOption) (*ListLessonsReply, error)
		CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*EmptyReply, error)
		RemoveLesson(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*EmptyReply, error)
		CountLessons(ctx context.Context, in *CourseRequest, opts ...grpc.CallOption) (*CountReply, error)
		ValidateLesson(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*ValidateReply, error)
		GrantCourses(ctx context.Context, in *GrantCoursesRequest, opts ...grpc.CallOption) (*EmptyReply, error)
		RevokeCourses(ctx context.Context, in *GrantCoursesRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	}

	defaultLearning struct {
		cli zrpc.Client
	}
)

func NewLearning(cli zrpc.Client) Learning {
	return &defaultLearning{
		cli: cli,
	}
}

func (m *defaultLearning) GetLesson(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*LessonReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.GetLesson(ctx, in, opts...)
}

func (m *defaultLearning) ListLessons(ctx context.Context, in *ListLessonsRequest, opts ...grpc.CallOption) (*ListLessonsReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.ListLessons(ctx, in, opts...)
}

func (m *defaultLearning) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.CreatePlan(ctx, in, opts...)
}

func (m *defaultLearning) RemoveLesson(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.RemoveLesson(ctx, in, opts...)
}

func (m *defaultLearning) CountLessons(ctx context.Context, in *CourseRequest, opts ...grpc.CallOption) (*CountReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.CountLessons(ctx, in, opts...)
}

func (m *defaultLearning) ValidateLesson(ctx context.Context, in *LessonRequest, opts ...grpc.CallOption) (*ValidateReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.ValidateLesson(ctx, in, opts...)
}

func (m *defaultLearning) GrantCourses(ctx context.Context, in *GrantCoursesRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.GrantCourses(ctx, in, opts...)
}

func (m *defaultLearning) RevokeCourses(ctx context.Context, in *GrantCoursesRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	client := pb.NewLearningClient(m.cli.Conn())
	return client.RevokeCourses(ctx, in, opts...)
}
