// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: course.proto

package server

import (
	"context"

	"tjxt/apps/course/rpc/internal/logic"
	"tjxt/apps/course/rpc/internal/svc"
	"tjxt/apps/course/rpc/pb"
)

type CourseServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCourseServer
}

func NewCourseServer(svcCtx *svc.ServiceContext) *CourseServer {
	return &CourseServer{
		svcCtx: svcCtx,
	}
}

// ===== 分类管理 =====
func (s *CourseServer) CategoryAdd(ctx context.Context, in *pb.CategoryAddRequest) (*pb.Empty, error) {
	l := logic.NewCategoryAddLogic(ctx, s.svcCtx)
	return l.CategoryAdd(in)
}

func (s *CourseServer) CategoryUpdate(ctx context.Context, in *pb.CategoryUpdateRequest) (*pb.Empty, error) {
	l := logic.NewCategoryUpdateLogic(ctx, s.svcCtx)
	return l.CategoryUpdate(in)
}

func (s *CourseServer) CategoryDelete(ctx context.Context, in *pb.IdRequest) (*pb.Empty, error) {
	l := logic.NewCategoryDeleteLogic(ctx, s.svcCtx)
	return l.CategoryDelete(in)
}

func (s *CourseServer) CategoryDisableOrEnable(ctx context.Context, in *pb.CategoryStatusRequest) (*pb.Empty, error) {
	l := logic.NewCategoryDisableOrEnableLogic(ctx, s.svcCtx)
	return l.CategoryDisableOrEnable(in)
}

func (s *CourseServer) CategoryGet(ctx context.Context, in *pb.IdRequest) (*pb.CategoryInfo, error) {
	l := logic.NewCategoryGetLogic(ctx, s.svcCtx)
	return l.CategoryGet(in)
}

func (s *CourseServer) CategoryListAll(ctx context.Context, in *pb.CategoryListAllRequest) (*pb.CategoryNodeList, error) {
	l := logic.NewCategoryListAllLogic(ctx, s.svcCtx)
	return l.CategoryListAll(in)
}

func (s *CourseServer) CategoryListOneLevel(ctx context.Context, in *pb.Empty) (*pb.CategoryList, error) {
	l := logic.NewCategoryListOneLevelLogic(ctx, s.svcCtx)
	return l.CategoryListOneLevel(in)
}

func (s *CourseServer) CategoryListQuery(ctx context.Context, in *pb.CategoryListQueryRequest) (*pb.CategoryList, error) {
	l := logic.NewCategoryListQueryLogic(ctx, s.svcCtx)
	return l.CategoryListQuery(in)
}

// ===== 课程基础信息 =====
func (s *CourseServer) CourseBaseInfoGet(ctx context.Context, in *pb.IdRequest) (*pb.CourseBaseInfoView, error) {
	l := logic.NewCourseBaseInfoGetLogic(ctx, s.svcCtx)
	return l.CourseBaseInfoGet(in)
}

func (s *CourseServer) CourseBaseInfoSave(ctx context.Context, in *pb.CourseBaseInfoSaveRequest) (*pb.IdResponse, error) {
	l := logic.NewCourseBaseInfoSaveLogic(ctx, s.svcCtx)
	return l.CourseBaseInfoSave(in)
}

func (s *CourseServer) CourseCheckName(ctx context.Context, in *pb.CourseCheckNameRequest) (*pb.NameExistReply, error) {
	l := logic.NewCourseCheckNameLogic(ctx, s.svcCtx)
	return l.CourseCheckName(in)
}

func (s *CourseServer) CourseDelete(ctx context.Context, in *pb.IdRequest) (*pb.Empty, error) {
	l := logic.NewCourseDeleteLogic(ctx, s.svcCtx)
	return l.CourseDelete(in)
}

func (s *CourseServer) CoursePageQuery(ctx context.Context, in *pb.CoursePageQueryRequest) (*pb.CoursePageQueryReply, error) {
	l := logic.NewCoursePageQueryLogic(ctx, s.svcCtx)
	return l.CoursePageQuery(in)
}

func (s *CourseServer) CoursePortalQuery(ctx context.Context, in *pb.CoursePortalQueryRequest) (*pb.CoursePageQueryReply, error) {
	l := logic.NewCoursePortalQueryLogic(ctx, s.svcCtx)
	return l.CoursePortalQuery(in)
}

func (s *CourseServer) CourseSimpleInfoList(ctx context.Context, in *pb.CourseSimpleInfoQueryRequest) (*pb.CourseSimpleInfoListReply, error) {
	l := logic.NewCourseSimpleInfoListLogic(ctx, s.svcCtx)
	return l.CourseSimpleInfoList(in)
}

func (s *CourseServer) CourseFullInfoGet(ctx context.Context, in *pb.CourseFullInfoGetRequest) (*pb.CourseFullInfo, error) {
	l := logic.NewCourseFullInfoGetLogic(ctx, s.svcCtx)
	return l.CourseFullInfoGet(in)
}

func (s *CourseServer) CourseSearchInfoForIndex(ctx context.Context, in *pb.IdRequest) (*pb.CourseSearchIndexInfo, error) {
	l := logic.NewCourseSearchInfoForIndexLogic(ctx, s.svcCtx)
	return l.CourseSearchInfoForIndex(in)
}

func (s *CourseServer) CourseName2Ids(ctx context.Context, in *pb.CourseNameRequest) (*pb.CourseIdList, error) {
	l := logic.NewCourseName2IdsLogic(ctx, s.svcCtx)
	return l.CourseName2Ids(in)
}

func (s *CourseServer) CourseInfoByTeacherIds(ctx context.Context, in *pb.TeacherIdsRequest) (*pb.TeacherCourseCountList, error) {
	l := logic.NewCourseInfoByTeacherIdsLogic(ctx, s.svcCtx)
	return l.CourseInfoByTeacherIds(in)
}

func (s *CourseServer) CourseSectionGet(ctx context.Context, in *pb.IdRequest) (*pb.CourseSectionInfo, error) {
	l := logic.NewCourseSectionGetLogic(ctx, s.svcCtx)
	return l.CourseSectionGet(in)
}

func (s *CourseServer) CourseMediaUseInfo(ctx context.Context, in *pb.MediaIdsRequest) (*pb.MediaQuoteList, error) {
	l := logic.NewCourseMediaUseInfoLogic(ctx, s.svcCtx)
	return l.CourseMediaUseInfo(in)
}

func (s *CourseServer) CourseGenerator(ctx context.Context, in *pb.Empty) (*pb.IdResponse, error) {
	l := logic.NewCourseGeneratorLogic(ctx, s.svcCtx)
	return l.CourseGenerator(in)
}

// ===== 课程目录 (catalogue) =====
func (s *CourseServer) CourseCatalogsGet(ctx context.Context, in *pb.IdRequest) (*pb.CourseAndSectionView, error) {
	l := logic.NewCourseCatalogsGetLogic(ctx, s.svcCtx)
	return l.CourseCatalogsGet(in)
}

func (s *CourseServer) CourseCatalogueTreeGet(ctx context.Context, in *pb.CourseCatalogueQueryRequest) (*pb.CatalogueTreeList, error) {
	l := logic.NewCourseCatalogueTreeGetLogic(ctx, s.svcCtx)
	return l.CourseCatalogueTreeGet(in)
}

func (s *CourseServer) CourseCatalogueSave(ctx context.Context, in *pb.CourseCatalogueSaveRequest) (*pb.Empty, error) {
	l := logic.NewCourseCatalogueSaveLogic(ctx, s.svcCtx)
	return l.CourseCatalogueSave(in)
}

func (s *CourseServer) CourseCatalogueIndexList(ctx context.Context, in *pb.IdRequest) (*pb.CataSimpleList, error) {
	l := logic.NewCourseCatalogueIndexListLogic(ctx, s.svcCtx)
	return l.CourseCatalogueIndexList(in)
}

func (s *CourseServer) CourseCatalogueSectionInfo(ctx context.Context, in *pb.IdRequest) (*pb.CourseSectionInfo, error) {
	l := logic.NewCourseCatalogueSectionInfoLogic(ctx, s.svcCtx)
	return l.CourseCatalogueSectionInfo(in)
}

func (s *CourseServer) CourseCatalogueBatchQuery(ctx context.Context, in *pb.IdsRequest) (*pb.CataSimpleList, error) {
	l := logic.NewCourseCatalogueBatchQueryLogic(ctx, s.svcCtx)
	return l.CourseCatalogueBatchQuery(in)
}

// ===== 章节/小节的题目 =====
func (s *CourseServer) CourseSubjectsGet(ctx context.Context, in *pb.IdRequest) (*pb.CataSubjectInfoList, error) {
	l := logic.NewCourseSubjectsGetLogic(ctx, s.svcCtx)
	return l.CourseSubjectsGet(in)
}

func (s *CourseServer) CourseSubjectsSave(ctx context.Context, in *pb.CourseSubjectsSaveRequest) (*pb.Empty, error) {
	l := logic.NewCourseSubjectsSaveLogic(ctx, s.svcCtx)
	return l.CourseSubjectsSave(in)
}

// ===== 课程媒体 =====
func (s *CourseServer) CourseMediaSave(ctx context.Context, in *pb.CourseMediaSaveRequest) (*pb.Empty, error) {
	l := logic.NewCourseMediaSaveLogic(ctx, s.svcCtx)
	return l.CourseMediaSave(in)
}

// ===== 课程老师 =====
func (s *CourseServer) CourseTeachersGet(ctx context.Context, in *pb.CourseTeachersGetRequest) (*pb.TeacherInfoList, error) {
	l := logic.NewCourseTeachersGetLogic(ctx, s.svcCtx)
	return l.CourseTeachersGet(in)
}

func (s *CourseServer) CourseTeachersSave(ctx context.Context, in *pb.CourseTeachersSaveRequest) (*pb.Empty, error) {
	l := logic.NewCourseTeachersSaveLogic(ctx, s.svcCtx)
	return l.CourseTeachersSave(in)
}

// ===== 上下架 =====
func (s *CourseServer) CourseUpShelf(ctx context.Context, in *pb.IdRequest) (*pb.Empty, error) {
	l := logic.NewCourseUpShelfLogic(ctx, s.svcCtx)
	return l.CourseUpShelf(in)
}

func (s *CourseServer) CourseDownShelf(ctx context.Context, in *pb.IdRequest) (*pb.Empty, error) {
	l := logic.NewCourseDownShelfLogic(ctx, s.svcCtx)
	return l.CourseDownShelf(in)
}

func (s *CourseServer) CourseCheckUpShelf(ctx context.Context, in *pb.IdRequest) (*pb.Empty, error) {
	l := logic.NewCourseCheckUpShelfLogic(ctx, s.svcCtx)
	return l.CourseCheckUpShelf(in)
}

func (s *CourseServer) CourseUp(ctx context.Context, in *pb.IdsRequest) (*pb.Empty, error) {
	l := logic.NewCourseUpLogic(ctx, s.svcCtx)
	return l.CourseUp(in)
}

func (s *CourseServer) CourseDown(ctx context.Context, in *pb.IdsRequest) (*pb.Empty, error) {
	l := logic.NewCourseDownLogic(ctx, s.svcCtx)
	return l.CourseDown(in)
}
