// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CouponCodePageReq struct {
	PageRequest
	CouponId int64  `form:"couponId,optional"`
	Status   string `form:"status,optional"`
}

type CouponCodePageResp struct {
	List  []ExchangeCodeVO `json:"list"`
	Total int64            `json:"total"`
	Pages int64            `json:"pages"`
}

type CouponDetailVO struct {
	Id                int64           `json:"id"`
	Name              string          `json:"name"`
	DiscountType      string          `json:"discountType"`
	DiscountValue     int64           `json:"discountValue"`
	MaxDiscountAmount int64           `json:"maxDiscountAmount"`
	ThresholdAmount   int64           `json:"thresholdAmount"`
	ObtainWay         string          `json:"obtainWay"`
	Specific          bool            `json:"specific"`
	Scopes            []CouponScopeVO `json:"scopes,optional"`
	IssueBeginTime    string          `json:"issueBeginTime,optional"`
	IssueEndTime      string          `json:"issueEndTime,optional"`
	TermBeginTime     string          `json:"termBeginTime,optional"`
	TermDays          int64           `json:"termDays,optional"`
	TermEndTime       string          `json:"termEndTime,optional"`
	TotalNum          int64           `json:"totalNum"`
	UserLimit         int64           `json:"userLimit"`
	Status            string          `json:"status,optional"`
}

type CouponDiscountListResp struct {
	List []CouponDiscountVO `json:"list"`
}

type CouponDiscountVO struct {
	DiscountAmount int64            `json:"discountAmount"`
	DiscountDetail map[string]int64 `json:"discountDetail,optional"`
	Ids            []int64          `json:"ids,optional"`
	Rules          []string         `json:"rules,optional"`
}

type CouponFormReq struct {
	Id                int64   `json:"id,optional"`
	Name              string  `json:"name"`
	DiscountType      string  `json:"discountType"`
	DiscountValue     int64   `json:"discountValue"`
	MaxDiscountAmount int64   `json:"maxDiscountAmount,optional"`
	ThresholdAmount   int64   `json:"thresholdAmount,optional"`
	ObtainWay         string  `json:"obtainWay"`
	Specific          bool    `json:"specific,optional"`
	Scopes            []int64 `json:"scopes,optional"`
	TotalNum          int64   `json:"totalNum,optional"`
	UserLimit         int64   `json:"userLimit,optional"`
}

type CouponIdReq struct {
	Id int64 `path:"id"`
}

type CouponIdsReq struct {
	CouponIds []int64 `form:"couponIds"`
	OrderId   int64   `form:"orderId,optional"`
}

type CouponIssueReq struct {
	Id             int64  `path:"id"`
	IssueBeginTime string `json:"issueBeginTime,optional"`
	IssueEndTime   string `json:"issueEndTime,optional"`
	TermBeginTime  string `json:"termBeginTime,optional"`
	TermDays       int64  `json:"termDays,optional"`
	TermEndTime    string `json:"termEndTime,optional"`
}

type CouponListResp struct {
	List []CouponVO `json:"list"`
}

type CouponPageReq struct {
	PageRequest
	Name   string `form:"name,optional"`
	Status string `form:"status,optional"`
	Type   string `form:"type,optional"`
}

type CouponPageResp struct {
	List  []CouponPageVO `json:"list"`
	Total int64          `json:"total"`
	Pages int64          `json:"pages"`
}

type CouponPageVO struct {
	Id                int64  `json:"id"`
	Name              string `json:"name"`
	DiscountType      string `json:"discountType"`
	DiscountValue     int64  `json:"discountValue"`
	MaxDiscountAmount int64  `json:"maxDiscountAmount"`
	ThresholdAmount   int64  `json:"thresholdAmount"`
	Specific          bool   `json:"specific"`
	ObtainWay         string `json:"obtainWay"`
	TotalNum          int64  `json:"totalNum"`
	IssueNum          int64  `json:"issueNum"`
	UsedNum           int64  `json:"usedNum"`
	Status            string `json:"status"`
	TermDays          int64  `json:"termDays,optional"`
	TermBeginTime     string `json:"termBeginTime,optional"`
	TermEndTime       string `json:"termEndTime,optional"`
	IssueBeginTime    string `json:"issueBeginTime,optional"`
	IssueEndTime      string `json:"issueEndTime,optional"`
	CreateTime        string `json:"createTime,optional"`
}

type CouponReceiveReq struct {
	CouponId int64 `path:"couponId"`
}

type CouponScopeVO struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type CouponVO struct {
	Id                int64  `json:"id"`
	Name              string `json:"name"`
	DiscountType      string `json:"discountType"`
	DiscountValue     int64  `json:"discountValue"`
	MaxDiscountAmount int64  `json:"maxDiscountAmount"`
	ThresholdAmount   int64  `json:"thresholdAmount"`
	Specific          bool   `json:"specific"`
	TermDays          int64  `json:"termDays,optional"`
	TermEndTime       string `json:"termEndTime,optional"`
	Available         bool   `json:"available,optional"`
	Received          bool   `json:"received,optional"`
}

type ExchangeByCodeReq struct {
	Code string `path:"code"`
}

type ExchangeCodeVO struct {
	Id   int64  `json:"id"`
	Code string `json:"code"`
}

type OrderCouponReq struct {
	CourseList    []OrderCourseItem `json:"courseList"`
	UserCouponIds []int64           `json:"userCouponIds,optional"`
}

type OrderCourseItem struct {
	CateId int64 `json:"cateId,optional"`
	Id     int64 `json:"id"`
	Price  int64 `json:"price"`
}

type PageRequest struct {
	PageNo   int64  `form:"pageNo,optional"`
	PageSize int64  `form:"pageSize,optional"`
	IsAsc    bool   `form:"isAsc,optional"`
	SortBy   string `form:"sortBy,optional"`
}

type RulesResp struct {
	Rules []string `json:"rules"`
}

type UserCouponAvailableReq struct {
	CourseList []OrderCourseItem `json:"courseList"`
}

type UserCouponPageReq struct {
	PageRequest
	Status string `form:"status,optional"`
}

type UserCouponPageResp struct {
	List  []CouponVO `json:"list"`
	Total int64      `json:"total"`
	Pages int64      `json:"pages"`
}
