// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: search.proto

package server

import (
	"context"

	"tjxt/apps/search/rpc/internal/logic"
	"tjxt/apps/search/rpc/internal/svc"
	"tjxt/apps/search/rpc/pb"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

// 用户兴趣
func (s *SearchServer) SaveInterests(ctx context.Context, in *pb.SaveInterestsReq) (*pb.Empty, error) {
	l := logic.NewSaveInterestsLogic(ctx, s.svcCtx)
	return l.SaveInterests(in)
}

func (s *SearchServer) GetInterests(ctx context.Context, in *pb.IdReq) (*pb.InterestsVO, error) {
	l := logic.NewGetInterestsLogic(ctx, s.svcCtx)
	return l.GetInterests(in)
}
